### ISSUE TITLE
Different IO total size between the output and files' total length

### ISSUE THREAD

**Issue by Hannah-xxl** [axboe/fio#836] opened 2019-10-08 08:06 UTC
I am doing a file-writing-test with fio 2.1.10, and find that the output total size for write io is different with the sum of files' length. Why? Is it because the fio not take completed io into account after time exhausting?

My job file is like this

> [global]
fallocate=none
file_append=1
file_service_type=sequential
filesize=1073741824
lockfile=exclusive
directory=<there are a large number of files>
ioengine=sync
fsync=1
bs=64k
direct=1
runtime=60s
time_based
group_reporting
> 
> [job_0]
filename=<some files>
rw=write
openfiles=1
> 
> [job_1]
filename=<some other files>
rw=write
openfiles=1
> 
> ......

I suppose they will be equal to each other because I have used "append" and "sequential" test flag with each job, which means a job will finish one file before moving to the next according to fio.

**Comment by sitsofe** [comment] 2019-10-08 10:50
> I am doing a file-writing-test with fio 2.1.10

I'm afraid we only support the latest fio - can you reproduce this issue with a newer fio? See https://github.com/axboe/fio/releases for which version we're up to.

**Comment by Hannah-xxl** [comment] 2019-10-09 07:08
All right, I will use a latest fio, that is 3.16, to try again and post the problem here.

**Comment by sitsofe** [comment] 2019-11-01 08:35
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2019-11-01 08:35 UTC
Labels: needinfo
