### ISSUE TITLE
randwrite test for two hours,get only 7119 result

### ISSUE THREAD

**Issue by clzeasystack** [axboe/fio#412] opened 2017-07-26 03:10 UTC
When I do fio test by using these parameter：
[global]
bs=4k
ioengine=libaio
iodepth=4
size=10g
direct=1
runtime=7200
numjobs=1
#directory=/mount-point-of-ssd
filename=/dev/sdc

[rand-write]
rw=randwrite
time_based
write_iops_log=write_iops_log
log_avg_msec=1000
stonewall

I can not get 7200 data but 7119 instead. I find the lost data is not in the same place.
I have try many times and every time lost data,but when I change runtime to 3600 or less,it has no this problem.
I wonder that if the lost data is because the computer can not print the data result accurately per second. Or someone else has also meet the problem?

**Comment by sitsofe** [comment] 2017-07-26 05:40
Sorry, I'm struggling understand a few of your sentences. Further when reporting a bug it's also useful for you to include the output and the version of fio you are running would help as described over in https://github.com/axboe/fio/blob/fio-2.99/REPORTING-BUGS . Finally this sounds more like a "How do I/Why is this happening?" rather than a bug so it might be more appropriate for the mailing list (see https://github.com/axboe/fio/blob/fio-2.99/README#L58 ). However let me take an initial guess at what you mean:

> I can not get 7200 data but 7119 instead.

If you mean the job only ran for 7119 rather than 7200 seconds then that could be because you hit another limit first (e.g. you had done [`size`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-size) amount of I/O before 7200 seconds had passed). By itself [`runtime`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-runtime) sets a maximum time to run - you would need to also use [`time_based`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-time-based) if you want it to loop until 7200 seconds had passed. Follow the links included for more explanations.

> I find the lost data is not in the same place.

Do you mean "I found it ran for different amounts of time before stopping". If so this would be expected as perhaps your disk/system's performance is changing over time so it takes slightly different amounts of time to write 10 gigabytes. If you don't mean this could you reword things and explain the issue another way?

If this explains the problem you're seeing could you close this issue? Thanks!

**Comment by clzeasystack** [comment] 2017-07-26 12:40
I am sorry  for not  write the issue clearly.And thank you for your reminding.
I now  write the issue  as []https://github.com/axboe/fio/blob/fio-2.99/REPORTING-BUGS(url)
1.The issue is that when I set the two parameters ’write_iops_log=write_iops_log‘ and 'log_avg_msec=1000' in my test script to write the iops result to log.
    I set runtime=7200 and "time_base" .I think I will get 7200 iops data in the write_iops_log_iops.1.log,but I can only get 7119 iops data.
    I have tried four times,Three  times runtime=7200 and one time runtime=3600, I set time_base everytime. when runtime=3600, I can get 3600 iops data in write_iops_log_iops.1.log .When I set runtime=7200, I can only get 7199 or less iops data in write_iops_log_iops.1.log  every time.
2.Linux distro version, kernel version：Linux version 3.10.0-327.el7.x86_64
3.fio version is fio-2.19-13-gd7658-dirty
4. my fio test setting:
[global]
bs=4k
ioengine=libaio
iodepth=4
size=10g
direct=1
runtime=7200
numjobs=1
#directory=/mount-point-of-ssd
filename=/dev/sdc

[rand-write]
rw=randwrite
time_based
write_iops_log=write_iops_log
log_avg_msec=1000
stonewall

**Comment by clzeasystack** [comment] 2017-07-26 12:52
what's more,this issue is not mean ran for 7119, it run for 7200 times.just only 7119 iops data in log.
the time is also 7200.for example, iops data of 5100 and 5101 not print in the log.

**Comment by szaydel** [comment] 2017-07-26 13:26
Notice the avg in the name of the feature: `log_avg_msec`. This means data will be on average recorded over 1000ms intervals. Average means you are not likely to get exactly 7200 you expect to get.

**Comment by sitsofe** [comment] 2017-07-26 13:28
@clzeasystack OK I see what you mean - you expect the log file to have 7200 rows inside it but sometimes has dramatically less and there are some seconds that are missing entires entirely. 

There have been various time accuracy fixes made since 2.19 - does the problem still happen with the latest version of fio (2.99)?

Another problem you might run into is that the creation of an entry could be linked to when the I/Os complete. It might be that if the I/Os don't complete for say 10 seconds there are no entries across those seconds at all. If you use the appropriate [`io_submit_mode`](http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-io-submit-mode) does that make the problem any better?

**Comment by sitsofe** [comment] 2017-08-14 13:03
@clzeasystack - have you had a chance to reproduce this with fio 2.99 or later?

**Comment by clzeasystack** [comment] 2017-08-14 15:51
I have not chance to  test  it in real working condition yet. I test it in my own computer, fio 2.99 don't have
the problem no more. I think it's ok now.
Thank you very much.

**Comment by sitsofe** [comment] 2017-08-14 17:31
@clzeasystack if you think this one has vanished away feel free to close this issue but if you see it again in a recent build you can always reopen it.

**Comment by sitsofe** [comment] 2017-08-27 09:11
@clzeasystack could you mark this issue as closed? I'm afraid I don't have the permissions to do so...

**Closed** 2017-08-27 16:07 UTC

**Comment by clzeasystack** [comment] 2017-08-28 04:07
@sitsofe  Thankyou for your  reminding. Now @axboe has close the issue,thank you for @axboe. 
I will close issue after it is sloved next time.
