### ISSUE TITLE
How to avoid error message "Multiple writers may overwrite blocks that belong to other jobs. This can cause verification failures."

### ISSUE THREAD

**Issue by ashokkumaralluri** [axboe/fio#303] opened 2017-02-04 06:45 UTC
Fio version: fio-2.9
**FIO command:**
fio  --name=integrity_test  --nrfiles=64 --ioengine=libaio  --iodepth=50 --rw=randwrite  --bs=4k --filesize=16m  --numjobs=5 --runtime=1500  --group_reporting --do_verify=1  --directory=/tmp  --continue_on_error=none  --verify=sha1 --fallocate=0 

**Output**

```
Multiple writers may overwrite blocks that belong to other jobs. This can cause verification failures.
integrity_test: (g=0): rw=randwrite, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=50
...
fio-2.9
Starting 5 processes
integrity_test: Laying out IO file(s) (64 file(s) / 64MB)
integrity_test: Laying out IO file(s) (64 file(s) / 64MB)
integrity_test: Laying out IO file(s) (64 file(s) / 64MB)
integrity_test: Laying out IO file(s) (64 file(s) / 64MB)
integrity_test: Laying out IO file(s) (64 file(s) / 64MB)
Jobs: 5 (f=320)
integrity_test: (groupid=0, jobs=5): err= 0: pid=21812: Fri Feb  3 22:41:18 2017
  read : io=327680KB, bw=231086KB/s, iops=57771, runt=  1418msec
    slat (usec): min=0, max=63373, avg=26.36, stdev=637.56
    clat (usec): min=6, max=653473, avg=2698.35, stdev=23139.37
     lat (usec): min=7, max=653654, avg=2724.74, stdev=23174.56
    clat percentiles (usec):
     |  1.00th=[  358],  5.00th=[  358], 10.00th=[  358], 20.00th=[  378],
     | 30.00th=[  418], 40.00th=[  636], 50.00th=[  732], 60.00th=[  788],
     | 70.00th=[ 1320], 80.00th=[ 1528], 90.00th=[ 1880], 95.00th=[ 1992],
     | 99.00th=[31872], 99.50th=[85504], 99.90th=[460800], 99.95th=[518144],
     | 99.99th=[593920]
  write: io=327680KB, bw=1103.5MB/s, iops=282482, runt=   290msec
    slat (usec): min=1, max=89, avg= 3.02, stdev= 1.40
    clat (usec): min=0, max=55136, avg=710.80, stdev=2115.96
     lat (usec): min=3, max=55140, avg=713.88, stdev=2116.16
    clat percentiles (usec):
     |  1.00th=[  470],  5.00th=[  486], 10.00th=[  498], 20.00th=[  516],
     | 30.00th=[  524], 40.00th=[  532], 50.00th=[  532], 60.00th=[  540],
     | 70.00th=[  548], 80.00th=[  716], 90.00th=[ 1012], 95.00th=[ 1032],
     | 99.00th=[ 1032], 99.50th=[ 1096], 99.90th=[52480], 99.95th=[54016],
     | 99.99th=[55040]
    bw (KB  /s): min=77926, max=118082, per=8.92%, avg=100739.60, stdev=15126.52
    lat (usec) : 2=0.01%, 10=0.01%, 20=0.01%, 50=0.02%, 100=0.04%
    lat (usec) : 250=0.10%, 500=21.14%, 750=45.04%, 1000=9.92%
    lat (msec) : 2=21.19%, 4=1.20%, 10=0.33%, 20=0.29%, 50=0.32%
    lat (msec) : 100=0.25%, 250=0.04%, 500=0.09%, 750=0.03%
  cpu          : usr=21.15%, sys=5.99%, ctx=9063, majf=0, minf=2260
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=99.8%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued    : total=r=81920/w=81920/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=50

Run status group 0 (all jobs):
   READ: io=327680KB, aggrb=231086KB/s, minb=231086KB/s, maxb=231086KB/s, mint=1418msec, maxt=1418msec
  WRITE: io=327680KB, aggrb=1103.5MB/s, minb=1103.5MB/s, maxb=1103.5MB/s, mint=290msec, maxt=290msec

Disk stats (read/write):
  sda: ios=5222/663, merge=0/76, ticks=1852/95774, in_queue=97623, util=78.09%

```
How to avoid the message and do proper integrity test, "_Multiple writers may overwrite blocks that belong to other jobs. This can cause verification failures_."  ?

Please help me on this .

**Comment by sitsofe** [comment] 2017-02-04 08:11
(iodepth=50 probably isn't having the impact you want. See the caveats in the HOWTO: http://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-iodepth and also be aware your  filesystem may not deal with async IO in an optimal way)

The message is only a warning and contains the word "may" so it doesn't necessarily mean that something is wrong. See https://github.com/axboe/fio/blob/f0ac17190989b4ada1d4d74be8d7a4ef3a76dfbb/init.c#L734 which shows it triggers whenever you are doing verified writes with numjobs bigger than one. Even if the jobs are **not** overwriting ranges of the *same file* before verification (and thus can't harm each other) the warning will still appear.

**Comment by ashokkumaralluri** [comment] 2017-02-04 15:08
Thanks sitsofe for the reply. So using direct=1 may give the expected results. I will also check that. But the output in my earlier comment says 99% seen 32 IO depth. Please help me correct my understanding here.
IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, **32=99.8%**, >=64=0.0%

I think, this warning message may be misleading in case verification tests. Please consider if it is  possible to remove this message or change it to convey recommendations to run the test.

Btw, to be sure and to be on safe side, do you think using _--lockfile= readwrite_ option would be helpful to avoid the conditions that message warns about?  Is it good recommendation to use this option?

Thanks,
Ashok

**Comment by sitsofe** [comment] 2017-02-04 17:15
> IO depths : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=99.8%, >=64=0.0%

That's the average fio queued up internally (without being told "I'm too busy" from the I/O engine) - not necessarily how much was ultimately submitted *simultaneously* at the lowest layers. Try using iostat -x on Linux while a single job is running to see what depth the device is achieving - is it 32 or above?

Re the warning: it's possible to make it more accurate but it's a tradeoff between complexity and false positives/negatives. Perhaps you could limit the warning to if the filename parameter is set on the basis that jobs in most ioengines will work on unique files otherwise? I don't know if my thinking there is correct...

Re locking - I'm not sure if it would make a difference, it depends on how locking works (I haven't checked). For example imagine I have two jobs a and b:
```
Job a locks file f
Job a writes 1s at block 0
Job a unlocks file f
Job b locks file f
Job b writes 2s at block 0
Job b unlocks file f
Job a locks file f
Job a verifies 1s at block 0
Job a reports a mismatch because Job b overwrote the data at block 0 with 2s
```

If the locking allows that interleaving how does it prevent the example situation? You might just be adding overhead for no gain...

**Comment by ashokkumaralluri** [comment] 2017-02-05 17:47
Thanks for iostat command and as well as the locking mechanism example.

This question is raised all because of , I am hitting frequent error message "_verify: bad magic header b270, wanted acca at file_"  frequently, just trying to understand is this the right corruption  or not. After reading "Multiple writers" warning message I got confused to decide on.  

Thanks,
Ashok

**Comment by sitsofe** [comment] 2017-02-05 18:28
@ashokkumaralluri Can you reproduce the problem with the newest fio and the fewest/smallest number of parameters (e.g. numjobs=2, nrfiles as small as possible etc)? Perhaps I was wrong about the files used being unique...

**Comment by sitsofe** [comment] 2017-02-06 04:49
(where "the problem" is the verification mismatches)

**Comment by sitsofe** [comment] 2017-02-14 12:27
@ashokkumaralluri any luck with the reproduction mentioned in https://github.com/axboe/fio/issues/303#issuecomment-277538511 ?

**Comment by sitsofe** [comment] 2017-04-08 09:15
@ashokkumaralluri are you still seeing that error message with recent fio versions and smaller parameter values?

**Comment by sitsofe** [comment] 2017-08-31 15:58
@ashokkumaralluri a fix has gone in to git fio (https://github.com/axboe/fio/commit/d30455b5f301b9c8017a0c7439573835d7e177de ) for making the "Multiple writers may overwrite blocks" more specific so it should no longer trigger in your case (where the filenames will be unique). Can you retest with git fio and see if that solves your issue?

**Comment by kobebry80** [comment] 2018-01-13 04:10
@sitsofe 
Fio version: fio-2.0.8
FIO command:
./fio -filename=/dev/sdal -direct=1 -iodepth 128 -rw=write -ioengine=libaio -bs=8k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5  -verify_dump=1 &
./fio -filename=/dev/sdam -direct=1 -iodepth 128 -rw=write -ioengine=libaio -bs=16k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdan -direct=1 -iodepth 128 -rw=write -ioengine=libaio -bs=23k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdao -direct=1 -iodepth 128 -rw=write -ioengine=libaio -bs=25k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdap -direct=1 -iodepth 128 -rw=write -ioengine=libaio -bs=27k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdaq -direct=1 -iodepth 128 -rw=write -ioengine=libaio -bs=29k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdar -direct=1 -iodepth 128 -rw=write -ioengine=libaio -bs=32k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdas -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=31k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdat -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=33k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdau -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=8k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdav -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=9k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdaw -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=17k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdax -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=19k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sday -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=21k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdaz -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=23k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdba -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=25k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdbb -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=27k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdbc -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=28k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdbd -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=29k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdbe -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=31k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &
./fio -filename=/dev/sdbf -direct=1 -iodepth 128 -rw=randwrite -ioengine=libaio -bs=33k -runtime=360000 -time_based -group_reporting -name=xvdn -do_verify=1 -verify=md5 -verify_dump=1 &

**OUTPUT:**
Starting 1 process
verify: bad magic header f734, wanted acca at file /dev/sdbd offset 2172856320, length 210403040
fio: pid=7305, err=84/file:io_u.c:1525, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character

xvdn: (groupid=0, jobs=1): err=84 (file:io_u.c:1525, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character): pid=7305
  read : io=10914MB, bw=28822KB/s, iops=993 , runt=387764msec
    slat (msec): min=1716 , max=359837 , avg=178801.85, stdev=107325.61
    clat (usec): min=1 , max=32410K, avg=128660.05, stdev=681586.63
     lat (msec): min=1723 , max=365254 , avg=178930.51, stdev=107314.78
    clat percentiles (usec):
     |  1.00th=[  390],  5.00th=[  486], 10.00th=[  596], 20.00th=[  876],
     | 30.00th=[ 1208], 40.00th=[ 1608], 50.00th=[ 2096], 60.00th=[ 2800],
     | 70.00th=[ 5344], 80.00th=[27264], 90.00th=[162816], 95.00th=[659456],
     | 99.00th=[2506752], 99.50th=[3555328], 99.90th=[7372800], 99.95th=[13959168],
     | 99.99th=[16711680]
  write: io=20162MB, bw=18895KB/s, iops=651 , runt=1092674msec
    slat (usec): min=4 , max=734 , avg=11.58, stdev= 5.44
    clat (usec): min=412 , max=43620K, avg=196333.66, stdev=830631.23
     lat (usec): min=421 , max=43620K, avg=196345.48, stdev=830631.26
    clat percentiles (usec):
     |  1.00th=[  748],  5.00th=[ 1032], 10.00th=[ 1368], 20.00th=[ 2448],
     | 30.00th=[ 4768], 40.00th=[10688], 50.00th=[22912], 60.00th=[39168],
     | 70.00th=[59648], 80.00th=[95744], 90.00th=[284672], 95.00th=[962560],
     | 99.00th=[3555328], 99.50th=[5013504], 99.90th=[8224768], 99.95th=[10158080],
     | 99.99th=[16711680]
    bw (KB/s)  : min=    6, max=107896, per=100.00%, avg=19910.64, stdev=6768.05
    lat (usec) : 2=0.01%, 100=0.01%, 250=0.03%, 500=1.95%, 750=4.16%
    lat (usec) : 1000=5.16%
    lat (msec) : 2=16.35%, 4=13.58%, 10=10.45%, 20=6.96%, 50=13.36%
    lat (msec) : 100=11.14%, 250=7.03%, 500=2.86%, 750=1.53%, 1000=1.04%
    lat (msec) : 2000=2.27%, >=2000=2.14%
  cpu          : usr=6.71%, sys=1.10%, ctx=906877, majf=0, minf=8407
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.1%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued    : total=r=385386/w=711924/d=0, short=r=0/w=0/d=0

Run status group 0 (all jobs):
   READ: io=10914MB, aggrb=28822KB/s, minb=28822KB/s, maxb=28822KB/s, mint=387764msec, maxt=387764msec
  WRITE: io=20162MB, aggrb=18894KB/s, minb=18894KB/s, maxb=18894KB/s, mint=1092674msec, maxt=1092674msec

Disk stats (read/write):
  sdbd: ios=385384/711924, merge=0/0, ticks=48358508/139017372, in_queue=187389224, util=100.00%
Jobs: 1 (f=1): [V] [0.4% done] [28489K/0K /s] [919 /0  iops] [eta 04d:03h:34m:54s]]  


I am hitting frequent error message "verify: bad magic header f734, wanted acca at file" frequently,that mean data discompare or bad io？

**Comment by axboe** [comment] 2018-01-13 04:49
@kobebry80 Please use a recent version of fio, the one you are using is almost 6  years old... If the issue reproduces in 3.3, then file a new issue for it, don't paste it into an unrelated issue.

**Comment by kobebry80** [comment] 2018-01-13 04:52
@axboe 
thanks a lot!

**Comment by sitsofe** [comment] 2018-04-09 15:11
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2018-04-09 15:12 UTC
