### ISSUE TITLE
Windows build stuck

### ISSUE THREAD

**Issue by jhjacobs** [axboe/fio#757] opened 2019-03-27 20:10 UTC
Cygwin version
$ uname -a
CYGWIN_NT-10.0 WTUSLVSE061162L 3.0.4(0.338/5/3) 2019-03-16 09:50 x86_64 Cygwin

Build listing
 ```
$ make clean && make -j
rm -f .depend gettime.o ioengines.o init.o stat.o log.o time.o filesetup.o eta.o verify.o memory.o io_u.o parse.o mutex.o options.o lib/rbtree.o smalloc.o filehash.o profile.o debug.o lib/rand.o lib/num2str.o lib/ieee754.o crc/crc16.o crc/crc32.o crc/crc32c-intel.o crc/crc32c.o crc/crc64.o crc/crc7.o crc/md5.o crc/sha1.o crc/sha256.o crc/sha512.o crc/test.o crc/xxhash.o engines/cpu.o engines/sync.o engines/null.o engines/net.o memalign.o server.o client.o iolog.o backend.o libfio.o flow.o cconv.o lib/prio_tree.o json.o lib/zipf.o lib/axmap.o lib/lfsr.o gettime-thread.o helpers.o lib/flist_sort.o lib/hweight.o lib/getrusage.o idletime.o td_error.o profiles/tiobench.o profiles/act.o io_u_queue.o filelock.o engines/windowsaio.o lib/strsep.o lib/strcasestr.o lib/getopt_long.o lib/inet_aton.o os/windows/posix.o fio.o gettime.o ioengines.o init.o stat.o log.o time.o filesetup.o eta.o verify.o memory.o io_u.o parse.o mutex.o options.o lib/rbtree.o smalloc.o filehash.o profile.o debug.o lib/rand.o lib/num2str.o lib/ieee754.o crc/crc16.o crc/crc32.o crc/crc32c-intel.o crc/crc32c.o crc/crc64.o crc/crc7.o crc/md5.o crc/sha1.o crc/sha256.o crc/sha512.o crc/test.o crc/xxhash.o engines/cpu.o engines/sync.o engines/null.o engines/net.o memalign.o server.o client.o iolog.o backend.o libfio.o flow.o cconv.o lib/prio_tree.o json.o lib/zipf.o lib/axmap.o lib/lfsr.o gettime-thread.o helpers.o lib/flist_sort.o lib/hweight.o lib/getrusage.o idletime.o td_error.o profiles/tiobench.o profiles/act.o io_u_queue.o filelock.o engines/windowsaio.o lib/strsep.o lib/strcasestr.o lib/getopt_long.o lib/inet_aton.o os/windows/posix.o gfio.o graph.o tickmarks.o ghelpers.o goptions.o gerror.o gclient.o gcompat.o cairo_text_helpers.o printing.o gettime.o ioengines.o init.o stat.o log.o time.o filesetup.o eta.o verify.o memory.o io_u.o parse.o mutex.o options.o lib/rbtree.o smalloc.o filehash.o profile.o debug.o lib/rand.o lib/num2str.o lib/ieee754.o crc/crc16.o crc/crc32.o crc/crc32c-intel.o crc/crc32c.o crc/crc64.o crc/crc7.o crc/md5.o crc/sha1.o crc/sha256.o crc/sha512.o crc/test.o crc/xxhash.o engines/cpu.o engines/sync.o engines/null.o engines/net.o memalign.o server.o client.o iolog.o backend.o libfio.o flow.o cconv.o lib/prio_tree.o json.o lib/zipf.o lib/axmap.o lib/lfsr.o gettime-thread.o helpers.o lib/flist_sort.o lib/hweight.o lib/getrusage.o idletime.o td_error.o profiles/tiobench.o profiles/act.o io_u_queue.o filelock.o engines/windowsaio.o lib/strsep.o lib/strcasestr.o lib/getopt_long.o lib/inet_aton.o os/windows/posix.o t/stest.o gettime.o mutex.o smalloc.o t/log.o t/ieee754.o lib/ieee754.o t/log.o lib/ieee754.o lib/rand.o lib/zipf.o t/genzipf.o t/axmap.o lib/lfsr.o lib/axmap.o t/lfsr-test.o lib/lfsr.o fio t/stest t/ieee754 t/genzipf t/axmap t/lfsr-test core.* core gfio FIO-VERSION-FILE *.d lib/*.d crc/*.d engines/*.d profiles/*.d t/*.d config-host.mak config-host.h
makefile:14: config-host.mak: No such file or directory
FIO_VERSION = fio-2.1.10
Running configure for you...
Forcing known good options on Windows
    CC gettime.o
    CC memory.o
    CC filesetup.o
: No such file or directoryor: gettime.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC time.o
    CC init.o
    CC ioengines.o
    CC lib/rbtree.o
    CC verify.o
    CC options.o
    CC stat.o
: No such file or directoryor: memory.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC eta.o
    CC log.o
    CC lib/ieee754.o
    CC mutex.o
: No such file or directoryor: init.c
: No such file or directoryor: filesetup.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC io_u.o
: No such file or directoryor: lib/rbtree.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: options.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: verify.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: eta.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC crc/crc32.o
    CC debug.o
    CC crc/crc7.o
    CC lib/rand.o
    CC filehash.o
: No such file or directoryor: ioengines.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: mutex.c
: No such file or directoryor: lib/ieee754.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: io_u.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC crc/xxhash.o
    CC crc/crc16.o
: No such file or directoryor: log.c
: No such file or directoryor: time.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC crc/crc64.o
    CC parse.o
    CC crc/sha1.o
    CC crc/sha256.o
: No such file or directoryor: stat.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: crc/crc7.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC engines/cpu.o
: No such file or directoryor: debug.c
: No such file or directoryor: crc/crc32.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: crc/xxhash.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC crc/crc32c.o
: No such file or directoryor: lib/rand.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: filehash.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: crc/crc16.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: crc/sha256.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: engines/cpu.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: parse.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: crc/crc64.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC profile.o
: No such file or directoryor: crc/crc32c.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: crc/sha1.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC smalloc.o
    CC crc/sha512.o
    CC server.o
    CC libfio.o
    CC memalign.o
    CC flow.o
    CC engines/null.o
    CC engines/sync.o
    CC crc/md5.o
    CC lib/zipf.o
    CC lib/strcasestr.o
    CC lib/getrusage.o
    CC filelock.o
    CC json.o
    CC helpers.o
    CC client.o
    CC gettime-thread.o
    CC os/windows/posix.o
    CC td_error.o
    CC lib/axmap.o
    CC fio.o
    CC backend.o
    CC iolog.o
    CC lib/prio_tree.o
    CC engines/net.o
    CC lib/flist_sort.o
    CC crc/crc32c-intel.o
    CC crc/test.o
    CC lib/hweight.o
    CC lib/num2str.o
    CC io_u_queue.o
    CC profiles/act.o
: No such file or directoryor: crc/sha512.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: flow.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: engines/null.c
: No such file or directoryor: memalign.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: smalloc.c
: No such file or directoryor: libfio.c
: No such file or directoryor: server.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC cconv.o
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC idletime.o
: No such file or directoryor: helpers.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC profiles/tiobench.o
: No such file or directoryor: json.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: profile.c
    CC engines/windowsaio.o
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: os/windows/posix.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: gettime-thread.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC lib/lfsr.o
: No such file or directoryor: crc/crc32c-intel.c
: No such file or directoryor: filelock.c
: No such file or directoryor: lib/zipf.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
x86_64-w64-mingw32-gcc: fatal error: no input files
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
compilation terminated.
: No such file or directoryor: profiles/act.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: lib/getrusage.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: fio.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: engines/sync.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: lib/flist_sort.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: iolog.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: backend.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: profiles/tiobench.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: crc/test.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: crc/md5.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: lib/hweight.c
: No such file or directoryor: lib/lfsr.c
: No such file or directoryor: lib/prio_tree.c
: No such file or directoryor: engines/net.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC lib/getopt_long.o
: No such file or directoryor: lib/strcasestr.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: idletime.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: td_error.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: lib/axmap.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: engines/windowsaio.c
: No such file or directoryor: client.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: cconv.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: io_u_queue.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: lib/num2str.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
    CC lib/strsep.o
    CC lib/inet_aton.o
: No such file or directoryor: lib/getopt_long.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
: No such file or directoryor: lib/inet_aton.c
: No such file or directoryor: lib/strsep.c
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
x86_64-w64-mingw32-gcc: fatal error: no input files
compilation terminated.
```

**Comment by sitsofe** [comment] 2019-03-27 22:01
@jhjacobs 
```
FIO_VERSION = fio-2.1.10
                  ^^^
```

I'm afraid we only support the latest version fio (see https://github.com/axboe/fio/releases for which version we're up to) Can you reproduce the problem with the latest fio?

**Comment by sitsofe** [comment] 2019-04-19 09:42
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2019-04-19 09:42 UTC
Labels: needinfo
