### ISSUE TITLE
Position of --debug option affects log output

### ISSUE THREAD

**Issue by milpita** [axboe/fio#786] opened 2019-06-05 18:51 UTC
Parameter position should not affect program behavior. I notice that if debug option comes before clocksource (`--debug=time --clocksource=cpu`), fio prints correctly time debug info:

```
fio: set debug option time
time     7149  cycles[0]=2194966
time     7149  cycles[1]=2194973
time     7149  cycles[2]=2194916
time     7149  cycles[3]=2194957
...
```

If debug comes after (`--clocksource=cpu --debug=time`) it won't print debug info:
```
fio: clocksource=cpu may not be reliable
fio: set debug option time
```

Version and full command for reference:
```
fio-3.14-6-g97134
fio --name=job --directory=/mnt/fio-test --filename=fio-4G \
    --rw=randwrite --blocksize=4k --ioengine=psync --iodepth=1 \
    --direct=0 --time_based --ramp_time=10 --runtime=10 \
    --size=4G --io_size=3200G --norandommap \
    --debug=time --clocksource=cpu --invalidate=0 --numjobs=1 \
    --cpus_allowed=1 --write_iops_log=fio --log_avg_msec=1000 \
    --output=fio.txt
```

**Comment by sitsofe** [comment] 2019-12-16 11:21
I don't necessarily think this is wrong but it could definitely be better documented. As it happens [`--debug` is actually a command line option](https://fio.readthedocs.io/en/latest/fio_doc.html#command-line-options) so it's a bit weird to see it in the middle of a job description (as above - imagine putting `--help` in that position).

**Comment by axboe** [comment] 2019-12-16 18:12
Non-job options should always come first. They are parsed in order, --debug will affect how the rest of the options are parsed. I hate to say it, but that's as designed, not a bug here.

**Comment by sitsofe** [comment] 2019-12-16 18:19
@milpita So based on Jens' comment I'm going to close this issue but if you can come up with some good wording we can add it to the documentation...

**Closed by sitsofe** 2019-12-16 18:19 UTC
