### ISSUE TITLE
Latency in rate limiting iops depends on the I/O depth

### ISSUE THREAD

**Issue by rshterman** [axboe/fio#635] opened 2018-08-02 12:09 UTC
Hi,
I'm running read/write workload with rate_iops of 300K (for both write and read together).
without rate_iops I can get much more than 300K IOPS. I was surprised to find
out that changing I/O depth with the rate limit affect the latency fio present.

I would expect that as long as I'm running with I/O depth that is enough to saturate
the rate limit I would not experience higher latency in case I'm increasing the I/O depth.

in case of rate_iops I saw in code that thread is sleeping till 'next I/O' needs to be
deployed. Why do we need to sleep?

Thanks,

**Comment by sitsofe** [comment] 2018-08-13 04:34
@rshterman If you just busy loop you'll burn CPU (which could have gone to another thread/process) and increase power usage but I suppose the problem is that you can't record the completion until you wake up so it's a tradeoff.

You might get better results by decoupling the completion from the submission path by using [`io_submit_mode=offload`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-io-submit-mode) - can you let us know if that helped?

**Comment by sitsofe** [comment] 2018-09-11 06:06
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2018-09-11 06:06 UTC
Labels: needinfo
