### ISSUE TITLE
FIO load_save_state after halted randwr run with trigger file doesn't work as expected

### ISSUE THREAD

**Issue by ronen-lb** [axboe/fio#468] opened 2017-09-27 08:22 UTC
Hi,

I am seeing an issue verifying partially written random data using verify_state_load.

I am tryign to use FIO to verify data on a storage device after an abrupt stop of transmission.
I am using fio verify+randomwr to generate data, and use the trigger-file option to activily stop the write 
mid way through.
I then use read + verify and verify_state_load=1 to verify only the data that was supposed to have been written up to the trigger command.  data verification fails. It seems to only work as expected
if I dont use random write (however this would somewhat defeat the purpose for me, as being to simple a write pattern).

I have tried playing with load verify_State_save, number of jobs, and passing the save and load directions either from job file or command line, I noticed that the local fio state files where created after trigger,but was not able to get this to work for me correctly with randwr.

I am currently using fio v2.21 running locally and writing to al ocal nvme device (at present I was not able to attempt upgrading to v2.29 or v3.0
to see if these resolve issue).

issue was observed running fio 2.29 on linux machine:
fio --version:
fio-2.21
uname -r:
4.10.0-33-generic

Bellow are snippets of the fio write job (the trigger-file and trigger commands where issued from command line and are not listed below), and the fio read jobs, as well as the errors in checking data.

Many thanks
ronen

write job
[global]
verify_fatal=1
do_verify=0
loops=1
group_reporting=1
filename=/dev/nvme0n1
cpus_allowed=0-7
cpus_allowed_policy=split
runtime=0
verify=crc32c-intel
direct=1
rw=randwrite
verify_offset=100
ioengine=libaio
iodepth=32
size=200mb
bs=4096
verify_backlog=16384.0

[job_0]
size=209715200
offset=0

[job_1]
size=209715200
offset=1744830464

[job_2]
size=209715200
offset=3489660928

[job_3]
size=209715200
offset=5234491392

[job_4]
size=209715200
offset=6979321856

[job_5]
size=209715200
offset=8724152320

[job_6]
size=209715200
offset=10468982784

[job_7]
size=209715200
offset=12213813248

read job
[global]
verify_fatal=1
do_verify=1
loops=1
group_reporting=1
filename=/dev/nvme0n1
cpus_allowed=0-7
verify_state_load=1
cpus_allowed_policy=split
runtime=0
verify=crc32c-intel
direct=1
rw=read
verify_offset=100
ioengine=libaio
iodepth=32
size=1mb
bs=4096
verify_backlog=16384.0

[job_0]
size=1048576
offset=0

[job_1]
size=1048576
offset=1744830464

[job_2]
size=1048576
offset=3489660928

[job_3]
size=1048576
offset=5234491392

[job_4]
size=1048576
offset=6979321856

[job_5]
size=1048576
offset=8724152320

[job_6]
size=1048576
offset=10468982784

[job_7]
size=1048576
offset=1221381324

error msg:
tarting 8 processes job_5: No I/O performed by libaio, perhaps try --debug=io option for details? job_4: No I/O performed by libaio, perhaps try --debug=io option for details? job_7: No I/O performed by libaio, perhaps try --debug=io option for details? job_6: No I/O performed by libaio, perhaps try --debug=io option for details? job_3: No I/O performed by libaio, perhaps try --debug=io option for details? job_2: No I/O performed by libaio, perhaps try --debug=io option for details? verify: bad header offset 466944, wanted 20480 at file /dev/nvme0n1 offset 20480, length 4096 verify: bad header offset 462848, wanted 24576 at file /dev/nvme0n1 offset 24576, length 4096 job_0: No I/O performed by libaio, perhaps try --debug=io option for details? fio: pid=1920, err=84/file:io_u.c:1985, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character

**Comment by sitsofe** [comment] 2017-09-27 16:38
Looks like you're getting mismatches. Any chance you whittle away your job to be as small as possible but yet still reproducing the issue? e.g. reduce the number of jobs, remove as many options from the global section etc?

**Comment by ronen-lb** [comment] 2017-09-27 17:19
sitsofe  thanks for the quick reply, 

I have tried running same scenario with only a single job and saw same behavior (i.e verify based on load state passed only when rw=write and fails with rw=randwrite).

I can definitely try to remove some of the options in my jobs.  though apologize in advance if it might take me a while to generate this info.

thanks
Ronen

**Comment by sitsofe** [comment] 2017-09-27 17:29
Anything that cuts down what to look at helps. I'm wondering why your read jobs have different sizes to your write jobs though? Do things get better when they are the same?

**Comment by ronen-lb** [comment] 2017-09-27 18:02
it was an error on my side in creating the read jobs, I corrected this (used same read size as in the write job) and saw same issue as described above (though aplogize for using the errored info in describing my jobs)

**Comment by sitsofe** [comment] 2017-09-27 20:21
Hmm, `verify_state_load` seems to trigger the "No I/O performed" message:
```
rm -f /tmp/fio.tmp; ./fio --rw=write --filename=/tmp/fio.tmp --size=1M --rate_iops=2 --verify=crc32c --trigger-timeout=2s --name=verifywrite
./fio --rw=read --filename=/tmp/fio.tmp --size=1M --verify=crc32c --verify_state_load=1 --name=verifywrite
```

**Comment by ronen-lb** [comment] 2017-09-28 12:11
sitsofe,

I simplified my fio jobs somewhat, i still seem to see that the trigger+verification wont work correctly when the write is done is random manner (wr=randwrite vs wr=write).

the commands I issue are:
>fio --trigger-file=/tmp/trig /tmp/fio_w_5
small time delay
>touch /tmp/trig
fio tmp/trig /tmp/fio_r_5

Jobs files are below, as well as detailed error print out in read:
write job:
[global]
do_verify=0
iodepth=32
filename=/dev/nvme0n6
rw=randwrite
ioengine=libaio
verify=crc32c-intel
direct=1
verify_offset=100
bs=4096
[job_0]
size=209715200
offset=0

read
[global]
do_verify=1
verify_state_load=1
iodepth=32
filename=/dev/nvme0n6
rw=read
ioengine=libaio
verify=crc32c-intel
direct=1
verify_offset=100
bs=4096

[job_0]
size=209715200
offset=0

read/error notices:
fio /tmp/fio_r_5 
job_0: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=32
fio-2.21
Starting 1 process
verify: bad header offset 12288, wanted 0 at file /dev/nvme0n6 offset 0, length 4096
verify: bad header offset 0, wanted 8192 at file /dev/nvme0n6 offset 8192, length 4096
verify: bad header offset 495616, wanted 16384 at file /dev/nvme0n6 offset 16384, length 4096
verify: bad header offset 491520, wanted 20480 at file /dev/nvme0n6 offset 20480, length 4096
verify: bad header offset 479232, wanted 24576 at file /dev/nvme0n6 offset 24576, length 4096
verify: bad header offset 475136, wanted 28672 at file /dev/nvme0n6 offset 28672, length 4096
verify: bad header offset 471040, wanted 32768 at file /dev/nvme0n6 offset 32768, length 4096
verify: bad header offset 466944, wanted 36864 at file /dev/nvme0n6 offset 36864, length 4096
verify: bad header offset 462848, wanted 40960 at file /dev/nvme0n6 offset 40960, length 4096
verify: bad header offset 458752, wanted 45056 at file /dev/nvme0n6 offset 45056, length 4096
verify: bad header offset 454656, wanted 49152 at file /dev/nvme0n6 offset 49152, length 4096
verify: bad header offset 450560, wanted 53248 at file /dev/nvme0n6 offset 53248, length 4096
verify: bad header offset 446464, wanted 57344 at file /dev/nvme0n6 offset 57344, length 4096
verify: bad header offset 442368, wanted 61440 at file /dev/nvme0n6 offset 61440, length 4096
verify: bad header offset 438272, wanted 65536 at file /dev/nvme0n6 offset 65536, length 4096
verify: bad header offset 434176, wanted 69632 at file /dev/nvme0n6 offset 69632, length 4096
verify: bad header offset 430080, wanted 73728 at file /dev/nvme0n6 offset 73728, length 4096
verify: bad header offset 425984, wanted 77824 at file /dev/nvme0n6 offset 77824, length 4096
verify: bad header offset 421888, wanted 81920 at file /dev/nvme0n6 offset 81920, length 4096
verify: bad header offset 417792, wanted 86016 at file /dev/nvme0n6 offset 86016, length 4096
verify: bad header offset 413696, wanted 90112 at file /dev/nvme0n6 offset 90112, length 4096
verify: bad header offset 409600, wanted 94208 at file /dev/nvme0n6 offset 94208, length 4096
verify: bad header offset 516096, wanted 98304 at file /dev/nvme0n6 offset 98304, length 4096
verify: bad header offset 397312, wanted 102400 at file /dev/nvme0n6 offset 102400, length 4096
verify: bad header offset 389120, wanted 106496 at file /dev/nvme0n6 offset 106496, length 4096
verify: bad header offset 393216, wanted 110592 at file /dev/nvme0n6 offset 110592, length 4096
verify: bad header offset 503808, wanted 114688 at file /dev/nvme0n6 offset 114688, length 4096
verify: bad header offset 520192, wanted 118784 at file /dev/nvme0n6 offset 118784, length 4096
verify: bad header offset 512000, wanted 122880 at file /dev/nvme0n6 offset 122880, length 4096
verify: bad header offset 507904, wanted 126976 at file /dev/nvme0n6 offset 126976, length 4096
fio: pid=2375, err=84/file:io_u.c:1985, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character

job_0: (groupid=0, jobs=1): err=84 (file:io_u.c:1985, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character): pid=2375: Thu Sep 28 12:01:51 2017
   read: IOPS=16.0k, BW=62.5MiB/s (65.5MB/s)(128KiB/2msec)
    slat (usec): min=4, max=44, avg= 6.34, stdev= 7.06
    clat (usec): min=1175, max=1398, avg=1308.88, stdev=55.48
     lat (usec): min=1221, max=1408, avg=1315.56, stdev=52.74
    clat percentiles (usec):
     |  1.00th=[ 1176],  5.00th=[ 1240], 10.00th=[ 1240], 20.00th=[ 1256],
     | 30.00th=[ 1272], 40.00th=[ 1288], 50.00th=[ 1304], 60.00th=[ 1336],
     | 70.00th=[ 1352], 80.00th=[ 1368], 90.00th=[ 1384], 95.00th=[ 1400],
     | 99.00th=[ 1400], 99.50th=[ 1400], 99.90th=[ 1400], 99.95th=[ 1400],
     | 99.99th=[ 1400]
    lat (msec) : 2=100.00%
  cpu          : usr=0.00%, sys=0.00%, ctx=17, majf=0, minf=49
  IO depths    : 1=3.1%, 2=6.2%, 4=12.5%, 8=25.0%, 16=50.0%, 32=3.1%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=66.7%, 8=0.0%, 16=0.0%, 32=33.3%, 64=0.0%, >=64=0.0%
     issued rwt: total=32,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=32

Run status group 0 (all jobs):
   READ: bw=62.5MiB/s (65.5MB/s), 62.5MiB/s-62.5MiB/s (65.5MB/s-65.5MB/s), io=128KiB (131kB), run=2-2msec

Disk stats (read/write):
  nvme0n6: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%

**Comment by axboe** [comment] 2017-09-28 12:31
It works for me, as long as you make sure that the rw=write is paired with rw=read, or if rw=randwrite is paired with rw=randread. It can't work otherwise. To do split verification like this, fio relies on the fact that the IO offsets generated are the same. It uses the state in the verify state file to know when to stop generating offsets. If you use different offset generators, then that won't work at all.

**Comment by ronen-lb** [comment] 2017-09-28 13:00
Thanks axboe , sitsofe,

Can confirm that it works for me too, both the simplified configuration and the more complicated scenario i originally submitted.

in normal operation we often use randwrite and read to verify data, I understand from the above that this only works as all offsets in range were written to.
With randwrite and  partial write (i.e stopped by trigger) the reader generates the same offsets (i.e uses same seed for random?) rather than reading from the load file the offsets that where written to?

**Comment by axboe** [comment] 2017-09-28 13:02
It only works when you verify the whole thing, if the whole range wasn't written, you would have to verify in the right sequence. So I'd say it sort-of works by accident, it's not something you should rely on. Fio has explicit requirements that if you split the read phase into a separate job, it should be identical to the write side in key areas. Those key areas include things like offset generation, buffer sizes, etc.

**Comment by axboe** [comment] 2017-09-28 13:04
The load file only tracks as many IOs as it has to, which is the queue depth of the job. It does not store every IO offset, that would be very inefficient and mean that fio had to load and sotre all of that info to be able to verify. Fio relies on the fact that we'll end up in that sequence of IOs at some point, and stop right at the right time. If you don't generate the same offsets, then that approach obviously fails.

If you run t/fio-verify-state on your state file, you can see exactly what it contains. We could make this more bullet proof by moving to a newer version of the state file, which would include some key settings from the write side. If the read side doesn't match exactly that, we could complain.

**Comment by sitsofe** [comment] 2017-09-28 13:38
@axboe do you get the "No I/O performed by psync" warning when running the commands in https://github.com/axboe/fio/issues/468#issuecomment-332643398 ?

**Comment by axboe** [comment] 2017-09-28 13:47
Yes, the commit that introduced that was buggy. I fixed it up earlier today:

http://git.kernel.dk/cgit/fio/commit/?id=c16035aadd600a3a4c4b241339e3d3099f56c4b2

**Closed** 2017-09-28 15:46 UTC

**Comment by roys-lb** [comment] 2019-11-30 23:05
Hi @axboe if I may ask another question regarding the load phase, assuming I'm running exactly the same offsets and sizes for save phase and load phase, I see that during the load phase if I'm putting high I/O depth I'm getting offsets that are not in the file from save phase. What is the expected behavior regarding I/O depth with save/load verify state?

**Comment by sitsofe** [comment] 2019-12-01 09:48
@roys-lb rather than tagging a question on to a closed issue (even though it may look related) could you ask this over on the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.12/README#L58) (note that the list only accepts plain text emails). Thanks!
