### ISSUE TITLE
No output file generated for write_bw_log or wirte_iops_log!

### ISSUE THREAD

**Issue by cashew250** [axboe/fio#183] opened 2016-05-26 23:07 UTC
No output files are generated to /var/log/SSD/ when running the below config. However, when I kill the fio process I will suddenly see some. Issue is, I ran this overnight, it completed and no files were generated. Not sure what is going on, when is the output being dumped by each process? Fio 2.1.10, Debian version is Wheezy, I tried a 2.11 build of Fio but no luck.

[global]
ioengine=libaio
direct=1
buffered=0
log_avg_msec=1000
group_reporting
filename=/dev/sdb

[sequential-write-precondition]
stonewall
description=Sequential write precondition
rw=write
iodepth=16
bs=1M
size=100%
# log_avg_msec=60000

write_bw_log=/var/log/SSD/ssd_seqwrt_precon_bandwidth
write_iops_log=/var/log/SSD/ssd_seqwrt_precon_iop
loops=2

[random-write-precondition]
stonewall
description=Random write precondition phase
rw=randwrite
bs=4K
iodepth=4
numjobs=4
size=100%
refill_buffers
# log_avg_msec=60000

write_bw_log=/var/log/SSD/ssd_rndwrt_precon_bandwidth
write_iops_log=/var/log/SSD/ssd_rndwrt_precon_iop
norandommap

[random-write-steady]
stonewall
description=Random write steady state phase
rw=randwrite
bs=4K
iodepth=4
numjobs=4
time_based
runtime=18000
size=100%
refill_buffers
norandommap
# log_avg_msec=60000

write_bw_log=/var/log/SSD/ssd_rndwrt_results_bandwidth
write_iops_log=/var/log/SSD/ssd_rndwrt_results_iop

**Comment by xjtuwjp** [comment] 2016-06-08 11:04
We have a similar bug with latest fio master branch (6a89b4012)
iops file was not generated.
bw file was generated but a lot zeros after first sample, eg
2498, 615636, 1, 0
5497, 0, 1, 0
8495, 0, 1, 0
11494, 0, 1, 0
14492, 0, 1, 0

**Comment by axboe** [comment] 2016-06-09 03:45
xjtuwjp, what job file did you run? I can take a look at this, most easily with a job file or similar that reproduces the issue.

**Comment by xjtuwjp** [comment] 2016-06-15 14:19
@axboe, sorry missed you comments, I just retried with fio-2.12, same result.
I guess it's related to timing, I can reproduce the behavior with our 64 cores big machine, but not 4 cores desktop. Also what I can tell is: fio-2.2.9-41-gae156 works better than master branch (6a89b40)

With  fio-2.2.9-41-gae156, I get some times empty file for 64k/128k bw or iops log.

configration:
[global]
ioengine=libaio
direct=1
sync=0
time_based=1
loops=1
disk_util=0

# pinning options
cpus_allowed=2-63
cpus_allowed_policy=split
numa_mem_policy=local

# runtime options
runtime=15
ramp_time=1
log_avg_msec=2000

# mode options
iodepth=128
rw=read
filename=/dev/ram0

[128_iodepth_seq_read_pinned_blocksize_4k]
blocksize=4k
stonewall
write_bw_log=128_iodepth_seq_read_pinned_blocksize_4k
write_iops_log=128_iodepth_seq_read_pinned_blocksize_4k
write_lat_log=128_iodepth_seq_read_pinned_blocksize_4k

[128_iodepth_seq_read_pinned_blocksize_32k]
blocksize=32k
stonewall
write_bw_log=128_iodepth_seq_read_pinned_blocksize_32k
write_iops_log=128_iodepth_seq_read_pinned_blocksize_32k
write_lat_log=128_iodepth_seq_read_pinned_blocksize_32k

[128_iodepth_seq_read_pinned_blocksize_128k]
blocksize=128k
stonewall
write_bw_log=128_iodepth_seq_read_pinned_blocksize_128k
write_iops_log=128_iodepth_seq_read_pinned_blocksize_128k
write_lat_log=128_iodepth_seq_read_pinned_blocksize_128k

output for log files:
 head *.log
==> 128_iodepth_seq_read_pinned_blocksize_128k_bw.3.log <==
2498, 1234281, 0, 0
5497, 0, 0, 0
8495, 0, 0, 0
11494, 0, 0, 0
14492, 0, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_128k_clat.3.log <==
2000, 6502, 0, 0
4000, 6507, 0, 0
6000, 6503, 0, 0
8000, 6505, 0, 0
10000, 6505, 0, 0
12000, 6521, 0, 0
14000, 6541, 0, 0
15000, 6507, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_128k_iops.3.log <==
2498, 9643, 0, 0
5497, 0, 0, 0
8495, 0, 0, 0
11494, 0, 0, 0
14492, 0, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_128k_lat.3.log <==
2000, 6551, 0, 0
4000, 6556, 0, 0
6000, 6552, 0, 0
8000, 6554, 0, 0
10000, 6554, 0, 0
12000, 6570, 0, 0
14000, 6591, 0, 0
15000, 6556, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_128k_slat.3.log <==
2000, 48, 0, 0
4000, 48, 0, 0
6000, 48, 0, 0
8000, 48, 0, 0
10000, 48, 0, 0
12000, 48, 0, 0
14000, 48, 0, 0
15000, 48, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_32k_bw.2.log <==
2998, 1170089, 0, 0
5997, 0, 0, 0
8995, 0, 0, 0
11994, 0, 0, 0
14992, 0, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_32k_clat.2.log <==
2000, 1737, 0, 0
4000, 1736, 0, 0
6000, 1734, 0, 0
8000, 1735, 0, 0
10000, 1735, 0, 0
12000, 1734, 0, 0
14000, 1734, 0, 0
15000, 1733, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_32k_iops.2.log <==
2998, 36565, 0, 0
5997, 0, 0, 0
8995, 0, 0, 0
11994, 0, 0, 0
14992, 0, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_32k_lat.2.log <==
2000, 1748, 0, 0
4000, 1747, 0, 0
6000, 1745, 0, 0
8000, 1746, 0, 0
10000, 1745, 0, 0
12000, 1745, 0, 0
14000, 1745, 0, 0
15000, 1744, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_32k_slat.2.log <==
2000, 10, 0, 0
4000, 10, 0, 0
6000, 10, 0, 0
8000, 10, 0, 0
10000, 10, 0, 0
12000, 10, 0, 0
14000, 10, 0, 0
15000, 10, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_4k_bw.1.log <==
2248, 319304, 0, 0
5247, 0, 0, 0
8245, 0, 0, 0
11244, 0, 0, 0
14242, 0, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_4k_clat.1.log <==
2000, 796, 0, 0
4000, 799, 0, 0
6000, 800, 0, 0
8000, 799, 0, 0
10000, 798, 0, 0
12000, 798, 0, 0
14000, 798, 0, 0
15000, 798, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_4k_iops.1.log <==
2248, 79826, 0, 0
5247, 0, 0, 0
8245, 0, 0, 0
11244, 0, 0, 0
14242, 0, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_4k_lat.1.log <==
2000, 800, 0, 0
4000, 802, 0, 0
6000, 803, 0, 0
8000, 802, 0, 0
10000, 801, 0, 0
12000, 801, 0, 0
14000, 801, 0, 0
15000, 802, 0, 0

==> 128_iodepth_seq_read_pinned_blocksize_4k_slat.1.log <==
2000, 3, 0, 0
4000, 3, 0, 0
6000, 3, 0, 0
8000, 3, 0, 0
10000, 3, 0, 0
12000, 3, 0, 0
14000, 3, 0, 0
15000, 3, 0, 0

**Comment by axboe** [comment] 2016-06-16 07:07
I'll look into this when I'm back. If you haven't heard anything in 2 weeks time, send me a reminder!

**Comment by xjtuwjp** [comment] 2016-06-29 08:46
@axboe  Around 2 weeks now, do you have any update on this bug?

**Comment by sitsofe** [comment] 2016-11-28 16:47
@xjtuwjp was this fixed by the commit https://github.com/axboe/fio/pull/216/commits/be6bb2b72608d7efbec13d06c67446e229136afa ?

**Comment by sitsofe** [comment] 2017-04-16 15:41
@xjtuwjp Can you still reproduce this issue with fio 2.19 or later? If not could you close this issue?

**Comment by sitsofe** [comment] 2017-08-31 16:11
@xjtuwjp Can you close this issue if it is no longer reproducible?

**Comment by xjtuwjp** [comment] 2017-10-09 14:29
I retested on fio-3.0, seems the bug is fixed, thanks, sorry for long delay.

**Comment by sitsofe** [comment] 2017-10-09 16:09
@cashew250 - if this issue is no longer reproducible could you close it please? Thanks.

**Comment by sitsofe** [comment] 2018-04-09 15:45
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2018-04-09 15:45 UTC
