### ISSUE TITLE
small size run pass ,but big size run fail

### ISSUE THREAD

**Issue by guoweifeng216** [axboe/fio#1246] opened 2021-07-12 12:06 UTC
**Please acknowledge the following before creating a ticket**

- [ ] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
<run small size pass
small_size.fio
[global]
filename=H:
**size=100g**
thread
ioengine=windowsaio
runtime=3600
continue_on_error=none
exitall_on_error
bs_unaligned
random_generator=tausworthe64
rw=randwrite

[random write 1njobs]
stonewall
direct=0
bssplit=512/10:1k/10:1.5k/10:3k/10:9k/10:127k/10:128k/10:512k/10:1m/10:2m/10
iodepth=32
numjobs=1

run big size fail
big_size.fio
[global]
filename=H:
**size=800g**
thread
ioengine=windowsaio
runtime=3600
continue_on_error=none
exitall_on_error
bs_unaligned
random_generator=tausworthe64
rw=randwrite

[random write 1njobs]
stonewall
direct=0
bssplit=512/10:1k/10:1.5k/10:3k/10:9k/10:127k/10:128k/10:512k/10:1m/10:2m/10
iodepth=32
numjobs=1

>

**Environment**: win10 pro

**fio version**: fio3.27

**Reproduction steps**
1、run fio small_size.fio pass 
2、run big_size.fio fail
>

**Comment by sitsofe** [comment] 2021-07-12 13:41
@guoweifeng216 This looks to be a varient of #1245 and could simply be because on the second run you ran out of space (but no one can tell because you didn't include fio's output).

What you are currently filing is not a bug - it is a help request in a bug clothing! Quoting from https://github.com/axboe/fio/blob/master/REPORTING-BUGS :

> If you are asking a question on how to do something ("How do I/Why is?") please send it to the **mailing list** [emphasis added] and not GitHub issues.

I am going to close this "issue" and request that you **don't** create GitHub issues for **fio questions**. I strongly recommend you read the fio documentation for how the [filename](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename) option works and then once _you have modified_ your job file you should post future queries to the **[fio mailing list](https://github.com/axboe/fio/blob/fio-3.12/README#L58)**.

Thanks.

**Closed by sitsofe** 2021-07-12 13:41 UTC
