### ISSUE TITLE
fio 3.4 reports as version 3.3

### ISSUE THREAD

**Issue by dirtyharrycallahan** [axboe/fio#535] opened 2018-02-19 15:56 UTC
Appears version did not get updated with 3.4 release.

**Comment by sitsofe** [comment] 2018-02-20 18:35
Looks like https://github.com/axboe/fio/blob/488468793d72297f7dccd42a7b50011e74de0688/FIO-VERSION-GEN#L4 needs to be updated. Looks like some packagers have already picked it up too - https://repology.org/metapackage/fio/versions ...

**Comment by axboe** [comment] 2018-02-20 22:31
Gah, and I'm on vacation this week. That was pretty stupid. I've tagged 3.5 properly now instead.

**Comment by sitsofe** [comment] 2018-02-21 10:57
@dirtyharrycallahan - this one should be solved with fio-3.5. Can you close this issue if the problem is fixed? Thanks!

**Closed** 2018-02-22 20:58 UTC
