### ISSUE TITLE
Incorrect Units information in FIO man page 

### ISSUE THREAD

**Issue by Naveenaz** [axboe/fio#103] opened 2015-07-31 10:51 UTC
Base 10 Vs Base 2 Units:

Info 1:

base-2 units:
1 KiB = 1,024 bytes (Note: big k)
1 MiB = 1,024 KiB = 1,048,576 bytes
1 GiB = 1,024 MiB = 1,048,576 KiB = 1,073,741,824 bytes
1 TiB = 1,024 GiB = 1,048,576 MiB = 1,073,741,824 KiB = 1,099,511,627,776 bytes

base-10 units:
1 kB = 1,000 bytes (Note: small k)
1 MB = 1,000 kB = 1,000,000 bytes
1 GB = 1,000 MB = 1,000,000 kB = 1,000,000,000 bytes
1 TB = 1,000 GB = 1,000,000 MB = 1,000,000,000 kB = 1,000,000,000,000 bytes

Source:
https://wiki.ubuntu.com/UnitsPolicy
http://physics.nist.gov/cuu/Units/binary.html

Info 2:

Now check the FIO man page.

---

```
   int    SI integer: a whole number, possibly containing a suffix denoting the base unit of the value.  Accepted suffixes are `k', 'M', 'G', 'T', and  'P',  denoting kilo (1024), mega (1024^2), giga (1024^3), tera (1024^4), and peta (1024^5) respectively. If prefixed with '0x', the value is assumed to be base 16 (hexadecimal). A suffix may include a trailing 'b', for instance 'kb' is identical to 'k'. You can  spec‐ify  a  base  10  value by using 'KiB', 'MiB','GiB', etc. This is useful for disk drives where values are often given in base 10 values.
          Specifying '30GiB' will get you 30*1000^3 bytes.  When specifying times the default suffix meaning changes, still denoting the base unit of  the  value,  but  accepted  suffixes are 'D' (days), 'H' (hours), 'M' (minutes), 'S' Seconds, 'ms' (or msec) milli seconds, 'us' (or  'usec') micro seconds. Time values without a unit specify seconds.  The suffixes are not case sensitive.
```

---

Also, if you look at http://www.snia.org/sites/default/files/SNIASSSI.SSDPerformance-APrimer2013.pdf 

On 7th page at the bottom it says:
One KiB = 1024 bytes. One KB = 1000 bytes. SSD Industry convention uses base 2 (e.g. KiB, MiB, GiB) to describe storage capacities (e.g. 4 KiB block size) and base 10 (e.g. KB, MB, GB) to describe transfer rates (e.g. total GB written or MB/sec)

Observation: By looking at both Info 1 and Info 2, I think FIO man page got it wrong.   FIO man page used wrong acronyms for Units. Because of this, we see incorrect Units in FIO results.  

e.g:
fio-2.2.8
Starting 1 process

 (groupid=0, jobs=1): err= 0: pid=7098: Fri Jul 17 13:19:56 2015
  write: io=6706.9GB, bw=1909.5MB/s, iops=15275, runt=3596754msec  
                                                              (Note here its actually      1909.5MiB/s)
    slat (usec): min=4, max=12165, avg=20.36, stdev= 7.95
    clat (usec): min=1783, max=42547, avg=8357.93, stdev=677.28
     lat (usec): min=1800, max=42562, avg=8378.50, stdev=677.24
    clat percentiles (usec):
     |  1.00th=[ 6560],  5.00th=[ 7776], 10.00th=[ 7840], 20.00th=[ 7968],
………
………

**Comment by DaveGlen** [comment] 2015-07-31 15:51
SSD and HDD industry both use base 10 to describe storage capacity. The convention for NAND capacity is base 2.

FIO's convention is for KB=1024 MB=1048576, etc, and KiB=1000 MiB=1000000 etc.  changing this for throughput reporting could cause confusion because MiB would be a power of 2 for throughput but a power of 10 for everything else.

Also, there are many users who have config files a wrapper scripts based on the current implementation of base 2 and base 10, so changing it generally would cause a lot of turmoil for users.

Not really up to me, but I wouldn't suggest making any changes.

**Comment by Naveenaz** [comment] 2015-08-01 08:27
Thanks for comment. IMO it's not about convention of FIO, it's about 'what is right (correct) thing'.  
Least I would expect some one adds clarity in the man page explaining about their "convention" and why they decided to go on that path.

**Comment by RobPNeff** [comment] 2015-08-13 18:50
Marketing departments do use MB (base-10), but the actual drive capacity in the OS is base-2, and the tool should default to base-2.

Since a different person did the documentation than the author of the tool there's some question as to whether the man page is wrong with respect to the tool or if the man page is correctly describing incorrect behavior by the tool.

**Comment by guenthert** [comment] 2016-02-10 23:32
KB, MB, GB have indeed been used in various ways as described above, but KiB, MiB, GiB are standardized in IEEE 1541.  Redefining it here is more than just asking for trouble.  If a tool makes the effort to distinguish between the base 10 and the base 2 units, then it ought to use the standardized ones.

**Comment by bmr-cymru** [comment] 2016-10-31 16:02
The problem is correctly described in the first comment - the `fio` documentation (as well as the implementation in `parse.c::__get_mult_bytes()`) are incorrectly using "KiB", "MiB", "GiB" etc. as the base 10 prefixes, when those are actually the SI binary prefix prefixes. Similarly `fio` treats `k`, `m`, `g`, etc. as base 2 prefixes - the exact opposite of what the rest of the (standard conforming) world expects.

Perhaps fixing this now is hopeless as `fio` has behaved this way for a long time - it would break a lot of people's job files to suddenly flip the multipliers around.

**Comment by bmr-cymru** [comment] 2016-10-31 16:07
> Least I would expect some one adds clarity in the man page explaining about their "convention" and why 
> they decided to go on that path. 

Right - it would be helpful if the documentation acknowledged the historical mistake, and clearly explained that even though everything "looks backwards", that is just how `fio` works.

**Comment by simo5** [comment] 2016-10-31 16:09
Or maybe add nitially a --ieee-correct option that use the standard correctly, and eventually transition the default to be based on intenrational standard by later on introducing --legacy-unit-value or somethign for the die-hard scripts that would fail by using correct units.

**Comment by bmr-cymru** [comment] 2016-10-31 16:10
Ack - that would also work - something like how `POSIXLY_CORRECT` works for some Gnu tools.

**Comment by sitsofe** [comment] 2017-01-08 09:17
I think this might be addressed by the commits leading up to https://github.com/axboe/fio/commit/6d500c2e886635861f68cac61039da1f397a7685 (Documentation for IEC binary and SI decimal prefix handling)...

**Comment by bmr-cymru** [comment] 2017-01-09 11:34
:+1:

Yes, I think so - I'll try to take a detailed look through some time, but I think this can be closed.

**Comment by sitsofe** [comment] 2017-09-08 04:31
@Naveenaz can you close this as the man page and HOWTO correctly describe fio's quirky behaviour (e.g. see http://fio.readthedocs.io/en/latest/fio_doc.html#int )?

**Comment by sitsofe** [comment] 2018-04-09 15:25
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2018-04-09 15:25 UTC

**Comment by bmr-cymru** [comment] 2018-04-09 15:36
Yes, sorry - the current IEC/SI notation handling is fine, thanks!

**Comment by Naveenaz** [comment] 2018-04-10 10:33
Sorry for being late. Yes, not it makes lot of sense.  Thanks !
