### ISSUE TITLE
Is there any param to specify time unit in result?

### ISSUE THREAD

**Issue by jiang4357291** [axboe/fio#1105] opened 2020-10-22 06:20 UTC
There is both usec and msec in fio result, it's inconvenient when parse result, is there and param to specify time unit,
so that ther is only one time unit in result

**Comment by sitsofe** [comment] 2020-10-22 06:52
@jiang4357291 

> Is there any param to specify time unit in result

Not for the human readable output...

> it's inconvenient when parse result

It definitely is if we're talking about the human readable output (see https://www.youtube.com/watch?v=vm1GJMp0QN4#t=17m48s for cautionary tale). I also need to warn you that the human readable output has changed in ways that have broken adhoc parsers in the past as new features have been added...

However maybe you can take a different approach... I would strongly suggest using one of the other formats (see http://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-output-format for a list of the formats) if your parsing the output as machines find them much easier to consume (given their regularity) AND the units are fixed :-) They are also easier for the fio project to extend in backwards compatible ways...

(This is likely a duplicate of #451)

**Closed** 2020-10-24 08:12 UTC
