### ISSUE TITLE
Average IOPS

### ISSUE THREAD

**Issue by Thanehood** [axboe/fio#281] opened 2016-12-23 21:08 UTC
I am trying to get instantaneous IOPS, I am using the --status-interval=1 and --minimal then I read the output at index 7 for read iops, and index 48 for write iops.  This works fine, but it appears to give me a running average not the actual last second average. Am I correct in my assumption? If so is there a way to get the IOPS for just the last interval?

**Comment by sitsofe** [comment] 2016-12-29 15:15
This sounds like a duplicate of issue #130 ...

**Comment by sitsofe** [comment] 2018-04-09 15:16
Closing as a duplicate of issue #130 . If this is in error please reopen this issue, thanks!

**Closed by sitsofe** 2018-04-09 15:16 UTC
Labels: duplicate
