### ISSUE TITLE
FIO segfaults with while using flow control

### ISSUE THREAD

**Issue by shivapahwa** [axboe/fio#251] opened 2016-09-29 07:34 UTC
I am trying to run the below test. My intention is to be able to direct 80% of the IOs to t2 and 20% IOs to t1.

Version: Fio 2.13
OS: CentOS

The IOs dont go to the device. FIO crashes while exit. 
fio --name=global --filename=/dev/nvme0n1 --rw=randrw --ioengine=sync --bs=16k --rwmixread=100 --percentage_random=100 --rate_process=poisson --runtime=900 --time_based=1 --norandommap=1 --name=t1 --iodepth=32 --numjobs=16 --rwmixread=100 --size=20% --flow=2 --name=t2 --iodepth=32 --rwmixread=100 --size=100% --flow=8

If i change the flow of my t1 to -2, The IOs go through but FIO crashes during cleanup.
fio --name=global --filename=/dev/nvme0n1 --rw=randrw --ioengine=sync --bs=16k --rwmixread=100 --percentage_random=100 --rate_process=poisson --runtime=900 --time_based=1 --norandommap=1 --name=t1 --iodepth=32 --numjobs=16 --rwmixread=100 --size=20% **--flow=-2** --name=t2 --iodepth=32 --rwmixread=100 --size=100% --flow=8

I want to be able to understand how the flow control works. 

Thanks,
Shiva Pahwa

**Comment by shivapahwa** [comment] 2016-09-29 07:37
Just realized that the crash was because i specified --rate_process=poisson. But still curious about how to use the flow control effectively.

**Comment by sitsofe** [comment] 2018-01-08 07:16
@shivapahwa can you still reproduce this issue with a recent fio? If not could you close this? Thanks!

**Comment by sitsofe** [comment] 2018-05-27 06:42
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2018-05-27 06:42 UTC
