### ISSUE TITLE
IOPS shows as 1 and fio2gnuplot shows also a single green bar (axis=1)

### ISSUE THREAD

**Issue by vogelfreiheit** [axboe/fio#742] opened 2019-02-21 20:03 UTC
Hi,

Using fio 3.8.0 from UBuntu 18.10, this is the job file I am using to generate several log files for plotting later:

```
[global]
ioengine=libaio
iodepth=1
size=1g
direct=1
runtime=60
directory=/mnt/testssd/
filename=fio-testfile.tmp
norandommap=1
group_reporting=1
time_based
per_job_logs=0

[Seq-Read]
bs=1m
rw=read
write_bw_log=Seq-Read
write_iops_log=Seq-Read
write_lat_log=Seq-Read
stonewall

[Seq-Write]
bs=1m
rw=write
write_bw_log=Seq-Write
write_iops_log=Seq-Write
write_lat_log=Seq-Write
stonewall

[Rand-Read-512K]
bs=512k
rw=randread
write_bw_log=Rand-Read-512K
write_iops_log=Rand-Read-512K
write_lat_log=Rand-Read-512K
stonewall

[Rand-Write-512K]
bs=512k
rw=randwrite
write_bw_log=Rand-Write-512K
write_iops_log=Rand-Write-512K
write_lat_log=Rand-Write-512K
stonewall

[Rand-Read-4K]
bs=4k
rw=randread
write_bw_log=Rand-Read-4K
write_iops_log=Rand-Read-4K
write_lat_log=Rand-Read-4K
stonewall

[Rand-Write-4K]
bs=4k
rw=randwrite
write_bw_log=Rand-Write-4K
write_iops_log=Rand-Write-4K
write_lat_log=Rand-Write-4K
stonewall

[Rand-Read-4K-QD32]
iodepth=32
bs=4k
rw=randread
write_bw_log=Rand-Read-4K-QD32
write_iops_log=Rand-Read-4K-QD32
write_lat_log=Rand-Read-4K-QD32
stonewall

[Rand-Write-4K-QD32]
iodepth=32
bs=4k
rw=randwrite
write_bw_log=Rand-Write-4K-QD32
write_iops_log=Rand-Write-4K-QD32
write_lat_log=Rand-Write-4K-QD32
stonewall

[Rand-ReadWriteMix-80_20-4K]
bs=4k
rw=randrw
rwmixread=80
write_bw_log=Rand-ReadWriteMix-80_20-4K
write_iops_log=Rand-ReadWriteMix-80_20-4K
write_lat_log=Rand-ReadWriteMix-80_20-4K
stonewall

[Rand-ReadWriteMix-50_50-4K]
bs=4k
rw=randrw
rwmixread=50
write_bw_log=Rand-ReadWriteMix-50_50-4K
write_iops_log=Rand-ReadWriteMix-50_50-4K
write_lat_log=Rand-ReadWriteMix-50_50-4K
stonewall

[Rand-ReadWriteMix-20_80-4K]
bs=4k
rw=randrw
rwmixread=20
write_bw_log=Rand-ReadWriteMix-20_80-4K
write_iops_log=Rand-ReadWriteMix-20_80-4K
write_lat_log=Rand-ReadWriteMix-20_80-4K
stonewall

```

The generated log files for IOPS are stuck at one, not sure what else is going on or if I need to use the averaging for that. When plotted, this obviously results in a rather useless plot displaying a single axis with a value of 1 and nothing else (solid green line in the middle).

Is this an operator mistake or a known bug? How can I modify the job file to accurately product log files for IOPS plots?

**Comment by sitsofe** [comment] 2019-02-22 04:23
@vogelfreiheit Hi there, you're going to need to minimize your job file to try and make this issue more tractable. Can you:

- Make remove as many jobs from this file as possible such that the problem continues to manifest itself?
- After doing so reduce the number of options that job uses to the minimum that still make the problem happen?

**Comment by sitsofe** [comment] 2019-03-24 07:37
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2019-03-24 07:37 UTC
Labels: needinfo

**Comment by FlorianHeigl** [comment] 2020-04-19 18:48
It seems to still exist, I have done a lot of tests and always end up with this issue.
It would be nice if someone could confirm they _don't_ got this issue.

I tried from source, and also ubuntu 20.04's

`ii  fio                                  3.16-1                            amd64        flexible I/O tester`

no matter what i do, the IOPS graphs are not OK.

The data in the iops logfile also has the "1" for the iops field:

randrw_iops.1.log:

```
14226, 1, 1, 4096
14226, 1, 1, 4096
14226, 1, 0, 4096
```
 

This, by now, is a pretty minimalistic config file that still gives me that problem:

```
[global]
#ioengine=libaio
size=512m
iodepth=64
filename=blah


[randrw]
bs=4k
rw=randrw
write_bw_log=randrw
write_iops_log=randrw
write_lat_log=randrw
```

If I think it over, I would say the problem is something "we do wrong with regard to _write_iops_log", but it's something very un-obvious.

**Comment by FlorianHeigl** [comment] 2020-04-19 18:54
PSA:
the problem is that log_avg_msec is not set by default. if you want a job to generate valid IOPS log files, you need(!) to set this.

What do you people think, it would seem more useful if setting write_iops_log would alert to that or pull in a default.

**Comment by sitsofe** [comment] 2020-04-26 05:37
@FlorianHeigl Unfortunately flipping the default would likely do more harm than good at this point.

What might help is a warning for people using fio2gnuplot if it looks like it is working on a file that didn't have `log_avg_msec` set (all lines are for a single iop is a strong hint). As they say, patches welcome...
