### ISSUE TITLE
Cannot run on unformatted drive (raw partition) on Windows 

### ISSUE THREAD

**Issue by Prabhu088** [axboe/fio#931] opened 2020-02-22 16:25 UTC
I am trying fio-3.18 to do some benchmarking on a unformatted hard drive on Windows but the test is failing.

`fio --version`
`fio-3.18
`

The command I used:
`fio --ioengine=windowsaio --name=fio_4k_j8_qd8_randw --bs=4k --runtime=1h --iodepth=8 --rw=randrw --numjobs=1 --size=1G --filename=\\.\PhysicalDrive1 --time_based --debug=io`

Output:
```
fio: set debug option io
fio: this platform does not support process shared mutexes, forcing use of threads. Use the 'thread' option to get rid of this warning.
fio_4k_j8_qd8_randw: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=windowsaio, iodepth=8
fio-3.18
Starting 1 thread
CreateDirectoryA = 123
fio: failed to create dir (\\.): 2


Run status group 0 (all jobs):
io       13740 ioengine cpuio unregistered
io       13740 ioengine mmap unregistered
io       13740 ioengine sync unregistered
io       13740 ioengine psync unregistered
io       13740 ioengine vsync unregistered
io       13740 ioengine null unregistered
io       13740 ioengine net unregistered
io       13740 ioengine ftruncate unregistered
io       13740 ioengine filecreate unregistered
io       13740 ioengine filestat unregistered
io       13740 ioengine windowsaio unregistered
```

**Comment by Prabhu088** [comment] 2020-02-22 16:31
I have tried with "--filename=\.\PhysicalDrive1" and it is started to run fio.

**Comment by sitsofe** [comment] 2020-03-01 12:47
Duplicate of #916 ...

**Closed by sitsofe** 2020-03-01 12:47 UTC
