### ISSUE TITLE
The --rate option cannot support values above 4G

### ISSUE THREAD

**Issue by sbates130272** [axboe/fio#976] opened 2020-05-07 18:43 UTC
While root-causing #975 we determined that the --rate option cannot handle values over 4G. In high performant systems (like those containing several NVMe SSDs) this is not that big of a value. Consider moving --rate to FIO_OPT_ULL to increase the values it can support.

**Comment by sitsofe** [comment] 2020-05-08 13:29
Closing as a duplicate of #716 (I think all the rate options will suffer this flaw)...

(@sbates130272 any chance you could cook up a patch for this one?)

**Closed by sitsofe** 2020-05-08 13:29 UTC

**Comment by sbates130272** [comment] 2020-05-08 13:52
Thanks @sitsofe! I concur this is a duplicate of #716 and I will look at a patch for that.
