### ISSUE TITLE
Terse output units

### ISSUE THREAD

**Issue by thaotran9** [axboe/fio#1152] opened 2020-12-22 18:41 UTC
I don't see terse output units is mentioned in the doc. What is the units for the terse format v3?

**Comment by sitsofe** [comment] 2020-12-22 20:09
Hi there @thaotran9 . As this isn't so much an issue in fio and more of a "How do I/Why is?" question it is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.23/README#L58) (note that the list only accepts plain text emails). As this doesn't seem to match a template I'll close this here.

**Closed by sitsofe** 2020-12-22 20:09 UTC

**Comment by sitsofe** [comment] 2020-12-23 07:04
Actually looking closer this looks like a duplicate of #1094 so I'd recommend subscribing to that issue.

**Comment by sitsofe** [comment] 2020-12-23 07:05
Duplicate of #1094 (test for github duplicate workflow).
