### ISSUE TITLE
#Issue Got a strange output after run any job "0, 0, 0, 0,"

### ISSUE THREAD

**Issue by letonphat1988** [axboe/fio#152] opened 2016-03-04 18:29 UTC
Hi all,
I've just had a big problem when fio export the output to *_bw/iops/lat/slat/clat.log. I've only received some records in few hundreds seconds, the others are "0, 0, 0, 0,".
this's my example:
........
89103, 3357, 0, 0
89103, 5533, 1, 0
91024, 487, 0, 0
91024, 1502, 1, 0
92109, 3724, 0, 0
92109, 3276, 1, 0
93127, 2762, 0, 0
93127, 5292, 1, 0
94130, 3535, 0, 0
94130, 4941, 1, 0
95188, 1578, 0, 0
95188, 3446, 1, 0
96350, 3751, 0, 0
96350, 2519, 1, 0
97548, 3835, 0, 0
97548, 6861, 1, 0
99047, 2271, 0, 0
99047, 3522, 1, 0
100617, 757, 0, 0
100617, 3137, 1, 0
101733, 1611, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
0, 0, 0, 0
.....
this's my fio config
[global]
ioengine=rbd
pool=SAS_POOL
rbdname=VOL01
clientname=admin
invalidate=0
per_job_logs=1
iodepth=128
numjobs=1
thread
runtime=600s
log_avg_msec=1000
disable_clat=1
disable_slat=1

[random-rw-4k]
stonewall
rw=randrw
rwmixread=40
percentage_random=100
bs=4k
group_reporting
write_bw_log=4k
write_lat_log=4k
write_iops_log=4k

Can anyone give me some advice on this case?

**Comment by letonphat1988** [comment] 2016-03-06 13:05
Hi all,
I fixed workaround this problem by increase log_avg_msec from 1000 to10000. The reason is my jobs'are very heavy with high num_jobs, high runtime, high iodepth... we must increase the interval time sothe the fio processes have enough time to collect data from all jobs. unless just get null data.

**Comment by sitsofe** [comment] 2016-07-27 06:36
@letonphat1988 - is this any better with the latest version (at the time of writing 2.13) version of fio?

**Comment by sitsofe** [comment] 2017-08-31 16:10
@letonphat1988 are you still able to reproduce this issue with a git fio?

**Comment by sitsofe** [comment] 2018-04-09 15:13
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2018-04-09 15:13 UTC
