### ISSUE TITLE
0 iops not shown in the final result

### ISSUE THREAD

**Issue by jshen28** [axboe/fio#1145] opened 2020-12-11 00:54 UTC
I am using fio version fio-3.1. while I using libaio engine to test rbd backed virtual block devices, I occasionally saw current IOPS is 0. But after tests completes, in the final text report, the min IOPS is always something greater than 0, is it possible for me to allow 0 in the final result? Thansk.

**Comment by sitsofe** [comment] 2020-12-11 18:27
Hi @jshen28,

As we (upstream) only support the latest fio (see https://github.com/axboe/fio/releases for which version we're up to) can you reproduce your issue with the latest fio? You may also want to turn on IOPS logging (https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-write-iops-log and possibly also using https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-log-avg-msec to prevent the log getting too big) to see if other parts of fio give a clue.

**Comment by sitsofe** [comment] 2020-12-23 07:18
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2020-12-23 07:18 UTC
Labels: needreporterinfo
