### ISSUE TITLE
FIO benchmark runs more than the stipulated 'runtime' mentioned with 8 Numjobs

### ISSUE THREAD

**Issue by rajrammohan** [axboe/fio#252] opened 2016-10-04 12:14 UTC
FIO runs more than stipulated time & this issue is seen only with numjobs=8.

FIO Version = fio-2.13 

FIO Profile  

[global]
# logging

ioengine=rbd
clientname=admin
pool=cbt-librbdfio-rack1-client-2
rbdname=cbt-librbdfio-rack1-client-2-1
readwrite=randread
blocksize=256k
direct=1
time_based
runtime=2m
group_reporting
[rbd_iodepth32
iodepth=64
numjobs=8

**Comment by sitsofe** [comment] 2016-10-09 04:16
@rajrammohan Not really much to go on here...

Can you reproduce the problem without using the rbd engine (e.g. with pvsync), can you make this happen on the latest git version of fio, can you reduce/remove the parameters of the job file down to the minimum values and sizes that still show the problem (e.g. can the iodepth be reduced), could you include the output that shows fio overrunning the designated two minutes?

**Comment by sitsofe** [comment] 2016-11-28 07:08
@rajrammohan - have you been able to reproduce this with a more recent fio? If so what are the minimum values that have to be in the job file such that the problem still happens and what is fio's output?

**Comment by sitsofe** [comment] 2018-04-09 15:12
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2018-04-09 15:12 UTC
