### ISSUE TITLE
Job doesn't stop at runtime when rate is less than the minimum block size

### ISSUE THREAD

**Issue by shradha-khapra** [axboe/fio#1039] opened 2020-07-14 12:45 UTC
## Details of the Bug
 Job file was executed for specified runtime but instead of stopping execution after that interval it keeps running indefinitely.

## Expected output
Execution halt for FIO after the specified runtime.

### During specified runtime
![output_during_runtime](https://user-images.githubusercontent.com/34954810/87420219-860d5680-c5f2-11ea-84a7-fd79c2806ce5.png)

### After specified runtime
![output_after_runtime](https://user-images.githubusercontent.com/34954810/87420267-9ae9ea00-c5f2-11ea-92de-b4ceaa4984e0.png)
   
## OS Details
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
```
## FIO version
```
fio-3.1
```

## FIO installation
```
sudo apt install fio
```

## Job File used
```
[reader-writer]
ioengine=libaio
iodepth=4
rw=rw
runtime=30
filename=/dev/sdc
bs=4096
rate=50.497800,50.354600
```

**Comment by sitsofe** [comment] 2020-07-14 14:19
@shradha-khapra can you check if the information in https://github.com/axboe/fio/issues/1017#issuecomment-644544867 clarifies things? If so can you close this ticket. Thanks!

> [...] are you aware that by default without extra options `runtime` means "exit IF you run longer than this time" (so it's a cap) rather than "run for exactly this time"? See the [fio documentation for runtime](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-runtime)  and [timebased](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-time-based).

**Comment by sitsofe** [comment] 2020-07-14 14:22
Actually I think the above is an incorrect guess. My next question is has your disk "gone away"? Can you check what ps says about the state of all your fio processes? This might be another case of https://github.com/axboe/fio/issues/1004#issuecomment-637227364 but we will need more information to know for sure...

**Comment by vincentkfu** [comment] 2020-07-14 14:34
With the rate option you are limiting bandwidth to 50 bytes/sec but your block size is 4096 bytes. fio will work better with a more reasonable rate value, but probably it should better handle unusual cases like this.

**Comment by shradha-khapra** [comment] 2020-07-14 15:30
> Actually I think the above is an incorrect guess. My next question is has your disk "gone away"? Can you check what ps says about the state of all your fio processes? This might be another case of [#1004 (comment)](https://github.com/axboe/fio/issues/1004#issuecomment-637227364) but we will need more information to know for sure...

Yes, that seems to be an incorrect guess as the expected behaviour is exactly fio should 'exit if you run longer than this time'.

To answer the next question, all the disks are intact.

It also doesn't seem to be a case of fio process going in D state. 
#### ps aux | grep fio  
![pasAuxOutput](https://user-images.githubusercontent.com/34954810/87444600-9df5d200-c614-11ea-8a38-e814ae3978d1.png)

**Comment by sitsofe** [comment] 2020-07-15 06:02
@shradha-khapra did you see Vincent's comment about the (maximum) rate being lower than the minimum block size?

**Comment by sribs** [comment] 2020-07-15 07:04
While @vincentkfu and @sitsofe has a really good point here, I still feel that this should not have anything to do with the process being run indefinitely

**Comment by sitsofe** [comment] 2020-07-15 09:00
@sribs It shouldn't do but it likely does. I'm not saying "this is OK!" but rather I'm just looking to identify the cause:

```
./fio --name=test --ioengine=null --runtime=5 --size=1T --bs=4k --rate=4k
```

will exit as expected after 5 seconds whereas
```
./fio --name=test --ioengine=null --runtime=5 --size=1T --bs=4k --rate=512
```
will take much longer to finish. I agree this is a bug possibly linked to overflow but seemingly linked to rate and when I/O is actually done (note that I'm using fio-3.20-27-gc9be).

**Comment by sribs** [comment] 2020-07-15 10:38
I agree @sitsofe. For now, we are testing by setting the blocksize programmatically by comparing the ```block_size = min(rate, 4k)```. We are testing on SSD Physical sector size set as 4096. This will act as a workaround for our requirement. 
However, this is something that we wanted to bring to your notice since this could be experienced by other users who are using fio in their production.

Also adding @axboe to this loop

**Comment by sitsofe** [comment] 2020-07-15 21:22
I think something like this (without the debug) will workaround the issue:
```diff
diff --git a/configure b/configure
index 63b30555..29b3579b 100755
--- a/configure
+++ b/configure
@@ -340,7 +340,7 @@ int main(void)
 EOF
   if compile_prog "" "-Wl,-no_weak_imports" "disable weak symbols"; then
     echo "Disabling weak symbols"
-    LDFLAGS="$LDFLAGS -Wl,-no_weak_imports"
+    #LDFLAGS="$LDFLAGS -Wl,-no_weak_imports"
   fi
   ;;
 SunOS)
diff --git a/io_u.c b/io_u.c
index 7f50906b..d78fcacd 100644
--- a/io_u.c
+++ b/io_u.c
@@ -680,7 +680,15 @@ static enum fio_ddir rate_ddir(struct thread_data *td, enum fio_ddir ddir)
 	if (td->o.io_submit_mode == IO_MODE_INLINE)
 		io_u_quiesce(td);
 
+	if (td->o.timeout && ((usec + now) > td->o.timeout))
+		usec = td->o.timeout - now;
+	log_info("->usec_sleep usec=%llu\n", usec);
 	usec_sleep(td, usec);
+	log_info("<-usec_sleep\n");
+	now = utime_since_now(&td->epoch);
+	if ((td->o.timeout && (now > td->o.timeout)) || td->terminate)
+		ddir = DDIR_INVAL;
+
 	return ddir;
 }
 
@@ -895,6 +903,10 @@ static int fill_io_u(struct thread_data *td, struct io_u *io_u)
 		goto out;
 
 	set_rw_ddir(td, io_u);
+	if (io_u->ddir == DDIR_INVAL) {
+		dprint(FD_IO, "io_u %p, failed to set direction\n", io_u);
+		return 1;
+	}
 
 	/*
 	 * fsync() or fdatasync() or trim etc, we are done
diff --git a/stat.c b/stat.c
index b3951199..31d4f092 100644
--- a/stat.c
+++ b/stat.c
@@ -552,7 +552,8 @@ static void show_ddir_status(struct group_run_stats *rs, struct thread_stat *ts,
 			bw_str = "kB";
 
 		if (rs->agg[ddir]) {
-			p_of_agg = mean * 100 / (double) (rs->agg[ddir] / 1024);
+			log_err("p_of_agg=%llu\n", rs->agg[ddir]);
+			p_of_agg = mean * 100 / (double) (rs->agg[ddir] / 1024.0);
 			if (p_of_agg > 100.0)
 				p_of_agg = 100.0;
 		}
```

It looks like rate can sleep for a time longer than the timeout and this caps the sleep if it looks like that would happen while also trying to discard the final I/O...

**Comment by sribs** [comment] 2020-07-16 14:28
Not to review or anything. I'm just interested here
``` c
+	if (td->o.timeout && ((usec + now) > td->o.timeout))
+		usec = td->o.timeout - now;
```
Isn't there a potential for ```usec``` to take negative value here. Just curious!

Also what would be the value of ```timeout``` set here ? Is this follows the same as runtime as set earlier or is there any tolerance that is set on top of the runtime argument.

The code looks like, if fio exceeds the limit of threshold, then set the Error value ```DDIR_INVAL``` which will prevent the IO to be executed (I mean read or written). 

Will this also send a ```SIGSTOP``` or ```SIGKILL``` or any suitable signal to handle this and kill the fio process ?. The problem here is that ```fio``` is running indefinitely with no operation being performed on the disk. 

PS : I have not read the complete source code of fio and assuming these scenarios if such things were to arise. I might very well be incorrect here

**Comment by sitsofe** [comment] 2020-07-16 17:23
> Isn't there a potential for usec to take negative value here. Just curious!

Not impossible. It's unlikely that you should have entered `rate_ddir()` if the timeout had been reached (i.e. now >= timeout) but you never know... It would be safer to check...

> Also what would be the value of timeout set here ? 
It's set over in https://github.com/axboe/fio/blob/37e8cc62319b30927a3147e25b16c3e00b84692f/options.c#L2657 . There's no additional tolerance - it's more to make the job not wait just because the time to do the next I/O is far away.

> The code looks like, if fio exceeds the limit of threshold, then set the Error value DDIR_INVAL which will prevent the IO to be executed (I mean read or written).

Yeah that was my intent. If we exit "early" I don't think it makes sense to still do send the I/O as we would do normally...

> Will this also send a SIGSTOP or SIGKILL or any suitable signal to handle this and kill the fio process ?. The problem here is that fio is running indefinitely with no operation being performed on the disk.

No but it will allow fio to get back to the main run loop in https://github.com/axboe/fio/blob/master/backend.c#L986 (and I guess ultimately break out because of the "failed" I/O). I guess there's an argument that it won't mark the thread for termination though (which is normally done via https://github.com/axboe/fio/blob/master/backend.c#L965 ).

**Comment by sitsofe** [comment] 2020-07-17 05:56
@sribs BTW your comments are good and I don't really have time to fix this properly. Do you think you could have a go at whipping up a patch to fix this? We can review it can give further suggestions!

**Comment by sribs** [comment] 2020-07-17 06:56
I can give it a try. I might be having few cycles left. However, allow me some time to get fair understanding of the source code. Will submit one mostly by the EoW

**Comment by sitsofe** [comment] 2020-07-18 14:47
@sribs there's no hurry so take your time...

**Comment by sribs** [comment] 2020-07-19 10:21
@sitsofe , Link to the Pull Request : https://github.com/axboe/fio/pull/1044

**Closed** 2020-07-24 17:06 UTC
Labels: patcheswelcome, triaged
