### ISSUE TITLE
ramp_time was interrupted due to setting io_size

### ISSUE THREAD

**Issue by shaoweei** [axboe/fio#748] opened 2019-03-08 03:46 UTC
I'm running a fio test with the following job file:
I expect fio to execute for 60 seconds for ramp_time, 
then continue to perform random reads until 4000k of data are completed.
But fio ends during the ramp_time period because it has completed 4000k data.

```
;-start job file-

 [global]
 filename=/dev/nvme0n1
 direct=1
 overwrite=1
 ioengine=libaio

[RR Benchmark]
 name=[Micro QoS Benchmark Test]
 rw=randread
 bs=4k
 size=100%
 io_size=4000k
 offset=0
 iodepth=256
 numjobs=1
 ramp_time=60s
 percentile_list=99:99.9:99.99:99.999:99.9999:100
 randrepeat=0
 norandommap
 unified_rw_reporting=1
 write_lat_log=rand_read_lat
 group_reporting
;-end job file-

```

**Comment by szaydel** [comment] 2019-03-08 04:03
I do not see `runtime` value set, which would have been adjusted by the amount of `ramp_time`, otherwise what is happening I believe is correct. The point of `ramp_time` is to let things settle and recording of data to begin *after* that amount of time passes. There is no problem here, I do not think.

**Comment by shaoweei** [comment] 2019-03-08 05:59
Hi Szaydel,

Whether I set runtime or not, the results are the same. The 'runtime' starts after the end of the ramp_time, but io_size is different, the calculation starts during the ramp_time. If possible, I also hope that there are other parameters that can achieve my intended purpose.

**Comment by sitsofe** [comment] 2019-03-24 07:35
@shaoweei What you describe is intended behavior (time and I/O spent in`ramp_time` count towards most limits). In general, fio jobs will finish a job as soon at the earliest opportunity so as soon as any stopping criteria becomes true an fio job will cease even during `ramp_time`:
- If the end of the file reached **and you aren't causing I/O to be looped**
- The maximum amount of I/O is reached (assumes you are setting [`io_limit`/`io_size`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-io-size)
- The maximum number of I/Os to do is reached etc (assumes you are setting [`number_ios`](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-number-ios))
- etc.

As noted by @szaydel, `runtime`'s interaction with `ramp_time` is a special case and I'd argue it benefits from both of them working on the same "dimension" (in this case time). To do something for the other stopping criteria you would have to have a well defined description of what to do if `ramp_time` were to consume it and you wanted to continue. Should we completely reset all the counters are restart the job as if no I/O has happened or do we reset everything to some arbitrary point (and if so which point)? What if you hit the end of the file? How does this interact with looping? What happens if the user is doing a verification job at the same time? And so on.

If you are happy with looping in general maybe you want to use [`runtime`](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-runtime) combined with [`time_based`](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-time-based). However I will note that such a job risks populating the the page cache before the real I/O starts so caveat emptor. If you are happy bounding by time just drop `io_size` and go with `runtime`. Beyond that I don't think there's any existing option that will do what you're asking for so it would be new feature work. If someone were to submit a patch that provided a toggle to do what you wanted and it handled all the corner cases I'm sure it could be looked at but it would be new work...

For what it's worth, 4 megabytes is a tiny amount of I/O for a very fast disk and is likely to suffer from distortions from run to run.

As there doesn't appear to be an issue here I'm going to close this ticket.

**Closed by sitsofe** 2019-03-24 07:35 UTC
