### ISSUE TITLE
rate=[int] Windows

### ISSUE THREAD

**Issue by SimonHaywood** [axboe/fio#194] opened 2016-06-21 17:33 UTC
Hi!

I'm testing performance of Win2008 Server against a NAS. I want to do some rate limited read tests. 

However, when I set the rate=[int] I see no data being read (and the estimated time to completion increases). If I do rate_limit=[int], I get surprising results (but that may be unrelated - I can't tell at this stage).

I've tested my syntax on an OSX machine reading from internal SSD - but I can't connect the OSX machine to the NAS.

So, is there something going wrong with rate=[int] on the Windows implementation of FIO, or is it me!?

Thanks!

Simon

**Comment by sitsofe** [comment] 2016-07-18 06:19
@SimonHaywood : is rate_limit even an fio parameter? I can't see it in https://github.com/axboe/fio/blob/master/HOWTO and Linux fio says "unrecognized option" if you attempt to use it. It might help if you can post the job file...

**Comment by sitsofe** [comment] 2016-07-23 05:45
@SimonHaywood : I've just tried the following on Windows 2012R2:

`& 'C:\Program Files\fio\fio.exe' --rw=read --filename \\.\PhysicalDrive1 --name=go --runtime=1h --time_based --rate=1M`

And it correctly limited the speed to around 1MByte/s (Windows' resource manager confirms the throughput was restricted to this to). In addition to my rate_limit question above, what fio job file were you using and which version of fio?

**Comment by chrispeters1** [comment] 2016-10-07 20:43
Hello,

I'm also having an issue with rate=[int] in Windows server 2012 R2. 

The rate option works correctly for about 1 min then it stops and disk performance goes to full speed. Below are the details of my fio jobfile any help is appreciated. 

[global]

time_based
ramp_time=10s
runtime=14400s
size=859G
bs=128k
ba=4k
rw=write
iodepth=4
rate=64M
ioengine=windowsaio
direct=1
numjobs=1
thread

[job1]

directory=/io.tst
filename=io.tst

Thanks,

Chris

**Comment by sitsofe** [comment] 2016-10-08 06:05
@chrispeters1 which version of fio?

**Comment by chrispeters1** [comment] 2016-10-08 09:44
I tried using a few different versions from http://bluestop.org/fio/

2.13
2.11
2.9

Then I downloaded a version 2.14 zip from here https://github.com/axboe/fio a couple days ago and compiled my own with Cygwin. With all versions I seem to have the same issue. I also tried to simplify the jobfile by commenting out a few options and also tried rate_iops instead but still get the same outcome.

**Comment by sitsofe** [comment] 2016-10-09 03:05
@chrispeters1  Can you cut the job file down to the bear minimum that still reproduces the problem (i.e. remove every line that doesn't have an impact, make every number as small as possible, use a single file, see if the problem can be reproduced using rw=read etc) and post the result here?

**Comment by sitsofe** [comment] 2016-10-09 03:54
OK I've reproduced it too with the following job:
```
[global]
time_based
runtime=180
bs=256k
rw=read
rate=512M
thread
ioengine=windowsaio
direct=1
iodepth=2

[job1]
filename=\\.\PhysicalDrive1
```

After about 10 seconds the above job with fio-2.13 on 64bit Windows starts doing close to a 1GByte/s. The time it takes for the problem to occur seems proportional to the rate and the blocksize (e.g. with `bs=128k rate=64M` it took about 65 seconds for the problem to happen). The problem doesn't arise with fio on Linux...

**Comment by G-C-F** [comment] 2016-10-25 16:28
I am also seeing this issue while trying to run the same workload on Linux and Windows. I see a hard limit of 15MB/s writes and reads on Linux, but closer to 18MB/s writes and 13MB/s on Windows. 15MB/s on both reads and writes is what I am attempting. Any updates on a fix for this?

**Comment by sitsofe** [comment] 2016-11-15 22:22
OK changing all the "rate state" in fio.h to be uint64_t resolved the problem for me (although I can't help wondering if I'm just kicking the can down the road). Mentioning @DaveGlen for comment because Dave introduced the current rate control algorithm in 50a8ce8 . Theoretically you might see this issue with 32 bit Linux fio too...

(Hopefully posting this comment in the correct issue this time)

**Closed** 2016-11-28 01:57 UTC
