### ISSUE TITLE
fio 3.11 and 3.12 both logging incorrect data for write_hist_log parameter

### ISSUE THREAD

**Issue by benjamin-slater** [axboe/fio#715] opened 2018-11-15 23:34 UTC
Using the write_hist_log parameter on fio versions 3.11 and 3.12 produce incorrect data. Running on an NVMe drive with [wr_qd_256_128k_1w.ini.txt](https://github.com/axboe/fio/files/2586895/wr_qd_256_128k_1w.ini.txt), the following files are produced:[wr_qd_256_128k_1w_clat_hist.log_clat_hist.1.log](https://github.com/axboe/fio/files/2586879/wr_qd_256_128k_1w_clat_hist.log_clat_hist.1.log) and [wr_qd_256_128k_1w_summary.log](https://github.com/axboe/fio/files/2586880/wr_qd_256_128k_1w_summary.log). The per second data does not seem to match the data in the summary file.  When running the same parameters on an Optane drive the following files are produced:
[wr_qd_256_128k_1w_clat_hist_optane.log_clat_hist.1.log](https://github.com/axboe/fio/files/2586875/wr_qd_256_128k_1w_clat_hist_optane.log_clat_hist.1.log) and [wr_qd_256_128k_1w_summary_optane.log](https://github.com/axboe/fio/files/2586876/wr_qd_256_128k_1w_summary_optane.log)
. The Optane per second data shows no IO, but IOPS are calculated in the summary log.  This feature did work on fio version 3.5 and running without the write_hist_log parameter produces correct data on both fio 3.11 and 3.12.

**Comment by sitsofe** [comment] 2018-11-16 06:05
@benjamin-slater Thanks for reporting this. Is there any chance you can bisect this down to the release (or even better the commit) that introduced this? If you're familiar with it, you can use `git bisect` for this...

**Comment by benjamin-slater** [comment] 2018-11-20 18:57
I have found that this behavior was introduces in version 3.6. Unfortunately I am not terribly familiar with `git bisect`, but I will see if I can find the commit that introduced this.

**Comment by benjamin-slater** [comment] 2018-11-27 17:12
Using `git bisect` I found that the commit responsible seems to be 6cc0e5aa9eddd2487dfa9ac80be1264151058409.

**Comment by sitsofe** [comment] 2019-03-26 05:29
@vincentkfu any ideas on this one?

**Comment by vincentkfu** [comment] 2019-03-26 13:13
I have never used the clat histogram logging feature. A quick look at the code revealed no obvious issues. @bengland2 has this been working for you recently?

**Comment by bengland2** [comment] 2019-03-26 13:21
So perhaps this may be a mis-interpretation of the output in this log file?     To see what's in it, you need to run the [fio-histo-log-pctiles.py](https://github.com/axboe/fio/blob/master/tools/hist/fio-histo-log-pctiles.py) tool.   Run it with -h to get help on parameters.   For documentation on what it does see [this pdf](https://github.com/axboe/fio/blob/master/doc/fio-histo-log-pctiles.pdf).

**Comment by sitsofe** [comment] 2019-03-28 05:21
@benjamin-slater have you seen the latest response?

**Comment by benjamin-slater** [comment] 2019-03-28 15:14
@bengland2  I will give that tool a shot and update the thread with the results.

**Comment by sitsofe** [comment] 2019-04-25 16:05
@benjamin-slater any luck?

**Comment by eortega3** [comment] 2019-07-15 23:16
Ran the clat hist logs utilizing the fio-hist-o-log-pctiles.py and received the following out puts, below are the results.

WRITE QD256 128K
![screenshot of fioHist from clat hist write 256 qd 128k](https://user-images.githubusercontent.com/32280300/61255050-dc179780-a71b-11e9-8737-c958a1017a65.PNG)

WRITE QD256 128K - OPTANE
![screenshot of fioHist from clat hist write 256 qd 128k OPTANE](https://user-images.githubusercontent.com/32280300/61255055-e0dc4b80-a71b-11e9-83e9-f30532d4903b.PNG)

**Comment by bengland2** [comment] 2019-07-16 18:27
@eortega3 I'll have a look sometime this week, try to reproduce and get back to you, thanks for the detailed info.

**Comment by sitsofe** [comment] 2019-09-27 04:44
@bengland2 did you have any luck?

**Comment by bengland2** [comment] 2019-09-28 13:29
@eortega3 somehow this slipped through my to-do-list, sorry about that.  I took your job file and made a few changes on it, reproduced the problem on my laptop.    However, the **raw histogram log emitted by fio has all zeroes**, even though I was doing about 10K IOPS to this file (on an NVM device).   I suspect it's related to your job parameters, because I did not try every possible fio parameter having to do with this feature when I tested it.   What is the simplest example of this behavior that we can find (with the fewest fio job parameters)?  So far I have reproduced with

```
[global]
name= With_write_hist_log
ioengine=libaio
log_avg_msec=1000
write_lat_log=x
log_hist_msec=1000
write_hist_log=x
direct=1
size=128m
time_based
filename=/var/tmp/x.fiodata

[wr_qd_256_128k_1w]
stonewall
bs=128k
iodepth=256
numjobs=1
rw=write
runtime=10
```

Which is pretty basic.

**Comment by bengland2** [comment] 2019-09-29 14:59
so looking at the commit flagged as the one that broke this feature, it appears mostly to be about converting counters from 32 bits to 64 bits, so perhaps the code that export the histogram structures to a log file wasn't converted?   Looking...

**Comment by bengland2** [comment] 2019-09-29 15:28
@eortega3  I put in a rate_iops=2000 in the job file and the histogram counters became non-zero.     I comment out this line in the job file and the counters go back to zero.  Furthermore, if I set K to some insanely high value like 200000,  the counters go back to zero, suggesting that the act of limiting the rate somehow lets the counters in the histogram array get updated.   Why?  I'll post a separate issue about fio-histo-log-pctiles.py not supporting log_hist_coarseness parameter > 0.

**Comment by sitsofe** [comment] 2019-10-15 03:38
I've just realised this might be fixed by https://github.com/axboe/fio/pull/840 (if only I'd looked at this issue earlier...). @benjamin-slater: is this issue any better with the latest got fio?

**Comment by benjamin-slater** [comment] 2019-10-15 15:47
@sitsofe I have not checked out the latest version.  I will check it out and report back.

**Comment by benjamin-slater** [comment] 2019-10-17 21:42
This issue appears to be resolved with https://github.com/axboe/fio/pull/840

**Comment by sitsofe** [comment] 2019-10-18 06:47
@benjamin-slater thanks for following up and sorry it took so long to get around to this one! I'll close this issue now seems fixed.

**Closed by sitsofe** 2019-10-18 06:47 UTC
Labels: needinfo, triaged
