### ISSUE TITLE
io_uring latencies are reporting much higher on QD1

### ISSUE THREAD

**Issue by eortega3** [axboe/fio#793] opened 2019-06-24 23:14 UTC
Hello!

io_uring QD1 workload's iops/BW are reporting consistently higher than IOENGINE QD1 pvsync2

However, the io_uring QD1 latencies from 1-100 percentile values are significantly off (It is reporting up in the 10's of 1000's of % higher) from what the other ioengines are reporting.  

Below is an example of the ini file I am specifically running.
#####
ioengine=io_uring
hipri
direct=1
buffered=0
size=100%
randrepeat=0
time_based
ramp_time=30
norandommap
refill_buffers
log_avg_msec=1000
log_max_value=1
group_reporting
percentile_list=1.0:25.0:50.0:75.0:90.0:99.0:99.9:99.99:99.999:99.9999:99.99999:99.999999:100.0
filename=/dev/nvme0n1

[rd_qd_1_4k_1w]
stonewall
bs=4k
iodepth=1
numjobs=1
rw=read
####

I am running my tests on the latest kernel (5.1.0-el7.elrepo.x86_64) and this build of FIO (3.13-41-g2857-dirty)

Is there a significant difference in the way latency/percentiles are reported relative to iops in the new ioengine?

Or is this a kernel specific issue?

**Comment by sitsofe** [comment] 2019-10-15 04:58
@eortega3 are you still seeing this? @axboe can you reproduce this?

**Comment by sitsofe** [comment] 2019-11-01 08:33
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2019-11-01 08:33 UTC
Labels: needinfo
