### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by tjodork** [axboe/fio#539] opened 2018-02-22 23:36 UTC
# fio /tmp/fio.sdbg.jobfile
job1: (g=0): rw=randread, bs=16K-16K/16K-16K/16K-16K, ioengine=libaio, iodepth=1
fio-2.2.8
Starting 1 thread
fio: check /proc/sys/fs/aio-max-nr
fio: pid=97220, err=11/file:engines/libaio.c:353, func=io_queue_init, error=Resource temporarily unavailable

Run status group 0 (all jobs):

Disk stats (read/write):
  sdbg: ios=0/0, merge=0/0, ticks=0/0, in_queue=0, util=0.00%

# cat /tmp/fio.sdbg.jobfile
[global]
bs=16k
direct=1
buffered=0
iodepth=1
group_reporting=1
rw=randread
rwmixread=0
rwmixwrite=0
ioengine=libaio
runtime=1200
time_based
numjobs=1
thread
norandommap
size=99%
[job1]
filename=/dev/sdbg

the sdbg resource is ok ..

************ sdbg ************
Command is sg_raw -r 8  /dev/sdbg  25 00 00 00 00 00 00 00 00 00
Sending cdb 28 00 00 00 00 00 00 00 01 00
Command is sg_raw -r 4096  -b  -o  /dump/read_sdbg  /dev/sdbg  28 00 00 00 00 00 00 00 01 00
Read Command was successful and data stored in file:/dump/read_sdbg with size 4096 bytes

Im not sure why I'm gettint the error above...any help would be appreciated

**Comment by sitsofe** [comment] 2018-02-23 07:08
@tjodork 

The error is trying to say you're out of AIO resources (see the ERRORS 
 section of http://manpages.ubuntu.com/manpages/xenial/man2/io_queue_init.2.html ) rather than the device is unaccessible. As the message suggests can you cat `/proc/sys/fs/aio-max-nr` and post the output here? It might also be interesting to know what distro and what kernel you're running and whether you're in some sort of sub-environment (e.g. a container).

Additionally can you reproduce the problem with the latest upstream version of fio? You're running fio-2.2.8 and we're quite a bit beyond that (see https://github.com/axboe/fio/releases ). Distros often have old versions of fio but since you are asking for upstream we really need you to be running the latest upstream version (which probably means building fio for yourself:  )...

**Comment by sitsofe** [comment] 2018-02-26 18:38
@tjodork Can you provide any more information on this one and if you're not able to could you close this issue for now?

**Closed** 2018-04-09 14:57 UTC

**Comment by ThilinaManamgoda** [comment] 2020-06-03 18:33
@sitsofe I ran into this issue when running a test against a persistence volume mount on Kubernetes. 
```
cat  /proc/sys/fs/aio-max-nr
65536
```
Do you have any idea how we can overcome this issue? Would increasing **fs.aio-max-nr** value fix this?

**Comment by sitsofe** [comment] 2020-06-09 03:26
@ThilinaManamgoda Hi,

That messages corresponds to https://github.com/axboe/fio/blob/c9beb194ef608dc49dd2f7537b90951f3c8b432d/engines/libaio.c#L393 so it does look to be the same thing (`EAGAIN` be returned by `io_queue_init`). You didn't say what depth your jobs are doing but if it were 64 or more it's highly likely that you're hitting your `/proc/sys/fs/aio-max-nr` and yes raising that value would help BUT you need to raise it on the host rather than from inside the container. Writing to `/proc` from a container is disallowed by default (otherwise containers could quickly hurt the host).

(PS: it's kinder not to add a question on to a closed issue as it's easy to overlook. Additionally we prefer questions (to be sent the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.192/README#L58) (note that the list only accepts plain text emails))

**Comment by ThilinaManamgoda** [comment] 2020-06-09 03:58
@sitsofe Yes, I am using 64 as the IO depth. I'll look into the possibility of setting `aio-max-nr` in the Kubernetes worker node. 

>(PS: it's kinder not to add a question on to a closed issue as it's easy to overlook. Additionally we prefer questions (to be sent the fio mailing list (note that the list only accepts plain text emails))
Noted and I apologize for the trouble. I'll start sending questions to the mailing.
