### ISSUE TITLE
running fsync with --client results in returncode of 1

### ISSUE THREAD

**Issue by jtaleric** [axboe/fio#839] opened 2019-10-11 00:07 UTC
Attempting to run this simple test w/ `--client`

```
sh-4.2$ fio --client=10.129.2.47 --rw=write --ioengine=sync --fdatasync=1 --directory=test-data --size=22m --bs=2300 --name=mytest                     
mytest: (g=0): rw=write, bs=(R) 2300B-2300B, (W) 2300B-2300B, (T) 2300B-2300B, ioengine=sync, iodepth=1
sh-4.2$ echo $?
1
```

Testing with a jobfile with :
```
[global]
directory=/tmp
filename_format=f.\$jobnum.\$filenum
write_bw_log=fio
write_iops_log=fio
write_lat_log=fio
write_hist_log=fio
log_avg_msec=1000
log_hist_msec=1000
clocksource=clock_gettime
kb_base=1000
unit_base='8'
ioengine=sync
size=23MiB
bs=2300B
iodepth=1

numjobs=1

[write]
rw=write
ioengine=sync
fdatasync=1
```

Results in :
```
sh-4.2$ fio --client=10.129.2.47 fiojob 
hostname=fio-server-1-benchmark-e91c8d4e-sbr6m, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.12, flags=1
<fio-server-1-benchmark-e91c8d4e-sbr6m> write: (g=0): rw=write, bs=(R) 2300B-2300B, (W) 2300B-2300B, (T) 2300B-2300B, ioengine=sync, iodepth=1
<fio-server-1-benchmark-e91c8d4e-sbr6m> Starting 1 process
<fio-server-1-benchmark-e91c8d4e-sbr6m> =1505 IOPS][eta 00m:00s]
write: (groupid=0, jobs=1): err= 0: pid=78: Fri Oct 11 00:06:31 2019
  write: IOPS=1480, BW=3406kB/s (3326KiB/s)(24.1MB/7080msec)
    clat (usec): min=3, max=3921, avg=180.29, stdev=172.37
     lat (usec): min=3, max=3921, avg=181.01, stdev=172.38
    clat percentiles (usec):
     |  1.00th=[    4],  5.00th=[    4], 10.00th=[    5], 20.00th=[    5],
     | 30.00th=[    6], 40.00th=[   11], 50.00th=[  281], 60.00th=[  293],
     | 70.00th=[  302], 80.00th=[  310], 90.00th=[  326], 95.00th=[  347],
     | 99.00th=[  506], 99.50th=[  668], 99.90th=[ 1270], 99.95th=[ 1975],
     | 99.99th=[ 2704]
   bw (   kB/s): min= 3034, max= 3508, per=99.96%, avg=3324.71, stdev=162.38, samples=7
   iops        : min= 1351, max= 1562, avg=1480.43, stdev=72.32, samples=7
  lat (usec)   : 4=6.32%, 10=33.21%, 20=4.04%, 50=0.25%, 100=0.01%
  lat (usec)   : 250=0.03%, 500=55.08%, 750=0.68%, 1000=0.18%
  lat (msec)   : 2=0.16%, 4=0.04%
  cpu          : usr=1.06%, sys=2.74%, ctx=37069, majf=0, minf=40
  IO depths    : 1=200.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,10485,0,0 short=10485,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=3406kB/s (3326KiB/s), 3406kB/s-3406kB/s (3326KiB/s-3326KiB/s), io=24.1MB (22.0MiB), run=7080-7080msec
sh-4.2$ 
```

However, I am missing the fsync data. Any help would be great! My preference would be to get the fsync data using the fiojob file.

**Comment by sitsofe** [comment] 2019-10-11 08:29
@jtaleric:

- Do you see fsync data running the same job in "local mode"? If not do you see it locally when you just use `fsync=1` rather than `fdatasync=1`?

**Comment by jtaleric** [comment] 2019-10-11 10:14
Yup, running a local job works just fine.

**Comment by jtaleric** [comment] 2019-10-11 16:07
@sitsofe ^ FYI, sorry I didn't tag you in my response.

**Comment by jtaleric** [comment] 2019-10-11 19:51
@sitsofe Trying with fsync=1

```
sh-4.2$ fio --client=10.129.2.47 fiojob 
hostname=fio-server-1-benchmark-e91c8d4e-sbr6m, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.12, flags=1
<fio-server-1-benchmark-e91c8d4e-sbr6m> write: (g=0): rw=write, bs=(R) 2300B-2300B, (W) 2300B-2300B, (T) 2300B-2300B, ioengine=sync, iodepth=4
<fio-server-1-benchmark-e91c8d4e-sbr6m> Starting 1 process
<fio-server-1-benchmark-e91c8d4e-sbr6m> =912 IOPS][eta 00m:00s]
write: (groupid=0, jobs=1): err= 0: pid=86: Fri Oct 11 19:50:46 2019
  write: IOPS=777, BW=1789kB/s (1747KiB/s)(24.1MB/13477msec)
    clat (usec): min=4, max=39106, avg=222.52, stdev=873.83
     lat (usec): min=4, max=39108, avg=223.26, stdev=873.86
    clat percentiles (usec):
     |  1.00th=[    5],  5.00th=[    5], 10.00th=[    5], 20.00th=[    5],
     | 30.00th=[    7], 40.00th=[   11], 50.00th=[  285], 60.00th=[  297],
     | 70.00th=[  302], 80.00th=[  310], 90.00th=[  322], 95.00th=[  334],
     | 99.00th=[  529], 99.50th=[ 1549], 99.90th=[13960], 99.95th=[21627],
     | 99.99th=[35914]
   bw (   kB/s): min=  257, max= 2120, per=99.33%, avg=1735.31, stdev=553.43, samples=13
   iops        : min=  114, max=  944, avg=772.69, stdev=246.60, samples=13
  lat (usec)   : 10=38.10%, 20=5.19%, 50=0.53%, 100=0.01%, 250=0.01%
  lat (usec)   : 500=55.08%, 750=0.31%, 1000=0.07%
  lat (msec)   : 2=0.26%, 4=0.09%, 10=0.19%, 20=0.10%, 50=0.06%
  cpu          : usr=0.67%, sys=2.20%, ctx=37388, majf=0, minf=54
  IO depths    : 1=200.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,10485,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=4

Run status group 0 (all jobs):
  WRITE: bw=1789kB/s (1747KiB/s), 1789kB/s-1789kB/s (1747KiB/s-1747KiB/s), io=24.1MB (22.0MiB), run=13477-13477msec
sh-4.2$ cat fiojob 
[global]
directory=/tmp
filename_format=f.\$jobnum.\$filenum
write_bw_log=fio
write_iops_log=fio
write_lat_log=fio
write_hist_log=fio
log_avg_msec=1000
log_hist_msec=1000
clocksource=clock_gettime
kb_base=1000
unit_base='8'
ioengine=sync
size=23MiB
bs=2300B
iodepth=4

numjobs=1

[write]
rw=write
ioengine=sync
fsync=1

```

**Comment by bengland2** [comment] 2019-10-14 15:31
@jtaleric  I reproduced.   git bisection might help here, I think this used to work.  I don't recall this kind of problem a year or two ago.

**Comment by bengland2** [comment] 2019-10-14 16:28
@jtaleric I just tried dropping unit_base=8 and the fio job worked. It sounds like byte-based reporting is the default anyway, so why is it in this example?

**Comment by dustinblack** [comment] 2019-10-14 17:23
Without `unit_base='8'`, fio defaults to base-10 *B units instead of base-2 *iB units. For our purposes in ripsaw, we use a config file that applies size-based parameters to both the ripsaw jobfile and to the kubernetes storage configuration. For k8s, the units are _always_ base-2 *iB units, and this cannot be changed (though there is a separate unit semantics problem there I still need to report to k8s).

In order to standardize the units we use in our ripsaw config file, we chose to use `unit_base='8'` in the fio jobfile template, thus making both fio and k8s options in the same file adhere to base-2 *iB unit formats.

**Comment by bengland2** [comment] 2019-10-14 19:11
@dblack, In the [fio documentation here](https://fio.readthedocs.io/en/latest/fio_doc.html), it says that unit_base=8 makes it report in bytes instead of bits, and the default is to auto-config (not sure what that means), so it's *not* about base-2 units versus power-of-10 units.   

However, fio v3.12 that Joe Talerico is using does not support this parameter.  If you omit it, the job completes successfully.   If you take the single-quotes off of the integer parameter the job completes successfully @jtaleric

**Comment by bengland2** [comment] 2019-10-14 21:21
the real issue was that if you run it from the command line it fails, but if you run the same thing from a jobfile it succeeds.   I can't debug it, because the server exits silently without a core dump, and gdb does not work because of fork() calls inside server.  Simplest form:
```
fio --client=localhost --rw=write  --directory=/tmp --size=22m --name=mytest
```

**Comment by dblack** [comment] 2019-10-14 21:34
@bengland2 I think you meant @dustinblack.

**Comment by bengland2** [comment] 2019-10-14 21:59
sorry that's right.

**Comment by sitsofe** [comment] 2019-10-15 05:30
@bengland2 re client commands that only work in a jobfile - are you hitting https://github.com/axboe/fio/issues/621 ?

**Comment by bengland2** [comment] 2019-10-16 19:30
fdatasync=1 means every single write will result in a fdatasync() call, but write latency and histogram logs will not capture fdatasync() latency.   So alternative is to use O_SYNC writes with sync=1.

**Comment by dustinblack** [comment] 2019-10-16 19:40
@bengland2 Ack -- I was confusing `unit_base` with `kb_base`. Mea culpa.

**Comment by sitsofe** [comment] 2019-12-16 18:26
@jtaleric After reading through the comments I'm unsure what the issue is here. Were you using an option not supported by your version of fio?

**Comment by jtaleric** [comment] 2019-12-16 19:46
> @jtaleric After reading through the comments I'm unsure what the issue is here. Were you using an option not supported by your version of fio?

Reading the documentation i was under the assumption it was a supported option. Why do you think it isn't?

**Comment by jtaleric** [comment] 2019-12-16 19:48
For reference, I am running with `fio-3.12`

**Comment by sitsofe** [comment] 2019-12-16 20:34
@jtaleric fair point but my understanding is that the option was buggy until fio 3.13 (see https://github.com/axboe/fio/commit/92a1a1d701f8af640859a75cc74f82b7bf9e3a0a )...

**Comment by sitsofe** [comment] 2019-12-17 15:10
@jtaleric Now I read back what I wrote, could you check if this is still an issue with the latest master version of fio? Thanks!

**Comment by sitsofe** [comment] 2020-01-12 10:44
Closing because we need more information from the reporter to take this further.

@jtaleric - please re-open this issue if/when you're able to do more supply the requested information. Thank you!

**Closed by sitsofe** 2020-01-12 10:44 UTC
Labels: needinfo
