### ISSUE TITLE
fio version 3.10 reports lesser results

### ISSUE THREAD

**Issue by jo-ale35** [axboe/fio#696] opened 2018-09-27 08:58 UTC
Used the latest version of fio "fio-3.10" but it reports very less results.  Previously I was using fio-3.8 version where the results were pretty much reliable. Now in the same system with same profile file and same configurations, the results are very less compared to the other one.

**Comment by sitsofe** [comment] 2018-09-27 11:59
@jo-ale35 Hi!

We're going to need you to (git) bisect this one. To do this you'll need to do a `git clone` of fio and then use [git bisect](https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git) to mark various versions good or bad to narrow down the commit that introduced the regression. See https://stackoverflow.com/questions/4713088/how-to-use-git-bisect for an overview of the process and when you're done post your `git bisect log` here.

**Comment by sitsofe** [comment] 2018-10-06 04:40
@jo-ale35 Hi, are you able to provide the information being requested by Jens or the results of a git bisect?

**Comment by sitsofe** [comment] 2018-10-16 03:52
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2018-10-16 03:52 UTC
Labels: needinfo
