### ISSUE TITLE
zoneskip is not respected unless norandommap is set

### ISSUE THREAD

**Issue by yurzo** [axboe/fio#513] opened 2018-01-11 19:57 UTC
Seems like there's a shift by one.
The norandommap does not have a single attempt to read from a 5 aligned offset vs the other one.

I don't need a fix since norandommap is good enought for me. Filing for completeness.

```
./fio/fio --bs=1 --rw=randread --size=100 --io_size=2000 --direct=1 --ioengine=null --name=carlos --zonesize=5 --zoneskip=5 --write_iolog=cmds_nr.txt --norandommap
```

```
./fio/fio --bs=1 --rw=randread --size=100 --io_size=2000 --direct=1 --ioengine=null --name=carlos --zonesize=5 --zoneskip=5 --write_iolog=cmds.txt
```

```
grep -c '5 1' cmds*
cmds_nr.txt:0
cmds.txt:171
```

**Comment by sitsofe** [comment] 2018-01-12 07:17
There's a problem which I think was fixed by @gvkovai over in https://github.com/axboe/fio/issues/450 . I have a rebased version of the patch there plus one of my own over on https://github.com/sitsofe/fio/tree/zone_calc_size but I think there was some problem with it that I can't remember...

**Comment by sitsofe** [comment] 2018-01-12 07:42
Ah there's a pull request over on https://github.com/axboe/fio/pull/457 but I never got time to polish it more...

**Comment by sitsofe** [comment] 2018-01-17 19:54
@yurzo can you check if the problem is still present with the latest git version of fio?

**Comment by yurzo** [comment] 2018-01-17 20:12
Looks better!
```
damian.yurzola@vm-damian-yurzola:~/fio_learning$ grep -c '5 1' cmds*
cmds_nr.txt:0
cmds.txt:0
```

**Comment by yurzo** [comment] 2018-01-17 20:13
In fact it looks perfect:
```
damian.yurzola@vm-damian-yurzola:~/fio_learning$ grep -c '[5-9] 1' cmds*
cmds_nr.txt:0
cmds.txt:0
damian.yurzola@vm-damian-yurzola:~/fio_learning$ grep -c '[0-4] 1' cmds*
cmds_nr.txt:2000
cmds.txt:2000
```

**Comment by sitsofe** [comment] 2018-01-18 08:28
@yurzo that does look better - could you close this issue?

**Closed** 2018-01-18 15:40 UTC
