### ISSUE TITLE
Windows FIO exit before time with high runt value

### ISSUE THREAD

**Issue by jasonjorge** [axboe/fio#266] opened 2016-11-09 16:37 UTC
I've been running the latest windows version (2.15 x64) with the following command line, downloaded from Bluestop.  Every time I attempt to run the following workload FIO will always exit after ~25mins, and the IOPs reported are 0.

fio --filename="\\.\PhysicalDrive1" --time_based=1 --ramp_time=5s --runtime=7200s --direct=1 --bs=4KB --iodepth=1 --ioengine=windowsaio --thread=1 --output="4KB_RandRd_QD=1_1.out" --name="4KB RandRd QD=1" --rw=randread

![image](https://cloud.githubusercontent.com/assets/8410864/20146097/3700b44a-a668-11e6-9344-60aa085b39d8.png)

I looked in the output file, and the runt value is runt=18446744071562070msec

This same command line worked correctly with version 2.13. 

When we run with a runtime value of less than half hour the test completes successfully.  

for example --runtime=300s completes in runt=300068msec

4KB RandRd QD=1: (g=0): rw=randread, bs=4K-4K/4K-4K/4K-4K, ioengine=windowsaio, iodepth=1
fio-2.15
Starting 1 thread

output results.
4KB RandRd QD=1: (groupid=0, jobs=1): err= 0: pid=2268: Wed Nov 9 16:12:46 2016
  read : io=701144KB, bw=565B/s, iops=0, runt=18446744071562070msec
    slat (usec): min=7, max=6563, avg=16.80, stdev=22.67
    clat (usec): min=864, max=91597, avg=12229.06, stdev=4148.19
     lat (usec): min=881, max=91614, avg=12245.86, stdev=4148.23
    clat percentiles (usec):
     |  1.00th=[ 4128],  5.00th=[ 5856], 10.00th=[ 7072], 20.00th=[ 8768],
     | 30.00th=[10048], 40.00th=[11072], 50.00th=[12096], 60.00th=[13120],
     | 70.00th=[14144], 80.00th=[15552], 90.00th=[17280], 95.00th=[18560],
     | 99.00th=[27776], 99.50th=[29056], 99.90th=[30336], 99.95th=[30592],
     | 99.99th=[34048]
    lat (usec) : 1000=0.01%
    lat (msec) : 2=0.01%, 4=0.83%, 10=29.14%, 20=67.78%, 50=2.23%
    lat (msec) : 100=0.01%
  cpu          : usr=0.05%, sys=0.14%, ctx=0, majf=0, minf=0
  IO depths    : 1=100.2%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=175286/w=0/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: io=701144KB, aggrb=0KB/s, minb=0KB/s, maxb=0KB/s, mint=4294967295msec, maxt=18446744071562070msec

**Comment by sitsofe** [comment] 2016-11-09 16:45
Look at that runt - 18446744071562070msec . If that's really milliseconds then that's years' worth of time passing...

**Comment by jasonjorge** [comment] 2016-11-15 21:52
Any Update on this?  Is there something that I can do to help recreate?

**Comment by sitsofe** [comment] 2016-11-15 22:06
I've actually been debugging this over the last hour. Interestingly the problem seems to happen around the 4GBytes of I/O done mark so I think it's because `rate_io_issue_bytes` is an `unsigned long` (which means on 64 bit Linux it's 8 bytes long but on Windows it's only 4 - see http://stackoverflow.com/a/384672/4513656 ). Just recompiling setting it to a `uint64_t` to see if it makes things better...

**Comment by sitsofe** [comment] 2016-11-15 22:19
OK changing all the "rate state" in `fio.h` to be `uint64_t` resolved the problem for me (although I can't help wondering if I'm just kicking the can down the road). Mentioning @DaveGlen for comment because Dave introduced the current rate control algorithm in https://github.com/axboe/fio/commit/50a8ce864e2c5bee7c44935b39b357aa8071615b . Theoretically you might see this issue with 32 bit Linux fio too...

**Comment by sitsofe** [comment] 2016-11-15 22:20
Apologies - got the wrong issue!

**Comment by sitsofe** [comment] 2016-11-15 22:40
@jasonjorge: Could you check if this happens with 2.14 too and can you see if you can find the minimum number of command line parameters that still reproduce the issue (e.g. if you set the runtime to 30 minutes can you still reproduce this issue)?

**Comment by sitsofe** [comment] 2016-11-15 23:23
I wonder if this problem is because `usec` in `utime_since()` from `gettime.c` is defined as a (signed) `long` but is returned (via the function) as a `uint64_t`. On Windows a `long` is only 32 bits so if it wraps and becomes negative this could cause problems when cast to an unsigned value...

**Comment by sitsofe** [comment] 2016-11-16 10:20
Using the following job I found fio exited after 35 minutes and 48 seconds rather than after the expected 50 minutes:

```
[global]
time_based
runtime=50m
bs=4k
thread
ioengine=null

[null]
size=4k
```

In microseconds that's 2148000000 which is not far off 2147483648 (2^32/2). Using the following diff:

```patch
diff --git a/gettime.c b/gettime.c
index 73b48b0..8496aa8 100644
--- a/gettime.c
+++ b/gettime.c
@@ -381,7 +381,7 @@ void fio_clock_init(void)

 uint64_t utime_since(const struct timeval *s, const struct timeval *e)
 {
-       long sec, usec;
+       long long sec, usec;

        sec = e->tv_sec - s->tv_sec;
        usec = e->tv_usec - s->tv_usec;
```

lets the same job run for 50 minutes. I think the patch resolves the issue because the accumulation of seconds into `usec` can (quickly) overflow a 32 bit signed long (32 bit Linux, Windows).

**Comment by sitsofe** [comment] 2017-01-03 22:35
@jasonjorge can you still reproduce this issue with fio 2.16 on 64 bit Windows? I think the fixes referenced above should resolve this...

**Comment by sitsofe** [comment] 2017-04-09 06:11
@jasonjorge Is this issue solved with recent fio versions and If so could you close this issue?

**Closed** 2018-04-09 14:57 UTC
