### ISSUE TITLE
Multiple writes to the same offset when using multiple filenames

### ISSUE THREAD

**Issue by Vladyyy** [axboe/fio#823] opened 2019-09-26 22:06 UTC
I'm running the following Fio job to drive IO to 2 different devices:
```
fio --name=full_device_write --rw=randwrite  --direct=1 --ioengine=libaio --verify=crc32c --verify_dump=1 --bs=32k --iodepth=32 --filename=/dev/nbd0:/dev/nbd2 --serialize_overlap=1 --randseed=0
```

This is failing with:
```
verify: bad header numberio 50389, wanted 0 at file /dev/nbd0 offset 259031040, length 32768 (requested block: offset=259031040, length=32768)
       hdr_fail data dumped as nbd0.259031040.hdr_fail
```

When I look at the debug log I see that there are multiple writes being made to the same offset:

```
io       11560 fill: io_u 0x1fce5c0: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd0
io       11560 prep: io_u 0x1fce5c0: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd0
io       11560 queue: io_u 0x1fce5c0: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd0
io       11560 complete: io_u 0x1fce5c0: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd0

io       11560 fill: io_u 0x1fcc080: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd0
io       11560 prep: io_u 0x1fcc080: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd0
io       11560 queue: io_u 0x1fcc080: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd0
io       11560 complete: io_u 0x1fcc080: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd0

io       11560 fill: io_u 0x1fcb9c0: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd2
io       11560 prep: io_u 0x1fcb9c0: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd2
io       11560 queue: io_u 0x1fcb9c0: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd2
io       11560 complete: io_u 0x1fcb9c0: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd2

io       11560 fill: io_u 0x1fcdf00: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd2
io       11560 prep: io_u 0x1fcdf00: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd2
io       11560 queue: io_u 0x1fcdf00: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd2
io       11560 complete: io_u 0x1fcdf00: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd2

io       11560 prep: io_u 0x1fcd840: off=0xf708000,len=0x8000,ddir=0,file=/dev/nbd0
io       11560 queue: io_u 0x1fcd840: off=0xf708000,len=0x8000,ddir=0,file=/dev/nbd0
```

My expectation is that there should be a single IO to each block, however from the output above I case that each device has received 2 different writes to the same offset.

I'm running fio-3.14

**Comment by sitsofe** [comment] 2019-09-27 04:43
@Vladyyy I've been trying to reproduce an issue but I'm a bit unsure about what I'm looking for in your debug output (reproduced with line numbers below). Which lines show the duplication against the same file?

```
 1	io       11560 fill: io_u 0x1fce5c0: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd0
 2	io       11560 prep: io_u 0x1fce5c0: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd0
 3	io       11560 queue: io_u 0x1fce5c0: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd0
 4	io       11560 complete: io_u 0x1fce5c0: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd0
  	
 5	io       11560 fill: io_u 0x1fcc080: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd0
 6	io       11560 prep: io_u 0x1fcc080: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd0
 7	io       11560 queue: io_u 0x1fcc080: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd0
 8	io       11560 complete: io_u 0x1fcc080: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd0
  	
 9	io       11560 fill: io_u 0x1fcb9c0: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd2
10	io       11560 prep: io_u 0x1fcb9c0: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd2
11	io       11560 queue: io_u 0x1fcb9c0: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd2
12	io       11560 complete: io_u 0x1fcb9c0: off=0xf7080000,len=0x8000,ddir=1,file=/dev/nbd2
  	
13	io       11560 fill: io_u 0x1fcdf00: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd2
14	io       11560 prep: io_u 0x1fcdf00: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd2
15	io       11560 queue: io_u 0x1fcdf00: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd2
16	io       11560 complete: io_u 0x1fcdf00: off=0xf708000,len=0x8000,ddir=1,file=/dev/nbd2
  	
17	io       11560 prep: io_u 0x1fcd840: off=0xf708000,len=0x8000,ddir=0,file=/dev/nbd0
18	io       11560 queue: io_u 0x1fcd840: off=0xf708000,len=0x8000,ddir=0,file=/dev/nbd0
```

(I was using
```
awk '/complete:/ { print $6 }' output
```
to cut down what I had to look at)

**Comment by sitsofe** [comment] 2019-10-10 06:23
@Vladyyy just a quick ping to see if you can clarify the problem...

**Comment by sitsofe** [comment] 2019-11-01 08:32
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2019-11-01 08:32 UTC
Labels: needinfo
