### ISSUE TITLE
Fio on aarch64 and CentOS 7.4(AltArch) fio: 1 job failed to start  fio: terminating on signal 15

### ISSUE THREAD

**Issue by fossxplorer** [axboe/fio#546] opened 2018-03-01 09:36 UTC
It seems i have issues running fio on our shiny new aarch64 with 32 cores. 
I have some other aarch64 Cortex-A53 based boxes at home, on which fio runs just fine.   
Any clues?

[root@ceph-client01 ~]# lsb_release -d
Description:	CentOS Linux release 7.4.1708 (AltArch) 
[root@ceph-client01 ~]# uname -r
4.11.0-22.el7a.aarch64
**[root@ceph-client01 ~]# fio  --debug=file --direct=0 --name=randread --rw=randread --group_reporting --size 1M  --filename=/dev/sdc
fio: set debug option file
file     400513 dup files: 0
file     400513 add file /dev/sdc
file     400513 resize file array to 1 files
file     400513 file 0xffff82fd4910 "/dev/sdc" added at 0
randread: (g=0): rw=randread, bs=4K-4K/4K-4K/4K-4K, ioengine=sync, iodepth=1
fio-2.2.8
Starting 1 process
file     400513 setup files
file     400513 get file size for 0xffff82fd4910/0/0xffff82fd4a70
fio: 1 job failed to start

fio: terminating on signal 15**

Run status group 0 (all jobs):
[root@ceph-client01 ~]# lscpu 
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    1
Core(s) per socket:    16
Socket(s):             4
NUMA node(s):          4
Model:                 2
BogoMIPS:              100.00
L1d cache:             unknown size
L1i cache:             unknown size
L2 cache:              unknown size
NUMA node0 CPU(s):     0-15
NUMA node1 CPU(s):     16-31
NUMA node2 CPU(s):     32-47
NUMA node3 CPU(s):     48-63
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
[root@ceph-client01 ~]#

**Comment by sitsofe** [comment] 2018-03-01 10:26
Such an old version of fio... we're up to 3.5 upstream so there could be issues that have gone on to be fixed.

Can you check dmesg and see if the OOM killer has been kicking in?

**Comment by fossxplorer** [comment] 2018-03-01 10:39
Ok. I installed fio 3.1 from https://koji.fedoraproject.org/koji/buildinfo?buildID=1011806 and still getting the same errors. Checked journal (systemd based init) and there is nothing obvious related to OOM.
[root@ceph-client01 ~]#  fio --debug=file --direct=0 --name=randread --rw=randread --group_reporting --size 1M --filename=/dev/sdc
fio: set debug option file
file     400611 dup files: 0
file     400611 add file /dev/sdc
file     400611 resize file array to 1 files
file     400611 file 0xffff99ef6930 "/dev/sdc" added at 0
randread: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.1
Starting 1 process
file     400611 setup files
file     400611 get file size for 0xffff99ef6930/0//dev/sdc
fio: 1 job failed to start

fio: terminating on signal 15
Jobs: 0 (f=0)

Run status group 0 (all jobs):
[root@ceph-client01 ~]# 

Anything else i can help with in order to debug this?

**Comment by sitsofe** [comment] 2018-03-01 11:00
Try a run as above with --debug=all --thread and attach the output as a file here...

**Comment by fossxplorer** [comment] 2018-03-01 11:08
[fiodebug.txt](https://github.com/axboe/fio/files/1770895/fiodebug.txt)

**Comment by sitsofe** [comment] 2018-03-01 11:36
Of course that attempt would go on to work without issue allowing the cause of the problem to remain elusive...

Can you run ipcs and see if you have a large number of shm segments allocated?

**Comment by fossxplorer** [comment] 2018-03-01 12:26
[root@ceph-client01 ~]# ipcs

------ Message Queues --------
key        msqid      owner      perms      used-bytes   messages    

------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status      
0x00000000 0          root       600        111599620  16         dest         
0x00000000 32769      root       600        111599620  16         dest         
0x00000000 65538      root       600        111599620  2          dest         
0x00000000 98307      root       600        111599620  2          dest         
0x00000000 163844     root       600        111599620  2          dest         
0x00000000 196613     root       600        111599620  2          dest         
0x00000000 229382     root       600        111599620  2          dest         
0x00000000 262151     root       600        111599620  2          dest         
0x00000000 294920     root       600        111599620  2          dest         
0x00000000 327689     root       600        111599620  2          dest         
0x00000000 360458     root       600        111599620  2          dest         
0x00000000 393227     root       600        111599620  2          dest         
0x00000000 425996     root       600        111599620  2          dest         
0x00000000 458765     root       600        111599620  2          dest         
0x00000000 491534     root       600        111599620  2          dest         
0x00000000 524303     root       600        111599620  2          dest         
0x00000000 557072     root       600        111599620  2          dest         
0x00000000 589841     root       600        111599620  2          dest         
0x00000000 622610     root       600        263651332  8          dest         
0x00000000 655379     root       600        263651332  1          dest         
0x00000000 688148     root       600        263651332  1          dest         
0x00000000 720917     root       600        263651332  1          dest         
0x00000000 753686     root       600        263651332  1          dest         
0x00000000 786455     root       600        263651332  1          dest         
0x00000000 819224     root       600        263651332  1          dest         
0x00000000 851993     root       600        263651332  1          dest         
0x00000000 884762     root       600        263651332  1          dest         
0x00000000 917531     root       600        263651332  1          dest         
0x00000000 950300     root       600        263651332  1          dest         
0x00000000 1245213    root       600        263651332  1          dest         
0x00000000 1277982    root       600        263651332  1          dest         
0x00000000 1310751    root       600        263651332  1          dest         
0x00000000 1376288    root       600        263651332  1          dest         

------ Semaphore Arrays --------
key        semid      owner      perms      nsems     

[root@ceph-client01 ~]#

**Comment by sitsofe** [comment] 2018-03-01 13:11
Hmm that looks suspicious but I don't know what other programs you have running on your system and those segments might belong to them so the following is only a guess:

When running in "process mode" fio needs to allocate a region of shared memory so that it can pass information back and fore between the parent and the child jobs. Unfortunately if fio exits abruptly (e.g. you kill -9 it, it crashes etc) the region of memory isn't deallocated and remains until shutdown or its manually cleaned and each time you start fio it allocates another one of these regions. Over time this can cause a system to either run out of shared memory (there are usually limits on it) or even run out of regular memory. "Thread mode" fio doesn't need to allocate this region so it doesn't suffer this problem.

Back in https://github.com/axboe/fio/commit/97900ebfb0192130823dce8aa8f36916313a1c18 code was added that allows Linux to remove the shared region if fio hasn't cleaned it up when it entirey exits but said code only went in at fio 2.18...

Summary: If the above is right, the easiest thing to do is reboot that system but if you know what you're doing you can use ipcrm to clean up the shared segments.

**Comment by sitsofe** [comment] 2018-03-01 13:21
Actually I notice that there is something that is attached to all those segments. Could you run
`ipcs -lm`
and say what the output is?

**Comment by sitsofe** [comment] 2018-03-03 14:39
@fossxplorer - did you manage to solve this and if so could you close this issue? Thanks!

**Comment by fossxplorer** [comment] 2018-03-06 13:36
Sorry for the @sitsofe 
Since i'm running fio 3.1, i assume i should be "fine" with regard to cleanup of shared region of the used memory by fio?
Additionally, this issue can be reproduced among multiple other aarch64 systems i have access to. 
 
[root@ceph-client01 ~]# ipcs -lm

------ Shared Memory Limits --------
max number of segments = 4096
max seg size (kbytes) = 18014398509465599
max total shared memory (kbytes) = 18014397435740096
min seg size (bytes) = 1

[root@ceph-client01 ~]#

**Comment by sitsofe** [comment] 2018-03-06 14:46
@fossxplorer 

> Since i'm running fio 3.1, i assume i should be "fine" with regard to cleanup of shared region of the used memory by fio?

Yes.

> Additionally, this issue can be reproduced among multiple other aarch64 systems i have access to.

Gah the problem continues! OK...

1. Does running
   ```
   fio --thread  --name=randread --rw=randread --size=1M --filename=/dev/sdc
   ```
   always work for you?

2. If so can you attach the output of running
   ```
   fio --debug=all --name=randread --rw=randread --size=1M --filename=/dev/sdc
   ```
   and attach the result of that like you did before.

Thanks!

**Comment by axboe** [comment] 2018-03-06 19:59
I tried this on a bunch of different aarc64 boxes (40-120 threads) and wasn't able to trigger any issues, fwiw.

**Comment by sitsofe** [comment] 2018-03-12 10:08
@fossxplorer any follow up to the previous questions? If not could you close this issue? Thanks!

**Comment by fossxplorer** [comment] 2018-03-13 08:56
@sitsofe 
1. No, it fails as i've written earlier.
2. Attached.

@axboe Hmm, yeah i have some Cortex-A53 boxes at home where fio works just fine. So i find this issue strange indeed.
[fiodebug2.txt](https://github.com/axboe/fio/files/1806137/fiodebug2.txt)

**Comment by sitsofe** [comment] 2018-03-13 14:53
@fossxplorer I don't believe it - that debug run ran to happy completion too. Just to check when you use `--debug=all` does it look like everything works?

**Comment by fossxplorer** [comment] 2018-03-13 14:57
[root@ceph-client01 ~]# fio --thread  --name=randread --rw=randread --size=1M --filename=/dev/sdc
randread: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.1
Starting 1 thread
fio: 1 job failed to start

fio: terminating on signal 15

fio: terminating on signal 15
Jobs: 0 (f=0)

Run status group 0 (all jobs):
[root@ceph-client01 ~]#

**Comment by sitsofe** [comment] 2018-03-13 16:06
@fossxplorer Hmm there's got to be a way to smuggle some more clues out of this scenario. Can you start with
```
fio --thread --debug=process,file,io,mem,blktrace,verify,all,random,parse,diskutil,mutex,profile,time,net,rate,compress --thread --name=randread --rw=randread --size=1M --filename=/dev/sdc
```

and remove debug options from either end until it looks like the terminating on signal 15 error is happening again?

**Comment by fossxplorer** [comment] 2018-03-13 17:02
So i started to remove the --debug options from left to right, and after removing mutex (in addition to the rest on the left ofc) i got something like:
 [root@ceph-client01 ~]# fio --thread --debug=profile,time,net,rate,compress --thread --name=randread --rw=randread --size=1M --filename=/dev/sdc
fio: set debug option profile
fio: set debug option time
fio: set debug option net
fio: set debug option rate
fio: set debug option compress
randread: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.1
time     409048 gettime: clocksource=2
Starting 1 thread
fio: 1 job failed to start

fio: terminating on signal 15

fio: terminating on signal 15
Jobs: 0 (f=0)

Run status group 0 (all jobs):
profile  409048 unregister profile 'act'
profile  409048 unregister profile 'tiobench'
[root@ceph-client01 ~]#

**Comment by sitsofe** [comment] 2018-03-13 18:07
@fossxplorer Hmm so does
```
fio --thread --debug=mutex --thread --name=randread --rw=randread --size=1M --filename=/dev/sdc
```

not hit the issue?

**Comment by fossxplorer** [comment] 2018-03-13 19:33
Not that my eyes can see at least:
[root@ceph-client01 ~]# fio --thread --debug=mutex --thread --name=randread --rw=randread --size=1M --filename=/dev/sdc
fio: set debug option mutex
randread: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.1
mutex    409086 wait on startup_mutex
mutex    409086 done waiting on startup_mutex
Starting 1 thread
mutex    409086 wait on startup_mutex
mutex    409086 up startup_mutex
mutex    409086 wait on td->mutex
mutex    409086 done waiting on startup_mutex
mutex    409086 done waiting on td->mutex

randread: (groupid=0, jobs=1): err= 0: pid=409088: Tue Mar 13 20:32:58 2018
   read: IOPS=0, BW=0B/s (0B/s)(1024KiB/4850968455msec)
    clat (nsec): min=12033P, max=12033P, avg=12033343467665756160.00, stdev= 0.00
     lat (nsec): min=12033P, max=12033P, avg=12033343467665756160.00, stdev= 0.00
    clat percentiles (msec):
     |  1.00th=[17113],  5.00th=[17113], 10.00th=[17113], 20.00th=[17113],
     | 30.00th=[17113], 40.00th=[17113], 50.00th=[17113], 60.00th=[17113],
     | 70.00th=[17113], 80.00th=[17113], 90.00th=[17113], 95.00th=[17113],
     | 99.00th=[17113], 99.50th=[17113], 99.90th=[17113], 99.95th=[17113],
     | 99.99th=[17113]
  lat (msec)   : >=2000=100.00%
  cpu          : usr=0.00%, sys=0.00%, ctx=0, majf=0, minf=0
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwt: total=256,0,0, short=0,0,0, dropped=0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=0B/s (0B/s), 0B/s-0B/s (0B/s-0B/s), io=1024KiB (1049kB), run=4850968455-4850968455msec
[root@ceph-client01 ~]#

**Comment by axboe** [comment] 2018-03-13 20:15
Might be interesting to see where the process that fails to start is stuck. You could change the:

```kill(td->pid, SIGTERM);```

in backend.c, line 2412 to a:

```printf("pid %d failed to start\n", td->pid);```

and then keep fio running and do a gdb -p on the listed pid. Then paste the backtrace here.

**Comment by axboe** [comment] 2018-03-13 20:29
I wonder if this makes a difference at all.

[runstate-sync.txt](https://github.com/axboe/fio/files/1808550/runstate-sync.txt)

**Comment by sitsofe** [comment] 2018-03-13 21:05
@axboe I admit I was wondering that too - valgrind's helgrind was complaining that it wasn't being properly synchronized...

**Comment by bvanassche** [comment] 2018-03-13 21:14
Jens, with the runstate-sync.txt patch, are you perhaps referring to the data races reported by thread checking tools on global variables? Such unsynchronized accesses are not necessarily a bug. That is why both Helgrind and DRD support client requests like ANNOTATE_BENIGN_RACE_SIZED().

**Comment by axboe** [comment] 2018-03-13 21:24
I haven't used tools, I was merely observing the symptoms and they are consistent with missing an update on that field. For most cases, it doesn't matter of ->runstate misses a transition. For job startup it does, however. Hence I was curious if the patch would make a difference.

**Comment by sitsofe** [comment] 2018-03-13 21:30
@fossxplorer Looks like we're going to need you build your own fio to test the impact of Jen's patch but don't worry, fio is an easy compile if you don't need many features.

**Comment by sitsofe** [comment] 2018-03-14 06:36
@fossxplorer 

By the way what happens if you make size much bigger e.g.
```
fio --thread --thread --name=randread --rw=randread --size=100M --filename=/dev/sdc
```

?

**Comment by fossxplorer** [comment] 2018-03-15 11:02
[root@ceph-client01 ~]# fio --thread --name=randread --rw=randread --size=100M --filename=/dev/sdc
randread: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.1
Starting 1 thread
randread: Laying out IO file (1 file / 100MiB)
fio: 1 job failed to start

fio: terminating on signal 15

fio: terminating on signal 15
Jobs: 0 (f=0)

Run status group 0 (all jobs):
[root@ceph-client01 ~]# 


Time capped these days, so i have to take the compile part later :(

**Comment by sitsofe** [comment] 2018-03-15 12:11
@fossxplorer BTW on this latest pass it doesn't look like the /dev/sdc block device existed so fio created a normal file called `/dev/sdc` inside `/dev/`. This may cause issues later...

**Comment by sitsofe** [comment] 2018-03-15 12:32
@fossxplorer without access to a machine demonstrating the problem, a backtrace at the point the things get stuck or the ability to test potential changes it's unlikely we're going to be able to get far with this one. Let's see how it goes for you time-wise over the next few weeks...

**Comment by sitsofe** [comment] 2018-04-24 07:41
@fossxplorer any luck gathering more information on this one or should we close this for now?

**Comment by sitsofe** [comment] 2018-05-27 06:33
Closing this issue for now because we'd need more information from the reporter to take it further. @fossxplorer - please re-open this issue if/when you're able to do more debugging. Thank you!

**Closed by sitsofe** 2018-05-27 06:33 UTC
