### ISSUE TITLE
Need your help for verify data after power cycle

### ISSUE THREAD

**Issue by ZongWenqian** [axboe/fio#961] opened 2020-04-15 02:37 UTC
Dear Sir.
I want to do a test（use trigger-timeout and trigger-cmd to trigger SSD(solid state disk) reboot in certain time(example:10 seconds), then verify the written data pattern after SSD power on again）
I send fio write command as below:
fio --name=sdb --filename=/dev/sdb --size=100g --rw=write --ioengine=libaio --trigger='python3 ptsPowerOff.py --portId 1' --trigger-timeout=10 --offset=0G --verify=md5 --do_verify=0 --verify_backlog=500K  
'python3 ptsPowerOff.py --portId 1’ is a method to control SSD power down and power on.

I send fio read command as below:
fio --name=sdb --filename=/dev/sdb --size=100g --rw=read --ioengine=libaio --verify_state_load=1 --verify=md5 --do_verify=1 --verify_dump=1 --offset=0G --verify_backlog=500K
But while doing read, will report error information as below:
××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××
“fio --name=sdb --filename=/dev/sdb --size=100g --rw=read --verify_state_load=1 --verify=md5 --do_verify=1 --verify_dump=1 --offset=0G --verify_backlog=500K
command: fio --name=sdb --filename=/dev/sdb --size=100g --rw=read --verify_state_load=1 --verify=md5 --do_verify=1 --verify_dump=1 --offset=0G --verify_backlog=500K error, return:sdb: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.1
Starting 1 process
verify: bad magic header e3e8, wanted acca at file /dev/sdb offset 5940518912, length 4096
       hdr_fail data dumped as sdb.5940518912.hdr_fail
fio: pid=7058, err=84/file:io_u.c:1991, func=io_u_sync_complete, error=Invalid or incomplete multibyte or wide character

sdb: (groupid=0, jobs=1): err=84 (file:io_u.c:1991, func=io_u_sync_complete, error=Invalid or incomplete multibyte or wide character): pid=7058: Wed Apr  8 11:42:10 2020
  read: IOPS=123k, BW=482MiB/s (506MB/s)(5665MiB/11745msec)
    clat (nsec): min=536, max=716237, avg=2278.35, stdev=13511.52
     lat (nsec): min=565, max=716829, avg=2307.96, stdev=13511.34
    clat percentiles (nsec):
     |  1.00th=[   564],  5.00th=[   580], 10.00th=[   588], 20.00th=[   588],
     | 30.00th=[   596], 40.00th=[   596], 50.00th=[   596], 60.00th=[   604],
     | 70.00th=[   604], 80.00th=[   612], 90.00th=[   636], 95.00th=[   732],
     | 99.00th=[ 98816], 99.50th=[102912], 99.90th=[158720], 99.95th=[162816],
     | 99.99th=[166912]
   bw (  KiB/s): min=490736, max=495336, per=100.00%, avg=494468.87, stdev=923.36, samples=23
   iops        : min=122684, max=123836, avg=123617.22, stdev=231.04, samples=23
  lat (nsec)   : 750=95.40%, 1000=2.93%
  lat (usec)   : 2=0.05%, 4=0.05%, 10=0.01%, 20=0.01%, 50=0.01%
  lat (usec)   : 100=0.69%, 250=0.87%, 500=0.01%, 750=0.01%
  cpu          : usr=73.60%, sys=10.58%, ctx=22695, majf=0, minf=77
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=
××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××××
**Questions:**
1.	Why I meet this error information? Is there something wrong in my parameters?
2.	If I want to do test (when fio is writing, do asyn power, then power on, read back written data before power cycle, expect can verify written data integrity), can fio do this kind of test?
Looking forward for your reply.
Thanks a lot in advance.

Best Regards
ZongWenqian

**Comment by sitsofe** [comment] 2020-04-15 06:15
I'm going to close this as a duplicate of #962 as I've started replying there and it's essentially the same question.

**Closed by sitsofe** 2020-04-15 06:15 UTC
