### ISSUE TITLE
FIO tool requests size on time based analysis in versions past v2.1.6

### ISSUE THREAD

**Issue by truthbrown** [axboe/fio#230] opened 2016-08-19 17:34 UTC
Historically my team has used fio v2.1 to evaluate PCIe flash performance on 4 socket servers running  RHEL 6.x & RHEL 7.x. Recently we updated to v2.13 and noticed that there was a significant performance degradation across many tests. Through additional testing we have determined that running multiple jobs (numjobs=4) causes an issue where the tool requests size to be specified with time based evaluations. Also we have determined that the issue does not show itself in fio versions 2.1-2.1.5 but does in versions 2.1.6-2.13. 

Below I've included the job file, parameters, and terminal output of my A/B testing of versions v2.1 vs v2.13. Am I doing something wrong? Has anything changed with how jobfiles need to be constructed with the newer versions of fio? 

**How I'm passing parameters to the jobfile:**

~~~~~~~~~~~~~
BLKSIZE=4K DEPTH=16 RUN_T=45 JOBS=4 fio raw_fusion_fioa_RW.fio;
~~~~~~~~~~~~~

**Random Write jobfile used for both versions (v2.1 & v2.13):**

 ~~~~~~~~~~~~~
[global]
rw=randwrite            
# size=10000m        	
blocksize=${BLKSIZE}    
blockalign=${BLKSIZE}   
iodepth=${DEPTH}        
ioengine=libaio         
# iodepth_batch=16       
# iodepth_batch_complete=0 
direct=1                 
norandommap=1            
randrepeat=0             
# ramp_time=15            
time_based=1             
runtime=${RUN_T}s		 
numjobs=${JOBS}         

 ### Book Pinning ###
#--------------------#
[/dev/fiod]
numa_cpu_nodes=3
 ~~~~~~~~~~~~~

**fio v2.1 Random Write Terminal Output**

~~~~~~~~~~~~~
/dev/fiod: (g=0): rw=randwrite, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=4
...
/dev/fiod: (g=0): rw=randwrite, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=4
fio-2.1
Starting 4 processes
Jobs: 4 (f=4): [wwww] [100.0% done] [0KB/1354MB/0KB /s] **[0/347K/0 iops]** [eta 00m:00s]
	/dev/fiod: (groupid=0, jobs=1): err= 0: pid=28488: Fri Aug 19 00:55:50 2016
	  write: io=15232MB, bw=346601KB/s, iops=86650, runt= 45001msec

	  ... extra data removed for clarity ... 
	 
	/dev/fiod: (groupid=0, jobs=1): err= 0: pid=28489: Fri Aug 19 00:55:50 2016
	  write: io=15224MB, bw=346414KB/s, iops=86603, runt= 45001msec

	  ... extra data removed for clarity ... 
	 
	/dev/fiod: (groupid=0, jobs=1): err= 0: pid=28490: Fri Aug 19 00:55:50 2016
	  write: io=15241MB, bw=346817KB/s, iops=86704, runt= 45001msec

	  ... extra data removed for clarity ... 
	 
	/dev/fiod: (groupid=0, jobs=1): err= 0: pid=28491: Fri Aug 19 00:55:50 2016
         write: io=15232MB, bw=346598KB/s, iops=86649, runt= 45001msec

	  ... extra data removed for clarity ... 

Run status group 0 (all jobs):
  WRITE: io=60928MB, aggrb=1353.1MB/s, minb=346414KB/s, maxb=346816KB/s, mint=45001msec, maxt=45001msec

Disk stats (read/write):
  fiod: ios=56/15572235, merge=0/0, ticks=4/593462, in_queue=600752, util=100.00%
~~~~~~~~~~~~~

**fio v2.13 Random Write Terminal Output**

~~~~~~~~~~~~~
/dev/fiod: (g=0): rw=randwrite, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=4
...
fio-2.13
Starting 4 processes
/dev/fiod: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:833, func=total_file_size, error=Invalid argument
/dev/fiod: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:833, func=total_file_size, error=Invalid argument
/dev/fiod: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:833, func=total_file_size, error=Invalid argument

Jobs: 1 (f=1): [w(1),X(3)] [100.0% done] [0KB/746.7MB/0KB /s] **[0/191K/0 iops]** [eta 00m:00s]
	/dev/fiod: (groupid=0, jobs=1): err= 0: pid=12986: Fri Aug 19 00:40:32 2016
	  write: io=33860MB, bw=770487KB/s, iops=192621, runt= 45001msec

	  ... extra data removed for clarity ... 

Run status group 0 (all jobs):
  WRITE: io=33860MB, aggrb=770487KB/s, minb=770487KB/s, maxb=770487KB/s, mint=45001msec, maxt=45001msec

Disk stats (read/write):
  fiod: ios=39/8649782, merge=0/0, ticks=9/121982, in_queue=122755, util=100.00%

~~~~~~~~~~~~~

**Comment by axboe** [comment] 2016-08-19 18:47
Since you already did a great job in isolating where the problem started, it'd be great if you could run a git bisect to pinpoint the actual change. Something ala:

$ git bisect start
$ git bisect good fio-2.1.5
$ git bisect bad fio-2.1.5

then for each iteration, make clean && make and run the test case. If behaves as it should, git bisect good, if not, git bisect bad. You only need about 5 iterations, so should not take long. At the end of it, git will tell you what commit caused the bad behavior.

Thanks in advance, and let me know if you have any questions.

**Comment by truthbrown** [comment] 2016-08-22 19:04
Thank you for the quick response, but I have an issue implementing your suggestion. The system I'm testing is completely isolated from the Internet; therefore my method of installing FIO onto it is by transferring the zip folder from my laptop via a secure connection. And based on my research I won't be able to effectively execute the git bisect command on my machine. 

Despite the above limitation, I've isolated that release v2.1.6 is where the issues being. I performed a diff between release v2.1.5 and v2.1.6 and the file differences are as follows.  

**Files that were modified in fio v2.1.6**
~~~~~~~~~~~~~
arch-x86-common.h
backend.c
blktrace.c
cconv.c
compiler.h
configure
err.h
eta.c
file.h
filesetup.c
fio.1
fio.h
FIO-VERSION-GEN
gettime.c
goptions.c
HOWTO
init.c
install.wxs
io_u.c
io_u_queue.h
ioengine.h
ioengines.c
iolog.c
iolog.h
lfsr.c
libfio.c
Makefile
net.c
null.c
options.c
options.h
os.h
os-freebsd.h
os-linux.h
os-solaris.h
os-windows.h
parse.c
parse.h
server.c
server.h
stat.c
stat.h
test.c
thread_options.h
time.c
time.h
tiobench.c
verify.c
verify.h
~~~~~~~~~~~~~





**Files only existing in fio v2.1.6**
~~~~~~~~~~~~~
xxhash.c
xxhash.h
rbd.c
rbd.fio
~~~~~~~~~~~~~

**Comment by axboe** [comment] 2016-08-22 20:31
You don't have git on the target system? You don't need internet connectivity to perform the bisect, you just need to be able to rebuild fio between the test runs. I already looked at the log and diff between 2.1.5 and 2.1.6, and nothing sticks out. Hence the need for a bisection...

**Comment by axboe** [comment] 2016-08-22 20:47
BTW, you could also run the bisect on the box you are currently using to copy fio to the test system. Same procedure, see below. I'm using `test` as the 4-socket hostname, `workstation` as the hostname for the box you are currently using to transfer fio from.

`workstation: $ git bisect start`
`workstation: $ git bisect good fio-2.1.5`
`workstation: $ git bisect bad fio-2.1.6`
```Bisecting: 27 revisions left to test after this (roughly 5 steps)
[51c8c3701e2b041788d1d1e650a9a18a56c09f20] server: bump protocol version```
`workstation: $ make clean; make -j8`

Now scp the result to `test` and run the test. If it's slow, run

`workstation: $ git bisect bad`

and if it's fast, run

`workstation: $ git bisect good`

Then do 

`workstation: $ make clean; make -j8`

and copy fio over to the test box again, re-run the test, and input git bisect bad/good once more. Repeat for 4-5 iterations, and git on `workstation` will tell you which commit caused the slowdown.

If you build fio on `test`, then just tar+scp the fio directory after running the git bisect good/bad command each time and build it on that box. It doesn't matter, as long as you keep the source/binary in sync and do it after each iteration of git bisect good/bad.

Hope this helps!

**Comment by truthbrown** [comment] 2016-08-25 00:29
For future readers a breakdown of my issue with the "git bisect" command: 

My local machine is running Windows 7 and didn't have a git client installed.  Also by only utilizing 
the zip download to install fio on the device under test, I didn't have the repository cloned on my local machine. Once I downloaded a git client and cloned the repository I was able to run the command 
as demonstrated above. The only change I did was download each revision directly from github using the following:  https:// github.com / {username} / {project name} /archive/ <sha>.zip

**Comment by truthbrown** [comment] 2016-08-25 00:36
To axobe: 

I was able to get the bisect command working and this is what was reported back to me. Your thoughts? 

~~~~~~~~~
< workstation > ~/Downloads/fio_versions/fio_master (master)
$ git bisect start

< workstation > ~/Downloads/fio_versions/fio_master (master|BISECTING)
$ git bisect good fio-2.1.5

< workstation > ~/Downloads/fio_versions/fio_master (master|BISECTING)
$ git bisect bad fio-2.1.6
Bisecting: 27 revisions left to test after this (roughly 5 steps)
[51c8c3701e2b041788d1d1e650a9a18a56c09f20] server: bump protocol version

< workstation > ~/Downloads/fio_versions/fio_master ((51c8c37...)|BISECTING)
$ git bisect bad
Bisecting: 13 revisions left to test after this (roughly 4 steps)
[b74b8208826be02d93d0933eb24ad792f4e78f64] Fix inverted logic in gtod_reduce()

< workstation > ~/Downloads/fio_versions/fio_master ((b74b820...)|BISECTING)
$ git bisect good
Bisecting: 6 revisions left to test after this (roughly 3 steps)
[56e2a5fc76067c91738f7eb0efbd6ec6d349e0f2] fio: allow general repeatability

< workstation > ~/Downloads/fio_versions/fio_master ((56e2a5f...)|BISECTING)
$ git bisect good
Bisecting: 3 revisions left to test after this (roughly 2 steps)
[bcbfeefa7bce8383cf85fe59ced91f54821dfbd2] fio: add multi directory support

< workstation > ~/Downloads/fio_versions/fio_master ((bcbfeef...)|BISECTING)
$ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 1 step)
[23ed19b0e10749dca2389511f78d89db886c064a] fio: provide an option for a startdelay range

< workstation > ~/Downloads/fio_versions/fio_master ((23ed19b...)|BISECTING)
$ git bisect good
bcbfeefa7bce8383cf85fe59ced91f54821dfbd2 is the first bad commit
commit bcbfeefa7bce8383cf85fe59ced91f54821dfbd2
Author: Christian Ehrhardt <ehrhardt@linux.vnet.ibm.com>
Date:   Thu Feb 20 09:13:06 2014 -0800

    fio: add multi directory support

    This patch adds support for ':' seperated multiple directories at the
    directory config statement in order to achieve an automatic distribution
    of job clones (numjob) across directories.

    That way people can distribute a load across these directories (usually
    mount points of disks) automatically - changing numjob will be
    sufficient to get all job clones evenly (optimal if dirs % numjobs = 0,
    otherwise as good as possible) distributed at all times.

    To avoid confused users old config Files will behave like they always
    did, old fio binaries using new config files won't abort but just use
    the first specified dir. If one specifies an explcit (non generated)
    filename the distribution to many directories is also deactivated.

    It also fixes an issue of events seeming out of order like when running
    with --debug=file seeing the "..." message meaning "I created the
    clones" prior to the last clone activities.  Now the clones are called
    with index N-1 .. 1, zero being the base thread as before.

    Signed-off-by: Christian Ehrhardt <ehrhardt@linux.vnet.ibm.com>
    Signed-off-by: Jens Axboe <axboe@fb.com>

:040000 040000 284c92f28a9b8cb598b77eb12e200456dd79f84e e12b1cf5b981d22e6ab6f72afdd2e5ff9e4ec1f6 M      engines
:100644 100644 c1d02a5bea57add8d9049aad117fb91592740459 d065a25096447e00cb218382c83e6458038d4b55 M      file.h
:100644 100644 544ecb1c53dce5f336faf3294c0acfc75ace53e3 f0e3b34fd8ae1e90424c04a37ec1cba4b71e4a38 M      filesetup.c
:100644 100644 2320ba341fc5efdf839afb350981f185a3906327 1f3f4dd6b39af7241827fba2a918977af5ae2560 M      fio.1
:100644 100644 9d3c960870a89e0412094b5d5ee4ba6754462061 7f8b3178ebd26f36e47c434dbcf035a6b8ceac28 M      init.c
:100644 100644 5fd9416c036ec2454030b4ddf6772eab487efa30 eeaca291e21eb6503712f29a602ca5ad121a2615 M      iolog.c
:100644 100644 5b97ec413aae0ba43d8f911ccfda8dc24397553f 04fb506a6e9cfffd234e0b898eee08e600cb81c2 M      options.c
:100644 100644 3dc48a9788ab073a811bc29c78b26a0f65c4a4dc de9f6109fa1b474e72a1b60df667f99f7455735d M      options.h

< workstation > ~/Downloads/fio_versions/fio_master ((23ed19b...)|BISECTING)
$
~~~~~~~~~

**Comment by axboe** [comment] 2016-08-25 02:31
Any chance you can try and run that again? Doesn't seem related at all. How confident are you in your good/bad decisions along the way?

**Comment by truthbrown** [comment] 2016-08-26 00:10
Yes I am confident in my good/bad git bisect decisions along the way. But to make sure I reran everything from scratch and confirmed my previous results. I have attached three log files of what I did in each terminal. 

I’m not sure how to fully interrupt the git bisect results but I believe the delta in is performance related to the numjobs parameter. When I run a time based analysis and set numjobs to greater than 1, the errors below are reported. Based on the terminal output I assume the tool is only executing the first job and not the additional three. Am I doing something wrong with my job file? 




**How I'm passing parameters to the jobfile:**
~~~~~~~~~~~~~
BLKSIZE=4K DEPTH=16 RUN_T=30 JOBS=4 fio raw_fusion_fioa_RR.fio;
~~~~~~~~~~~~~


**Random Read jobfile used for git bisect evaluations:**
 ~~~~~~~~~~~~~
[global]
rw=randread              
# size=10G        		 
blocksize=${BLKSIZE}     
blockalign=${BLKSIZE}    
iodepth=${DEPTH}         
ioengine=libaio          
# iodepth_batch=16        
# iodepth_batch_complete=0 
direct=1                 
norandommap=1            
randrepeat=0             
# ramp_time=15            
time_based=1             
runtime=${RUN_T}s		 
numjobs=${JOBS}         

 ### Book 1 Pinning ###
#--------------------#
[/dev/fiod]
numa_cpu_nodes=3
 ~~~~~~~~~~~~~




**Reported error that correlates with poor performance:** 

~~~~~
/dev/fiod: (g=0): rw=randread, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=16
...
fio-2.1.5
Starting 4 processes
/dev/fiod: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:789, func=total_file_size, error=Invalid argument
/dev/fiod: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:789, func=total_file_size, error=Invalid argument
/dev/fiod: you need to specify size=
fio: pid=0, err=22/file:filesetup.c:789, func=total_file_size, error=Invalid argument

Jobs: 1 (f=1): [rXXX] [100.0% done] [400.7MB/0KB/0KB /s] [102K/0/0 iops] [eta 00m:00s]
/dev/fiod: (groupid=0, jobs=1): err= 0: pid=122769: Thu Aug 25 13:37:59 2016
  read : io=12072MB, bw=412033KB/s, iops=103008, runt= 30001msec

  	... extra data removed for clarity ... 
  
Run status group 0 (all jobs):
   READ: io=12072MB, aggrb=412033KB/s, minb=412033KB/s, maxb=412033KB/s, mint=30001msec, maxt=30001msec

Disk stats (read/write):
  fiod: ios=3075257/0, merge=0/0, ticks=442644/0, in_queue=445465, util=100.00%
~~~~~


**Terminal output of a successful run with proper performance:** 

~~~~~
/dev/fiod: (g=0): rw=randread, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=16
...
/dev/fiod: (g=0): rw=randread, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=16
fio-2.1.5
Starting 4 processes
Jobs: 4 (f=4): [rrrr] [100.0% done] [453.7MB/0KB/0KB /s] [116K/0/0 iops] [eta 00m:00s]
/dev/fiod: (groupid=0, jobs=1): err= 0: pid=125713: Thu Aug 25 13:43:29 2016
  read : io=3404.5MB, bw=116200KB/s, iops=29049, runt= 30001msec
		
		... extra data removed for clarity ... 
	
/dev/fiod: (groupid=0, jobs=1): err= 0: pid=125714: Thu Aug 25 13:43:29 2016
  read : io=3405.6MB, bw=116239KB/s, iops=29059, runt= 30001msec
		
		... extra data removed for clarity ... 
	
/dev/fiod: (groupid=0, jobs=1): err= 0: pid=125715: Thu Aug 25 13:43:29 2016
  read : io=3403.2MB, bw=116158KB/s, iops=29039, runt= 30001msec
		
		... extra data removed for clarity ... 
	
/dev/fiod: (groupid=0, jobs=1): err= 0: pid=125716: Thu Aug 25 13:43:29 2016
  read : io=3403.5MB, bw=116168KB/s, iops=29042, runt= 30001msec
		
		... extra data removed for clarity ... 
	
Run status group 0 (all jobs):
   READ: io=13617MB, aggrb=464764KB/s, minb=116158KB/s, maxb=116238KB/s, mint=30001msec, maxt=30001msec

Disk stats (read/write):
  fiod: ios=3474256/0, merge=0/0, ticks=1884856/0, in_queue=1904235, util=100.00%

~~~~~

**Comment by axboe** [comment] 2016-08-26 03:03
Ah, now it makes sense. It's not a fio slowdown, it's simply not running jobs 2 and on. This is a regression introduced by the commit you found, if you use jobname as the filename. Can you try current -git? I committed a fix for it:

http://git.kernel.dk/cgit/fio/commit/?id=04d6530f6ecd50520e99732b0b6bb90f71ff131a

**Comment by truthbrown** [comment] 2016-08-26 14:30
Awesome !!! Pulled it down this morning and everything is working as it should. I really appreciate you taking the time to help me work through this issue. Take care and have a great weekend.

**Comment by axboe** [comment] 2016-08-26 14:39
Perfect! Thanks for reporting, and taking the time to do the bisect. I never would have found this issue without that, since I completely missed that 3 out of the 4 jobs simply didn't start.

**Closed by axboe** 2016-08-26 14:39 UTC
