### ISSUE TITLE
Incorrect log was generated when using the write_iolog in the FIO version fio-3.24

### ISSUE THREAD

**Issue by wangyihanlarry** [axboe/fio#1139] opened 2020-11-30 13:14 UTC
Greetings, 

I am trying to create a bitmap against the FIO log files generated by running FIO with switch write_iolog, and I saw two issues by using this featue on the latest FIO version, please check my steps in bleow,

1, install FIO 3.24
```
[root@TENCENT64 /tmp]# rpm -ivh fio-3.24-1.tl2.x86_64.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:fio-3.24-1.tl2                   ################################# [100%]

[root@TENCENT64 /tmp]# fio --version
fio-3.24
```
2,  Create a FIO profile to write IO to two 1G volumes
```
[root@TENCENT64 ~/FIO_Profiles]# vi fio_profile.fio 
[global]
            exitall_on_error=1
            write_iolog=/tmp/testlarrry
            invalidate=1
            direct=1
            allow_file_create=0
            refill_buffers=1
            group_reporting
            iodepth_batch_submit=2
            iodepth=16
[sdfd-1G-comp69%]
filename=/dev/sdfd
size=1G
bsrange=8k-256k
do_verify=1
verify=crc32c
verify_fatal=1
verify_dump=1
rw=randwrite
buffer_compress_percentage=69%
buffer_pattern=0x170d95bb

[sdfe-1G-comp45%]
filename=/dev/sdfe
size=1G
bsrange=8k-256k
do_verify=1
verify=crc32c
verify_fatal=1
verify_dump=1
rw=randwrite
buffer_compress_percentage=45%
buffer_pattern=0x79908874

[sdfd-1G-comp22%]
stonewall
filename=/dev/sdfd
size=20M
bsrange=4k-128k
do_verify=1
verify=crc32c
verify_fatal=1
verify_dump=1
rw=randwrite
buffer_compress_percentage=22%
buffer_pattern=0x9bae179c
buffer_compress_chunk=1k

[sdfe-1G-comp11%]
filename=/dev/sdfe
size=100M
bsrange=4k-128k
do_verify=1
verify=crc32c
verify_fatal=1
verify_dump=1
rw=randwrite
buffer_compress_percentage=11%
buffer_pattern=0xa8b9c72b
buffer_compress_chunk=2k


[root@TENCENT64 ~/FIO_Profiles]# fio fio_profile.fio 
sdfd-1G-comp69%: (g=0): rw=randwrite, bs=(R) 8192B-256KiB, (W) 8192B-256KiB, (T) 8192B-256KiB, ioengine=psync, iodepth=16
sdfe-1G-comp45%: (g=0): rw=randwrite, bs=(R) 8192B-256KiB, (W) 8192B-256KiB, (T) 8192B-256KiB, ioengine=psync, iodepth=16
sdfd-1G-comp22%: (g=1): rw=randwrite, bs=(R) 4096B-128KiB, (W) 4096B-128KiB, (T) 4096B-128KiB, ioengine=psync, iodepth=16
sdfe-1G-comp11%: (g=1): rw=randwrite, bs=(R) 4096B-128KiB, (W) 4096B-128KiB, (T) 4096B-128KiB, ioengine=psync, iodepth=16
fio-3.24
Starting 4 processes
Jobs: 1 (f=1): [_(3),V(1)][100.0%][r=88.1MiB/s,w=5332KiB/s][r=1897,w=154 IOPS][eta 00m:00s]
sdfd-1G-comp69%: (groupid=0, jobs=2): err= 0: pid=11059: Mon Nov 30 20:55:53 2020
  read: IOPS=3508, BW=319MiB/s (334MB/s)(2048MiB/6421msec)
    clat (usec): min=212, max=4637, avg=546.57, stdev=222.72
     lat (usec): min=213, max=4638, avg=547.53, stdev=222.72
    clat percentiles (usec):
     |  1.00th=[  273],  5.00th=[  318], 10.00th=[  351], 20.00th=[  392],
     | 30.00th=[  429], 40.00th=[  465], 50.00th=[  506], 60.00th=[  553],
     | 70.00th=[  611], 80.00th=[  685], 90.00th=[  783], 95.00th=[  865],
     | 99.00th=[ 1074], 99.50th=[ 1254], 99.90th=[ 3458], 99.95th=[ 3884],
     | 99.99th=[ 4359]
  write: IOPS=960, BW=87.3MiB/s (91.6MB/s)(2048MiB/23452msec); 0 zone resets
    clat (usec): min=754, max=32954, avg=1992.77, stdev=1487.46
     lat (usec): min=758, max=32990, avg=2031.19, stdev=1495.20
    clat percentiles (usec):
     |  1.00th=[  947],  5.00th=[ 1057], 10.00th=[ 1139], 20.00th=[ 1287],
     | 30.00th=[ 1434], 40.00th=[ 1565], 50.00th=[ 1713], 60.00th=[ 1876],
     | 70.00th=[ 2057], 80.00th=[ 2311], 90.00th=[ 2802], 95.00th=[ 4047],
     | 99.00th=[ 5276], 99.50th=[12387], 99.90th=[21103], 99.95th=[25560],
     | 99.99th=[31065]
   bw (  KiB/s): min=20160, max=111216, per=99.65%, avg=89111.93, stdev=7874.78, samples=87
   iops        : min=  306, max= 1128, avg=955.46, stdev=66.74, samples=87
  lat (usec)   : 250=0.14%, 500=24.25%, 750=19.27%, 1000=6.75%
  lat (msec)   : 2=33.00%, 4=13.95%, 10=2.35%, 20=0.23%, 50=0.06%
  cpu          : usr=3.32%, sys=0.83%, ctx=45090, majf=0, minf=636
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=22529,22529,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16
     sdfd-1G-comp22%: (groupid=1, jobs=2): err= 0: pid=12035: Mon Nov 30 20:55:53 2020
  read: IOPS=3046, BW=136MiB/s (143MB/s)(120MiB/881msec)
    clat (usec): min=206, max=4204, avg=384.40, stdev=171.42
     lat (usec): min=207, max=4205, avg=385.26, stdev=171.47
    clat percentiles (usec):
     |  1.00th=[  229],  5.00th=[  255], 10.00th=[  269], 20.00th=[  302],
     | 30.00th=[  322], 40.00th=[  343], 50.00th=[  359], 60.00th=[  383],
     | 70.00th=[  408], 80.00th=[  445], 90.00th=[  506], 95.00th=[  562],
     | 99.00th=[  709], 99.50th=[  914], 99.90th=[ 3130], 99.95th=[ 3294],
     | 99.99th=[ 4228]
  write: IOPS=668, BW=29.9MiB/s (31.4MB/s)(120MiB/4013msec); 0 zone resets
    clat (usec): min=784, max=30550, avg=1756.26, stdev=1438.97
     lat (usec): min=787, max=30587, avg=1775.70, stdev=1441.53
    clat percentiles (usec):
     |  1.00th=[  873],  5.00th=[  971], 10.00th=[ 1037], 20.00th=[ 1139],
     | 30.00th=[ 1254], 40.00th=[ 1369], 50.00th=[ 1500], 60.00th=[ 1598],
     | 70.00th=[ 1713], 80.00th=[ 1876], 90.00th=[ 2343], 95.00th=[ 4015],
     | 99.00th=[ 4686], 99.50th=[ 5735], 99.90th=[26084], 99.95th=[29230],
     | 99.99th=[30540]
   bw (  KiB/s): min=27640, max=59104, per=100.00%, avg=49971.56, stdev=8583.87, samples=10
   iops        : min=  578, max= 1172, avg=1061.56, stdev=173.88, samples=10
  lat (usec)   : 250=1.92%, 500=42.85%, 750=4.88%, 1000=3.48%
  lat (msec)   : 2=38.88%, 4=5.38%, 10=2.40%, 20=0.15%, 50=0.06%
  cpu          : usr=1.98%, sys=0.89%, ctx=5373, majf=0, minf=170
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=2684,2684,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
   READ: bw=319MiB/s (334MB/s), 319MiB/s-319MiB/s (334MB/s-334MB/s), io=2048MiB (2147MB), run=6421-6421msec
  WRITE: bw=87.3MiB/s (91.6MB/s), 87.3MiB/s-87.3MiB/s (91.6MB/s-91.6MB/s), io=2048MiB (2147MB), run=23452-23452msec

Run status group 1 (all jobs):
   READ: bw=136MiB/s (143MB/s), 136MiB/s-136MiB/s (143MB/s-143MB/s), io=120MiB (126MB), run=881-881msec
  WRITE: bw=29.9MiB/s (31.4MB/s), 29.9MiB/s-29.9MiB/s (31.4MB/s-31.4MB/s), io=120MiB (126MB), run=4013-4013msec

Disk stats (read/write):
  sdfd: ios=11555/11908, merge=438/0, ticks=5940/23656, in_queue=29596, util=95.63%
  sdfe: ios=13072/13294, merge=657/0, ticks=6884/26236, in_queue=33120, util=94.83%
```

3, upon the completion, use my program to generate a bit map in 1MB basis, below is my code:
```
import io
import re

temps = {}
bit_map = {}
with io.open('/root/1020/testlarrry', 'r') as temp:
    for line in temp.readlines():
        hit = re.search(r"/dev/(\S+)\s+write\s+(\d+)\s+(\d+)", line)
        if hit:
            dev_name = hit.group(1)
            offset = hit.group(2)
            length = hit.group(3)
            start_in_mb = int(offset)/1024/1024
            end_in_mb = (int(offset)+int(length))/1024/1024
            if (end_in_mb > 1024):
                print(start_in_mb)
                print(end_in_mb)
                print(offset)
                print(length)
            temps.setdefault(dev_name, {start_in_mb: end_in_mb})
            temps[dev_name].setdefault(start_in_mb, end_in_mb)

for key in temps.keys():
    # TODO: Key is the device number, we need firstly featch the size of device and then intitialze the bitmap list
    size = 1024
    init_bitmap = [0] * size
    enrtys = temps[key].keys()
    # TODO: walk through the entry to update the init_bitmap
    for entry in enrtys:
        end = temps[key][entry]
        init_bitmap[entry:end] = [1] * ((end - entry) + 1)
    bit_map.setdefault(key, init_bitmap)

pass

```

4th, Results:
1, there are several offsets which had exceed the max capacity of the volume,  in bleow:
```
line5551 /dev/sdfe write 1091010487040 147456
line 11885 /dev/sdfd write 514809856 4915021960192 65536 #there are 5 columns in this line

```

2, there are two write within one line, e,g.
```
/dev/sdfd write 1042ev/sdfe write 29212672 106496
```

I am attaching the original copy of the logfile in the ticket also, please check.
[testlarrry.txt](https://github.com/axboe/fio/files/5616082/testlarrry.txt)

**Comment by sitsofe** [comment] 2020-11-30 15:34
@wangyihanlarry Good to hear from you again :-)

First up, is it possible for you to reduce your job file to the minimum size that still reproduces the issue? For example, if you only have the `sdfe-1G-comp45%` section can you still reproduce the issue? Try to remove every option individually until you find out the set that is actually required (don't stop at the first option you remove that doesn't reproduce the issue - truly try and find the minimal set).

Secondly, does using a fixed block size still reproduce the issue with your minimal job file?

Second, could you use a randseed (https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-randseed ) so we can get a predictable ordering.

PS: `iodepth` style parameters don't make sense with synchronous ioengines (`[...] (W) 8192B-256KiB, (T) 8192B-256KiB, ioengine=*psync*`) - see https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-iodepth .

**Comment by sitsofe** [comment] 2020-11-30 15:50
Actually, isn't the fact you are using the same log file for multiple simultaneous jobs going to cause a problem?

Next question: what happens if you give each job a separate log file?

**Comment by sitsofe** [comment] 2020-12-02 07:40
@wangyihanlarry ping?

**Comment by wangyihanlarry** [comment] 2020-12-02 07:43
sorry，I was tied up by other works these days, I will reproduce it on tomorrow.

**Comment by sitsofe** [comment] 2020-12-23 07:18
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2020-12-23 07:18 UTC
Labels: needreporterinfo
