### ISSUE TITLE
deadlock between thread_main & helper_thread_main

### ISSUE THREAD

**Issue by zixuanhe** [axboe/fio#52] opened 2015-03-19 05:36 UTC
I am running into a deadlock with fio for the following lines: 

thread_main 
```
fio_mutex_down(stat_mutex) at backend.c:1529
```
helper_thread_main 
```
fio_mutex_down(td->rusage_sem) at stat.c:1467
```

thread_main is waiting for **stat_mutex**, which is already locked by helper_thread_main in function **__show_running_run_stats()** at stat.c:1441. However, the helper_thread_main is waiting for **td->rusage_sem**, which is supposed to be unlocked by **check_update_rusage()** in **do_io()** at backend.c:1525 in thread_main. 

The issue is not reproducible every time, and I was using a customized ioengine derived from rbd.c. 

Is there any chance that this issue is caused by the customized io engine? Or is there a way to get around this? 

Thanks. 

fio version 
commit f6facd21c027939f6ec3d376d294547c1db40e2d

**Comment by axboe** [comment] 2015-03-23 15:19
I don't think this is caused by your custom IO engine, it looks like a plain bug. Does it work if you add a check_rusage_update()  before the fio_mutex_down(stat_mutex)  near line 1529 of backend.c?

**Comment by zixuanhe** [comment] 2015-03-23 20:10
Adding check_rusage_update() before the fio_mutex_down(stat_mutex) on line 1529 of backend.c seems fixed the issue. 

FYI, the issue was encountered only when "--status-interval" was set before the fix. 

Thanks a lot.

**Comment by axboe** [comment] 2015-03-23 20:11
Thanks, I committed the fix, so current -git should be good. And yes, this situation will only occur if the status interval helper triggers. Thanks for reporting it!

**Closed** 2015-03-23 20:10 UTC
