### ISSUE TITLE
fio output intermittently scrambled when multiple --client options specified

### ISSUE THREAD

**Issue by jml9904** [axboe/fio#673] opened 2018-09-06 12:08 UTC
Running into an issue where output is interleaved among client/server runs. This is somewhat intermittent but has occurred across multiple fio versions. For example, starting two fio servers on a host (this is from a single host, but typically we see the problem when running servers on two separate hosts, and the client on a third):

fio --server, 8765
fio --server, 8766

and then running:

./fio --minimal --eta=never --client=xx.xx.xx.xx,8765 ./00test1.fio --client=xx.xx.xx.xx,8766 ./00test1.fio 

yields the following output:

hostname=gorgonzola, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.5-59-g7c54, flags=1
hostname=gorgonzola, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.5-59-g7c54, flags=1
<gorgonzola> 00-test1: (g=0): rw=randrw, <gorgonzola> 00-test1: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
ioengine=libaio, iodepth=64
<gorgonzola> Starting <gorgonzola> Starting 1 process1 process

3;fio-3.5-59-g7c54;00-test1;0;0;3208676;320835;80208;10001;2;71;3.275114;1.275014;8;7206;242.193155;305.997537;1.000000%=115;5.000000%=134;10.000000%=144;20.000000%=158;30.000000%=168;40.000000%
<... stats deleted for clarity ...>

Disk stats (read/write):
;nvme0n1;1584561;1583508;0;0;309780;781008;1100100;99.38%<gorgonzola> 
3;fio-3.5-59-g7c54;00-test1;0;0;3203416;320245;80061;10003;2;39;3.275121;1.244327;21;7556;241.026224;306.086266;1.000000%=114;5.000000%=132;10.000000%=144;20.000000%=156;30.000000%=168;40.000000%=179;50.000000%=189;60.000000%=199;70.000000%=214;80.000000%=232;90.000000%=26
<... stats deleted for clarity ...>

clients;0;0;6412092;641016;160254;10003;2;71;3.275121;0.879511;8;7556;241.026224;216.346815;0%=0;0%=0;0%=0;0%=0;0%=0;0%=0;0%=0;0%=0;0%=0;0%=0;0%=0;0%=0;0%=0;0%=0;0%=0;0%
<... stats deleted for clarity ...>

Disk stats (read/write):
;nvme0n1;1584570;1583514;0;0;309780;781008;1100100;99.38%<gorgonzola> 

The information at the head of the output is scrambled, and sometimes we get corruption within the body too, as in:

3;fio-3.5-45-g69b98f;All clients;0;0;280711168;20338441;4965;13802;99;2882701;16072.372432;73958.321310;2947;9798
<... stats deleted for clarity ...>
;5.5%;89.2%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.01%;0.10%;0.57%;3.06%;3.03%;12.69%;12.53%;10.44%;9.88%;0.00%;0.00%
;nvme2n1;55808;22944;0;0;5167415;2646201;7832048;64.34%;nvme16n1;54080;24672;0;0;13073942;6934592;20772754;67.79%
Disk stats (read/write):
;nvme19n1;53561;24219;0;0;106317193;49912036;186159849;97.82%;nvme13n1;53984;24768;0;0;7390954;4233313;11808161;66.83%;nvme8n1;53108;22066;0;0;10262887;4664063;15155532;61.38%;nvme14n1;55904;22848;0;0;7006908;3108602;10194615;64.81%;nvme10n1;52904;22270;0;0;5889436;2925676;8899389;60.74%<FNM00181400121-A> 

That ;nvme2n1 line is from client B, and doesn't belong where it is.

I think the best solution might be to add an option that would open a separate output file for each server stream (and possibly concatenate them into a single file at the termination of the run), although there might be other ways to accomplish it. Is this a known issue, and has anyone else reported it?

Thanks!

**Comment by bengland2** [comment] 2018-09-07 12:13
@jml9904, could it be related to [this PR](https://github.com/axboe/fio/pull/69) that I never got into fio.   Also see [this post from years ago](https://www.spinics.net/lists/fio/msg03860.html).  Is this what happened to you?  Could you try this fix and see if it helps you?  If so then we can rebase and resurrect this PR.

**Comment by jml9904** [comment] 2018-09-07 15:31
OK... found a little time between other things. I re-ran the original test (above) to ensure that the problem reproduced -- it did -- and then built with the PR from https://github.com/axboe/fio/pull/69/commits. 10 runs later, the issue has yet to re-occur. Can we resurrect?

**Comment by bengland2** [comment] 2018-09-07 15:46
thank you for building and testing this, I'm happy to resurrect.  I can't promise to get to it today, but I think within a week I can have the PR in place again - just have to rebase it.

**Comment by jml9904** [comment] 2018-09-07 16:06
Sounds good!

**Comment by axboe** [comment] 2018-09-07 16:15
Not sure that dprint(FD_NET, ...) is the right approach here, that's strictly for debug output. Hence with the default options, the text would not be visible to the client unless --debug=net is set. With --debug=net set, do you still not see intermingling?

**Comment by jml9904** [comment] 2018-09-07 16:53
Weird. With --debug=net set (and without the patch) the intermingling does not reproduce. As soon as I run without --debug=net, it returns.

**Comment by axboe** [comment] 2018-09-07 17:05
Do you have an easy way to reproduce this?

**Comment by jml9904** [comment] 2018-09-07 17:07
Yup. Just open three terminal sessions. In two of them run

fio --server, 8765
fio --server, 8766

and in the third, run:

./fio --minimal --eta=never --client=xx.xx.xx.xx,8765 ./00test1.fio --client=xx.xx.xx.xx,8766 ./00test1.fio

**Comment by axboe** [comment] 2018-09-07 17:43
Sorry for being dense, but that doesn't reproduce anything for me. Wasn't the point to have json output, which then got intermingled with some other output?

**Comment by axboe** [comment] 2018-09-07 17:46
Also might want to include the contents of 00test1.fio, in case they matter (group_reporting comes to mind).

**Comment by jml9904** [comment] 2018-09-07 17:47
No density at all :) But... when I do exactly those steps, I start with 
hostname=gorgonzola, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.5-59-g7c54, flags=1
hostname=gorgonzola, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.5-59-g7c54, flags=1
<gorgonzola> 00-test1: (g=0): rw=randrw, <gorgonzola> 00-test1: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
ioengine=libaio, iodepth=64
<gorgonzola> Starting <gorgonzola> Starting 1 process1 process

So that last line is indicative of the problem. Here's the config file -- I tried with group-reporting=0 but it didn't change anything:


 cat 00test1.fio 
[global]
ioengine=libaio
direct=1
refill_buffers=1
norandommap=1
randrepeat=0
group_reporting=1
rw=randrw
time_based
runtime=10
loops=1

[00-test1]
filename=/dev/nvme0n1
rwmixread=50
rwmixwrite=50
iodepth=64
numjobs=1
bs=4096

**Comment by axboe** [comment] 2018-09-07 17:48
Ah ok, I think I follow now. So you're complaining about the startup lines, like hostname=gorgonzola bla bla and so on.

**Comment by axboe** [comment] 2018-09-07 17:48
Let me see what the best approach would be...

**Comment by jml9904** [comment] 2018-09-07 17:53
It's not just the startup lines. I also see corruption in the data portion occasionally, but not nearly as often. Same sort of thing -- lines just intermingled with others. For example:

Disk stats (read/write):
 12 ;nvme24n1;121;5892;0;0;7;32679;28589;36.33%;nvme13n1;42;47040;0;0;7;1412064;1403623;85.28%;nvme18n1;42;47040;0;0;5;915946;907639;71.31%;nvme20n1;42;47040;0;0;1;    536640;528400;78.70%;nvme8n1;42;47008;0;0;10;338285;329860;70.85%;nvme9n1;42;47008;0;0;6;300628;294009;71.10%;nvme17n1;42;46976;0;0;4;1101512;1092355;83.86%;nvm    e12n1;42;46944;0;0;8;1532789;1523207;86.56%;nvme2n1;42;46848;0;0;10;561698;553163;85.14%;nvme15n1;42;46848;0;0;7;435110;426148;73.11%;nvme10n1;42;46848;0;0;4;31    4694;306718;71.45%;nvme11n1;42;46784;0;0;4;4934492;4924721;91.29%;nvme23n1;40;5824;0;0;3;17023;13052;38.06%;nvme6n1;0;46592;0;0;0;915477;906448;85.79%;nvme22n1;    0;5824;0;0;0;15715;11491;36.96%;nvme14n1;0;46560;0;0;0;3003782;2994099;89.16%;nvme19n1;0;46496;0;0;0;942616;935491;84.39%;nvme0n1;0;46322;0;0;0;1305857;1322714;    83.60%3;fio-3.5-45-g69b98f;DEVS_ALL-000-100-002-050-025-4194304;0;0;0;0;0;0;0;0;0.000000;0.000000;0;0;0.000000;0.000000;1.000000%=0;5.000000%=0;10.000000%=0;20.    000000%=0;30.000000%=0;40.000000%=0;50.000000%=0;60.000000%=0;70.000000%=0;80.000000%=0;90.000000%=0;95.000000%=0;99.000000%=0;99.500000%=0;99.900000%=0;99.9500    00%=0;99.990000%=0;0%=0;0%=0;0%=0;0;0;0.000000;0.000000;0;0;0.000000%;0.000000;0.000000;149114880;14525119;3546;10266;66;15815;131.671530;86.278059;2095;720506;    26216.706881;51277.516794;1.000000%=2736;5.000000%=2834;10.000000%=2899;20.000000%=4620;30.000000%=5472;40.000000%=6717;50.000000%=8585;60.000000%=11599;70.0000    00%=16711;80.000000%=28442;90.000000%=72876;95.000000%=110624;99.000000%=235929;99.500000%=312475;99.900000%=574619;99.950000%=624951;99.990000%=666894;0%=0;0%=    0;0%=0;2781;720683;26348.548551;51284.426989;106071;417792;2.046613%;297273.037000;58057.573663;8.871419%;0.901790%;34289;0;2022;0.1%;99.9%;0.0%;0.0%;0.0%;0.0%;    0.0%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;14.01%;41.31%;18.70%;11.85%;7.97%;5.30%;0.62%;0.23%;0.00%;0.00%;0.00%

Note how that "3;fio-3.5-45-g69b98f;DEVS_ALL" just pops up right in the middle of the line.

**Comment by axboe** [comment] 2018-09-07 17:58
There's really nothing preventing this, if output comes in split. A good example of that is the start output. We first send the "Starting " line, then send the remainder. I can definitely fix that one up, but broken up output exists in other places too... This is the real issue, not where we end up logging. That'll just impact timing.

**Comment by jml9904** [comment] 2018-09-07 18:01
That's why I suspect opening a separate output stream (file) for each client and possibly combining them at the end of the run might be a better approach? The crunched header stuff doesn't really bother me -- it's just annoying -- but the data being munged is definitely causing pain.

**Comment by axboe** [comment] 2018-09-07 18:05
We could do separate files, but that doesn't really work well with collating output from multiple jobs. I committed a few basic fixes for not doing this, just needs to be extended:

http://git.kernel.dk/cgit/fio/commit/?id=a41fc5291d25a02adfcca11915d41a645eaed502
http://git.kernel.dk/cgit/fio/commit/?id=fecea437a7272916e00228b99b74e05ee8e0c957

**Comment by jml9904** [comment] 2018-09-07 18:11
Looks like it'll help. As soon as I can get out from under the current testing (probably Monday) I'll give it a whirl. Thanks!

**Comment by axboe** [comment] 2018-09-07 18:13
Probably just have to hunt down more of these...

**Comment by axboe** [comment] 2018-09-07 18:30
For the minimal output split, maybe try changing this in server.h:

`        FIO_SERVER_MAX_FRAGMENT_PDU     = 1024,
`
and set it to eg 4096 or something like that.

**Comment by jml9904** [comment] 2018-09-07 18:37
Worth a try. If it keeps the data intact that'd solve the problem for me.

**Comment by jml9904** [comment] 2018-09-07 18:40
Will do. Have a good weekend, and thanks again!

**Comment by jml9904** [comment] 2018-09-07 18:56
Clean build of fio-3.9-4-g71cc produces no output in --minimal mode:

# ./fio --minimal --eta=never --client=xx.xx.xx.xx,8765 ./00test1.fio --client=xx.xx.xx.xx,8766 ./00test1.fio
00-test1: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
00-test1: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
Starting 1 process
Starting 1 process

Without --minimal, it does produce the normal output:

# ./fio --client=xx.xx.xx.xx,8765 ./00test1.fio --client=xx.xx.xx.xx,8766 ./00test1.fio
hostname=gorgonzola, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.9-4-g71cc, flags=1
hostname=gorgonzola, be=0, 64-bit, os=Linux, arch=x86-64, fio=fio-3.9-4-g71cc, flags=1
<gorgonzola> 00-test1: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
<gorgonzola> 00-test1: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
<gorgonzola> Starting 1 process
<gorgonzola> Starting 1 process
00-test1: (groupid=0, jobs=1): err= 0: pid=26991: Fri Sep  7 14:53:45 20180s]
   read: IOPS=81.1k, BW=317MiB/s (332MB/s)(3169MiB/10002msec)
    slat (usec): min=2, max=283, avg= 3.37, stdev= 1.56
    clat (usec): min=11, max=9703, avg=313.36, stdev=536.38
     lat (usec): min=25, max=9707, avg=316.88, stdev=536.38
    clat percentiles (usec):

<... more ...>

**Comment by axboe** [comment] 2018-09-07 19:01
Looks like something broke minimal for backend, not related to these changes. Let me take a quick look...

**Comment by axboe** [comment] 2018-09-07 19:07
OK, pull again and retry the test, thanks.

**Comment by axboe** [comment] 2018-09-07 19:33
Can't seem to reproduce the intermingled minimal output at all :-(

**Comment by axboe** [comment] 2018-09-07 20:26
Please pull again and use current -git and see if it works for you now. Hopefully it does. You want to be on (at least) this sha:

```
commit 7c6686fcd9dc145c4dbab907ab29d2336f0ba935 (HEAD -> master, origin/master, origin/HEAD)
Author: Jens Axboe <axboe@kernel.dk>
Date:   Fri Sep 7 14:25:30 2018 -0600

    client: switch to per-client buffer
```

**Comment by jml9904** [comment] 2018-09-07 21:11
Will do. It'll be Monday, though. Thanks a million... will let you know.

**Comment by axboe** [comment] 2018-09-07 21:44
That's fine, thanks.

**Comment by axboe** [comment] 2018-09-10 14:16
Perfect, thanks for testing!

**Closed by axboe** 2018-09-10 14:16 UTC
