### ISSUE TITLE
Question: set verify=pattern verify fail 

### ISSUE THREAD

**Issue by ZongWenqian** [axboe/fio#962] opened 2020-04-15 03:26 UTC
Hi Sir:

### **I do a ssd test, write command:**
fio --name=3:0:0:0 --filename=/dev/sdc --size=25165552k --rw=write --bs=904k --ioengine=libaio --iodepth=4 --offset=66613048k --verify=pattern --do_verify=0 --verify_backlog=500K --verify_pattern=%o

### **After power down and power on ssd, send fio read command , but verify data fail:**
[2020-04-14 23:39:24,793] [INFO]: fio --name=3:0:0:0 --filename=/dev/sdc --size=25165552k --rw=read --bs=904k --ioengine=libaio --iodepth=4 --offset=66613048k --verify=pattern --do_verify=1 --verify_dump=1 --verify_backlog=500K --verify_pattern=%o
[2020-04-14 23:42:20,905] [ERROR]: command: fio --name=3:0:0:0 --filename=/dev/sdc --size=25165552k --rw=read --bs=904k --ioengine=libaio --iodepth=4 --offset=66613048k --verify=pattern --do_verify=1 --verify_dump=1 --verify_backlog=500K --verify_pattern=%o error, return:3:0:0:0: (g=0): rw=read, bs=(R) 904KiB-904KiB, (W) 904KiB-904KiB, (T) 904KiB-904KiB, ioengine=libaio, iodepth=4
fio-3.7
Starting 1 process
fio: got pattern 'e0', wanted '20'. Bad bits 2
fio: bad pattern block offset 417793
pattern: verify failed at file /dev/sdc offset 92896370688, length 21
       received data dumped as sdc.92896370688.received
       expected data dumped as sdc.92896370688.expected
fio: verify type mismatch (41230 media, 18 given)
fio: got pattern '60', wanted '40'. Bad bits 1
fio: bad pattern block offset 1
pattern: verify failed at file /dev/sdc offset 92897296384, length 26
       received data dumped as sdc.92897296384.received
       expected data dumped as sdc.92897296384.expected
fio: verify type mismatch (48393 media, 18 given)
fio: pid=7348, err=84/file:io_u.c:2030, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character

3:0:0:0: (groupid=0, jobs=1): err=84 (file:io_u.c:2030, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character): pid=7348: Tue Apr 14 23:42:20 2020
   read: IOPS=152, BW=135MiB/s (141MB/s)(22.0GiB/174844msec)
    slat (usec): min=5375, max=13103, avg=6429.25, stdev=905.16
    clat (msec): min=18, max=247, avg=19.63, stdev= 1.65
     lat (msec): min=25, max=256, avg=26.05, stdev= 1.53
    clat percentiles (usec):
     |  1.00th=[18482],  5.00th=[18482], 10.00th=[18482], 20.00th=[18482],
     | 30.00th=[18482], 40.00th=[18482], 50.00th=[20317], 60.00th=[20317],
     | 70.00th=[20317], 80.00th=[20317], 90.00th=[20317], 95.00th=[20317],
     | 99.00th=[20317], 99.50th=[20317], 99.90th=[20317], 99.95th=[20317],
     | 99.99th=[22414]
   bw (  KiB/s): min=106672, max=139216, per=100.00%, avg=138146.44, stdev=1963.76, samples=349
   iops        : min=  118, max=  154, avg=152.81, stdev= 2.17, samples=349
  lat (msec)   : 20=40.62%, 50=59.37%, 250=0.01%
  cpu          : usr=1.82%, sys=4.40%, ctx=94418, majf=0, minf=931
  IO depths    : 1=0.1%, 2=0.1%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=26670,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=4

Run status group 0 (all jobs):
   READ: bw=135MiB/s (141MB/s), 135MiB/s-135MiB/s (141MB/s-141MB/s), io=22.0GiB (24.7GB), run=174844-174844msec

Disk stats (read/write):
  sdc: ios=94178/0, merge=1/0, ticks=337287/0, in_queue=337231, util=99.87%

### **Question:**
**1. How to use parameter "--verify=pattern"?
2. Weather set the parameters are limited, example: bs need 4k align, offset and size need bs align??**

**Comment by sitsofe** [comment] 2020-04-15 06:13
Hi @ZongWenqian:

> 1. How to use parameter "--verify=pattern"?

```
fio --name=3:0:0:0 [...] --size=25165552k [...] --offset=66613048k
```

Is your `size` smaller than your `offset`?
```
>>> 25165552 -66613048
-41447496
```

I'm not sure what you're hoping to happen by doing that. Can you explain further?

> After power down and power on ssd

Did you let the job run to completion or did you interrupt it? As there is no `end_fsync=1` and you're not using how do you know the data isn't just rolling around the kernel's cache (or the disk's cache for that matter)? I'm also a little worried by `--ioengine=libaio --iodepth=4` without `direct=1`... do you know about the limitations of the old-style kernel aio when it comes to asynchrony with buffered I/O (see https://github.com/axboe/fio/issues/512#issuecomment-356604533 )?

Aside from that, I think your split verify should work (although you could have used [verify_only](https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-arg-verify-only) and kept `rw=write`)...

> 2. Weather set the parameters are limited, example: bs need 4k align, offset and size need bs align??

Unless you are using `direct=1` it's not mandatory for the offset and size to be multiples of the block size but you might end up with an unwritten/unverified region at the end.

**Comment by ZongWenqian** [comment] 2020-04-15 06:36
@sitsofe Thank you for your answer！

Following is my test step：
1. Use following fio command to write disk：
fio --name=3:0:0:0 --filename=/dev/sdc --size=25165552k --rw=write --bs=904k --ioengine=libaio --iodepth=4 --offset=66613048k **--verify=pattern** --do_verify=0 --verify_backlog=500K --**verify_pattern=%o**
2. power down ssd；
3. power on ssd；
4. Check with command “lsblk”， Make sure ssd is found in os;
5. Use following fio command to read disk:
 fio --name=3:0:0:0 --filename=/dev/sdc --size=25165552k --rw=read --bs=904k --ioengine=libaio --iodepth=4 --offset=66613048k --verify=pattern --do_verify=1 --verify_dump=1 --verify_backlog=500K --verify_pattern=%o
6. Loop step1~step5 serval times, verify fail will occurr

Question：
```
Is your size smaller than your offset?

>>> 25165552 -66613048
-41447496
```
1. In my opinion, “offset” means the starting position of  fio write/read. Why size should be larger than offset?
2. I set verify=md5, then test above test step, test pass.
But I set verify = pattern , verify fail!
In fio command, I set size=random.randint(5, 30)g, offset = random.randint(ssd max size-size)g, bs = random.randint(4k, 1M) in my test.

BRS
ZongWenqian

**Comment by sitsofe** [comment] 2020-04-16 18:51
> Following is my test step：

Do you do a sync/fsync BEFORE you do 2.? I don't know how you guarantee the data reached the disks non-volatile region unless you do...

> 1. In my opinion, “offset” means the starting position of fio write/read. Why size should be larger than offset?

My mistake - I did a quick check and it's as you say.

> 2. I set verify=md5, then test above test step, test pass.

That's a bit strange. I guess the thing about md5 (and other fio checksum based) verification is that it checks the data looks intact but can't catch the case that correct data between two exactly sized blocks has been swapped around...

> 3. ### In issue #961, I test power down ssd interrupt write command. In the test, verify data fail when set ioengine=libaio.

Seems odd that it would behave different to any other I/O engine given you aren't setting an iodepth...

One thing to definitely check is this though:

```
fio-3.7
```

We (upstream) don't support only support the latest fio. See https://github.com/axboe/fio/releases for which version we're up to. Can you see if you can reproduce the issue with a recent fio?

**Comment by sitsofe** [comment] 2020-05-10 09:21
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2020-05-10 09:21 UTC
Labels: needreporterinfo
