### ISSUE TITLE
Issue using zer_buffers and verify options simultaneously

### ISSUE THREAD

**Issue by sellerb5** [axboe/fio#86] opened 2015-06-09 00:03 UTC
I am trying to write all zeros to a volume and read them back. 
Able to write all zeros to the volume using `--zero_buffers` option. 
However if I use verify=crc32|md5|meta it doesn't generate zero buffers any more. 
Is there any work around it?

**Comment by axboe** [comment] 2015-06-09 00:47
'meta' would be the most appropriate, but that one also fills other information to the verify header to be able to verify across write cycles, etc. I was going to suggest that we add a verify=pattern, but actually it looks like that would work right now with NOT setting verify but setting verify_pattern=0x00. Can you try?

**Comment by axboe** [comment] 2015-06-09 00:49
Actually, I can see that would fail, since it would not have a verify header. OK, I think we need to add verify=pattern if you want to verify strict zeroes. The way fio sets up verification is that each written block has a generic fio header with some values, and a header corresponding to what the verify type is. Even without the meta header, the fio header would still be there.

**Comment by axboe** [comment] 2015-06-09 02:44
Committed this. Use verify=pattern and set the pattern you want. In your case, you want verify_pattern=0x00. If you do that, fio will write just the pattern, and verify just the pattern. No specific headers included.

**Comment by axboe** [comment] 2015-06-09 02:44
http://git.kernel.dk/?p=fio.git;a=commit;h=5924538164650c6c0dc0e866d6ed15eb199ed020

**Closed by axboe** 2015-06-09 02:44 UTC

**Comment by sellerb5** [comment] 2015-06-09 05:54
Great!! Thanks a lot for the quick check in. I will give it a try asap and update.

**Comment by sellerb5** [comment] 2015-06-09 06:29
`--verify=pattern` with `--verify_pattern=0x00` works great. 

However, I was kind of curious to see the tool detecting the mismatch. So tried to read back with a different pattern while using `--verify_dump=1` in parallel. It does reports the mismatch  when I tried reading back using `--verify_pattern=0x00A`, however the dump files (.recieved/.extected) are 0 byte

`fio --filename=/tmp/bsrange --size=500M --rw=read --ioengine=libaio --direct=1 --time_based=1 --verify_dump=1 --threads=1 --name=test --bsrange=4k-1024k --verify=pattern --verify_pattern=0x00A`

<output truncated>
fio: bad pattern block offset 0
       received data dumped as bsrange.0.received
       expected data dumped as bsrange.0.expected
fio: verify type mismatch (0 media, 14 given)
fio: pid=31986, err=84/file:io_u.c:1875, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character

test: (groupid=0, jobs=1): err=84 (file:io_u.c:1875, func=io_u_queued_complete, error=Invalid or incomplete multibyte or wide character): pid=31986: Mon Jun  8 23:27:55 2015
  read : io=151552B, bw=37000KB/s, iops=250, runt=     4msec
< output truncated>

`# ls -ltr bsrange.0.*`
-rw-r--r--. 1 root root 0 Jun  8 23:27 bsrange.0.received
-rw-r--r--. 1 root root 0 Jun  8 23:27 bsrange.0.expected

**Comment by axboe** [comment] 2015-06-09 13:56
I think the dump parts rely on the header including the size. But we don't have that with the pattern verifies. But I can fix that up, though.

**Comment by axboe** [comment] 2015-06-09 14:06
This should fix it:

http://git.kernel.dk/?p=fio.git;a=commit;h=9ba987cce53801e1f793798a5a8dc20af1193768

**Comment by sellerb5** [comment] 2015-06-09 22:26
Great. It works as expected now. Thanks for your help.

**Comment by sellerb5** [comment] 2015-06-09 22:51
Actually ran in to another strange behavior with verify=pattern option.

Did writes using:
`fio --filename=/dev/sdc --rw=randwrite --ioengine=libaio --direct=1 --time_based=1 --verify_dump=1 --threads=1 --name=test --bsrange=512-3584 --verify=pattern --verify_pattern=0x00`

Reading back to verify:
`fio --filename=/dev/sdc --rw=read --ioengine=libaio --direct=1 --time_based=1 --verify_dump=1 --threads=1 --name=test --bsrange=512-3584 --verify=pattern --verify_pattern=0x00`

Second command fails with corruption. The issue is, the dump file `sdc.9216.expected` shows non-zero pattern. Something sounds fishy. Is there anything wrong with my usage?

# hexdump -Cv sdc.9216.expected
00000000  00 06 00 00 00 00 00 00  30 01 00 00 00 00 00 00  |........0.......|
00000010  10 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  f0 b6 96 90 20 7f 00 00  01 00 00 00 00 00 00 00  |.... ...........|
00000040  60 b6 96 90 20 7f 00 00  01 00 00 00 00 00 00 00  |`... ...........|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

**Comment by sitsofe** [comment] 2017-12-30 09:49
@sellerb5 - are you still able to reproduce the problem mentioned in your June comment?
