### ISSUE TITLE
Allow < 50 buffer_compress_percentage and buffer

### ISSUE THREAD

**Issue by Ornias1993** [axboe/fio#891] opened 2020-01-02 23:21 UTC
Current behaviour:
When running fio with a buffer_compress_percentage, values above and below 50 have the same effect. Simply put 30 == 70, 20 == 80 and 10 == 90

Expected behavior:
`20` should be: 20% random, 80% compressable buffer
`80` should be: 80% random, 20% compressable buffer
`0` should be compressable buffer only
`100` should be incompressable buffer only

Or everything the other way around.... 
In any case, values above and below 50 shouldn't give the same results.

**Comment by axboe** [comment] 2020-01-03 19:29
Please include how you are reproducing this. Just ran:

```
[comp]
size=128m
rw=randwrite
bs=4k
filename=128m
buffer_compress_percentage=90
```

and  the gzip'ed file is 11% of the original (so pretty close), and I tried =10 which ends up with the file being 90% of the original (which is spot on).

As the reporting bugs file says, any bug report should include:

- What you think the bug is
- How to reproduce
- Fio version

Note that for compression, each BLOCK that fio writes is compressible to the extent specified.

**Comment by Ornias1993** [comment] 2020-01-03 19:48
@axboe that works great as long as no buffer-pattern is used.
As soon as one uses a buffer pattern that logic does not work.

If you want to add instructions for creating issues, please refer to github on how to create those. Currently no info is being requested on creation of an issue and I'm certainly not going to dig through documentation to write something down this easy.

**Comment by axboe** [comment] 2020-01-03 19:49
But since I asked nicely, please provide exactly what you ran. In the spirit of making it _easy_ for someone to reproduce.

**Comment by axboe** [comment] 2020-01-03 19:52
Because if I add ```buffer_pattern=0x5aa5aaa5``` it still behaves as expected for me (used =10 and =90 again). To this:

> If you want to add instructions for creating issues, please refer to github on how to create those. Currently no info is being requested on creation of an issue and I'm certainly not going to dig through documentation to write something down this easy.

I'm using github as a backup service, I really have never requested people file bug reports here. In fact, I'd prefer it people didn't and simply sent them in over email. I don't _mind_ bug reports here, but please provide the requested info, especially when asked.

**Comment by Ornias1993** [comment] 2020-01-03 19:57
Try:

[global]
filename_format=file$jobnum
group_reporting=1
fallocate=0
ioengine=psync
bs=1024k
rw=write
thread=1
directory=(Pick one)
numjobs=16
filesize=100
randseed=1234
buffer_compress_percentage=30 (and 70)
buffer_pattern=0xdeadface
buffer_compress_chunk=0

Fio version:
Latest on debian 10 repo.

**Comment by Ornias1993** [comment] 2020-01-03 20:02
> I'm using github as a backup service

Do we need to smell that? Feel that? or have some sort of sixth sense?

> In fact, I'd prefer it people didn't

Look, I don't mind if you don't want them... really... But please don't expect people to dig through files. It's not usual nor acceptable on most of github.

> simply sent them in over email

If that was clear to me I would've, I'm sure it's in the readme that hurt my eyes so bad I can read just one alinea at a time. Sorry.

**Comment by axboe** [comment] 2020-01-03 20:06
Dude, I'm done with your attitude, I think this is the worst I've seen since I made fio available 15 years ago. I'm going to close this one as "not something I want to deal with". If you change your mind and want to behave like an adult, feel free to reopen.

**Closed by axboe** 2020-01-03 20:06 UTC

**Comment by Ornias1993** [comment] 2020-01-03 20:11
> As the reporting bugs file says, any bug report should include:

That sounded pretty scoffy to me, I'm willing to work with you... for sure... 
But I don't expect to be scoffed at. Which it sounded like to me.

I'm sorry for said misunderstanding.
I tried very hard to ammend my report with everything you asked for and, as requested, would refraign from two things from now on: Fighting with you and reporting bugs via github next time.

Can we  both agree and both continue like adults from now on?

**Comment by Ornias1993** [comment] 2020-01-03 20:12
@axboe 
I don't seem to be able to reopen on this repo for some reason....

Consider it reopened ;)
