### ISSUE TITLE
Runtime parameter being ingnored when in use with rate control parameters

### ISSUE THREAD

**Issue by jamesRowe74** [axboe/fio#1017] opened 2020-06-15 19:01 UTC
Hi, 
I noticed that the length of the workloads i am running is not constant with the config , which is just a constant value of 2800s over 100 tests. I only see this when using the the "rate" parameter that the runtime is sometimes ignored. this brings me to wonder how rate controls performance because throughout these tests the ones that ran to long had power consumption values close to max performance and the other half idle power consumption. but after 11 workloads returns to normal runtime and power consumption is not max/idle as expected. we saw this behavior on the first dozen or so tests for both read and write for are larger transfer sizes but not on small transfer sizes that used rate_iops. Have you seen any issues with workloads ignoring runtime? Also, is there a reason why FIO is idling the drive during performance? I attached workload configs some performance summaries with altered values.
[LinBAT_Log.txt](https://github.com/axboe/fio/files/4782287/LinBAT_Log.txt)
[LinBAT_LogFile_1_fiocfg.txt](https://github.com/axboe/fio/files/4782288/LinBAT_LogFile_1_fiocfg.txt)
[LinBAT_LogFile_2_fiocfg.txt](https://github.com/axboe/fio/files/4782289/LinBAT_LogFile_2_fiocfg.txt)
[LinBAT_LogFile_3_fiocfg.txt](https://github.com/axboe/fio/files/4782290/LinBAT_LogFile_3_fiocfg.txt)
[LinBAT_LogFile_4_fiocfg.txt](https://github.com/axboe/fio/files/4782291/LinBAT_LogFile_4_fiocfg.txt)
[LinBAT_LogFile_5_fiocfg.txt](https://github.com/axboe/fio/files/4782292/LinBAT_LogFile_5_fiocfg.txt)
[LinBAT_LogFile_6_fiocfg.txt](https://github.com/axboe/fio/files/4782293/LinBAT_LogFile_6_fiocfg.txt)
[LinBAT_LogFile_7_fiocfg.txt](https://github.com/axboe/fio/files/4782294/LinBAT_LogFile_7_fiocfg.txt)
[LinBAT_LogFile_8_fiocfg.txt](https://github.com/axboe/fio/files/4782295/LinBAT_LogFile_8_fiocfg.txt)
[LinBAT_LogFile_9_fiocfg.txt](https://github.com/axboe/fio/files/4782296/LinBAT_LogFile_9_fiocfg.txt)
[LinBAT_LogFile_10_fiocfg.txt](https://github.com/axboe/fio/files/4782297/LinBAT_LogFile_10_fiocfg.txt)
[LinBAT_LogFile_11_fiocfg.txt](https://github.com/axboe/fio/files/4782298/LinBAT_LogFile_11_fiocfg.txt)
[LinBAT_LogFile_12_fiocfg.txt](https://github.com/axboe/fio/files/4782299/LinBAT_LogFile_12_fiocfg.txt)

**Comment by sitsofe** [comment] 2020-06-16 05:47
@jamesRowe74 Hi,

(It helps if you include an fio jobfile as just plain text within the body of your comment when it is fairly small as it saves clicking through, downloading etc. I'll reproduce one here with fixed formatting:
```
[global]
ioengine=windowsaio
direct=1
buffered=0
size=100%
randrepeat=0
time_based
ramp_time=300
norandommap
group_reporting
filename=\\.\PHYSICALDRIVE2

[test]
stonewall
ba=131072
bs=131072
iodepth=256
numjobs=16
rate=250m
rw=write
runtime=2500
```
)

> Have you seen any issues with workloads ignoring runtime?

In the above were you expecting this job to run for 2500 seconds? If so are you aware that by default without extra options `runtime` means "exit IF you run longer than this time" (so it's a cap) rather than "run for exactly this time"? See the [fio documentation for runtime](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-runtime)  and [timebased](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-time-based).

> Also, is there a reason why FIO is idling the drive during performance?

If you set a `rate` lower than the performance your drive can achieve then if during first half of a period of one second fio has already sent 250 megabytes of data then for the second half of the period it can't do anything otherwise it will exceed your rate ([rate is a cap](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-rate)). This is an extreme example but hopefully that illustrates the scenario. What did you want to happen?

(FYI: As this isn't so much an issue in fio and more of a "How do I/Why is?" question it is better aimed at the [fio mailing list](https://github.com/axboe/fio/blob/fio-3.12/README#L58) (note that the list only accepts plain text emails) but that's more for next time)

**Comment by sitsofe** [comment] 2020-06-27 05:29
@jamesRowe74 did the above help you get past your issue and if so can you close this issue? Thanks!

**Comment by sitsofe** [comment] 2020-07-03 06:19
Closing due to lack of reply from reporter. If this issue is still happening with the latest fio (see https://github.com/axboe/fio/releases to find out which version that is) please reopen. Thanks!

**Closed by sitsofe** 2020-07-03 06:19 UTC
Labels: needreporterinfo
