### ISSUE TITLE
Windows version appears to fault consistently for 2022 builds.

### ISSUE THREAD

**Issue by jaxjexjox** [axboe/fio#1418] opened 2022-07-04 05:29 UTC
**Please acknowledge the following before creating a ticket**

- [ X] I have read the GitHub issues section of [REPORTING-BUGS](../blob/master/REPORTING-BUGS).

**Description of the bug:**
Upon running FIO the command line simply drops back after a few seconds with no output, event viewer has crash logs.

**Environment**: 
Windows 10, latest pactches as of 04/07/2022, machine is a genuine HP small business system, not a home build.
Prompt is an administrator prompt

**fio version**: 

Literally tested all versions from 2022 (as per windows build):

fio-3.29-154-g06bb snapshot released
x64 installer: [fio-3.29-154-g06bb-x64.msi](https://bsdio.com/fio/releases/fio-3.29-154-g06bb-x64.msi)
x86 installer: [fio-3.29-154-g06bb-x86.msi](https://bsdio.com/fio/releases/fio-3.29-154-g06bb-x86.msi)
fio-3.29 released
x64 installer: [fio-3.29-x64.msi](https://bsdio.com/fio/releases/fio-3.29-x64.msi)
x86 installer: [fio-3.29-x86.msi](https://bsdio.com/fio/releases/fio-3.29-x86.msi)

**Reproduction steps**

Install application.
Type fio from elevated prompt
No response

Event Viewer results: (EventID 1000):

Faulting application name: fio.exe, version: 0.0.0.0, time stamp: 0x624c997a
Faulting module name: fio.exe, version: 0.0.0.0, time stamp: 0x624c997a
Exception code: 0xc000001d
Fault offset: 0x000a5326
Faulting process id: 0x29b0
Faulting application start time: 0x01d88f64d81d5c7c
Faulting application path: C:\Program Files (x86)\fio\fio.exe
Faulting module path: C:\Program Files (x86)\fio\fio.exe
Report Id: 705356e9-7af2-49c5-a848-47edf447fb67
Faulting package full name: 
Faulting package-relative application ID: 

Plus (EventID 1005): 

Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program fio.exe because of this error.

Program: fio.exe
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 00000000
Disk type: 0

**PLEASE NOTE**
Builds from earlier than this, run fine, indicating the machine isn't so much of an issue.

Please ALSO note.
I've also copied, the executable files from 2022 - to a spare workstation of mine.  (Literally, the installed binary) and ran them and they work, indicating it's not a damaged file or install issue.

I suspect some kind of incompatibility on my machine, what that is I don't know but if I can test to help, I'm more than happy to.

**Comment by vincentkfu** [comment] 2022-07-05 13:49
Try the AppVeyor installers: https://ci.appveyor.com/project/axboe/fio

Choose an architecture/build chain and then click on the Artifacts tab to find an installer.

This appears to be a duplicate of https://github.com/axboe/fio/issues/1389

**Closed** 2022-07-22 13:38 UTC
